"""Sonzai Python SDK - Client for the Sonzai Mind Layer API."""

from . import providers
from ._client import AsyncSonzai, Sonzai
from ._exceptions import (
    APIError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    ErrorBody,
    FieldError,
    InternalServerError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    SonzaiError,
    StreamError,
    ValidationError,
)
from .types import (
    AcknowledgeResponse,
    Agent,
    AtomicFact,
    CreateAPIKeyResponse,
    DeleteProjectResponse,
    DeleteUserPersonaResponse,
    AgentKBSearchResponse,
    AgentKBSearchResult,
    AgentIndex,
    AgentInstance,
    AgentListResponse,
    BatchImportUser,
    BatchPersonalityEntry,
    BatchPersonalityResponse,
    Big5,
    Big5Trait,
    Breakthrough,
    BreakthroughsResponse,
    ChatChoice,
    ChatMessage,
    ChatResponse,
    ChatUsage,
    ConsolidateResponse,
    ConstellationNode,
    ConstellationResponse,
    CustomLLMConfigResponse,
    CustomState,
    CustomStateListResponse,
    CustomToolDefinition,
    CustomToolListResponse,
    DeleteResponse,
    DeleteWisdomResponse,
    DeliveryAttemptsResponse,
    DialogueResponse,
    DiaryResponse,
    ExternalToolCall,
    ExtractionDimensionDelta,
    ExtractionFact,
    ExtractionHabit,
    ExtractionInnerThoughts,
    ExtractionInterest,
    ExtractionMoodDelta,
    ExtractionPersonalityDelta,
    ExtractionProactive,
    ExtractionRecurring,
    ExtractionRelationshipDelta,
    EvalCategory,
    EvalRun,
    EvalRunListResponse,
    EvalTemplate,
    EvalTemplateCategory,
    EvalTemplateListResponse,
    EvaluationResult,
    Fact,
    FactHistoryResponse,
    FactListResponse,
    ForkResponse,
    ForkStatusResponse,
    GenerateBioResponse,
    GenerateCharacterResponse,
    GeneratedGoal,
    GenerateSeedMemoriesResponse,
    Goal,
    GoalsResponse,
    Habit,
    HabitsResponse,
    ImageGenerateResponse,
    ImportJob,
    InitialGoal,
    InstanceListResponse,
    ListAllFactsResponse,
    InterestsResponse,
    InventoryBatchImportResponse,
    InventoryDirectUpdateResponse,
    InventoryGroupResult,
    InventoryItem,
    InventoryQueryResponse,
    # Inventory
    InventoryUpdateResponse,
    JobUser,
    KBAnalyticsRule,
    # KB Bulk Update
    KBBulkUpdateEntry,
    KBBulkUpdateResponse,
    KBCandidate,
    KBConversionStats,
    KBDocument,
    KBEdge,
    KBEntitySchema,
    KBNode,
    KBNodeHistory,
    KBRecommendationScore,
    KBRelatedNode,
    KBSchemaField,
    KBSearchResponse,
    KBSearchResult,
    KBSimilarityConfig,
    KBTrendAggregation,
    KBTrendRanking,
    KBResolutionInfo,
    # KB — organization-global scope
    KBScope,
    KBNodeWithScope,
    CreateOrgNodeOptions,
    MemoryNode,
    MemoryResetResponse,
    MemoryResponse,
    MemorySearchResponse,
    MemorySearchResult,
    MemorySummary,
    MemoryTimelineResponse,
    ModelVariant,
    MoodAggregateResponse,
    MoodHistoryEntry,
    MoodHistoryResponse,
    MoodResponse,
    MoodState,
    Notification,
    NotificationListResponse,
    PersonalityBehaviors,
    PersonalityDelta,
    PersonalityDimensions,
    PersonalityPreferences,
    PersonalityProfile,
    PersonalityResponse,
    PersonalityShift,
    TraitPrecision,
    PersonalityUpdateResponse,
    PendingCapability,
    PlatformModelsResponse,
    PrimeContentBlock,
    PrimeUserMetadata,
    ProcessResponse,
    ProcessSideEffectsSummary,
    ProjectConfigEntry,
    ProjectConfigListResponse,
    ProjectNotificationListResponse,
    RecentShiftsResponse,
    RelationshipResponse,
    RunRef,
    Schedule,
    ScheduleCreateResponse,
    ScheduleListResponse,
    ScheduleUpcomingResponse,
    ScheduledWakeup,
    SeedMemoriesResponse,
    SessionResponse,
    SetStatusResponse,
    SideEffectExtraction,
    SignificantMoment,
    SignificantMomentsResponse,
    SimulationEvent,
    StructuredColumnMapping,
    StructuredImportSpec,
    SummariesResponse,
    SupportTicket,
    SupportTicketComment,
    SupportTicketHistory,
    TicketDetailResponse,
    TicketListResponse,
    TicketSummary,
    GetToolSchemasResponse,
    Project,
    ProjectAPIKey,
    ProjectAPIKeyList,
    ProjectList,
    RevokeAPIKeyResponse,
    ToolSchema,
    ToolSchemaEntry,
    ToolSchemasResponse,
    UserPersonaList,
    UserPersonaRecord,
    TimeMachineMoodSnapshot,
    TimeMachineResponse,
    TimelineSession,
    TriggerEventResponse,
    UpdateProjectResponse,
    UserOverlayDetailResponse,
    UserOverlaysListResponse,
    UserPersona,
    UserPersonalityOverlay,
    UsersResponse,
    Voice,
    VoiceListResponse,
    VoiceStreamEvent,
    VoiceStreamToken,
    VoiceUsage,
    TTSResponse,
    STTResponse,
    WakeupsResponse,
    WebhookDeliveryAttempt,
    WisdomAuditResponse,
    WebhookEndpoint,
    WebhookListResponse,
    WebhookRegisterResponse,
    # Workbench / AdvanceTime
    AdvanceTimeResponse,
    DiaryEntry,
    WakeupExecution,
)
from ._customizations import AgentCapabilities, ChatStreamEvent, StoredFact

__version__ = "1.4.0"

__all__ = [
    # Clients
    "Sonzai",
    "AsyncSonzai",
    # Provider constants
    "providers",
    # Exceptions
    "SonzaiError",
    "APIError",
    "AuthenticationError",
    "BadRequestError",
    "ConflictError",
    "ErrorBody",
    "FieldError",
    "InternalServerError",
    "NotFoundError",
    "PermissionDeniedError",
    "RateLimitError",
    "StreamError",
    "ValidationError",
    # Types - Agent CRUD
    "Agent",
    "AgentCapabilities",
    "AgentIndex",
    "AgentListResponse",
    "DeleteResponse",
    "DeleteWisdomResponse",
    "SetStatusResponse",
    "UpdateProjectResponse",
    # Types - Chat
    "ChatChoice",
    "ChatMessage",
    "ChatResponse",
    "ChatStreamEvent",
    "ChatUsage",
    "ExternalToolCall",
    # Types - Dialogue / Events
    "DialogueResponse",
    "TriggerEventResponse",
    # Types - Memory
    "AtomicFact",
    "Fact",
    "FactHistoryResponse",
    "FactListResponse",
    "ForkResponse",
    "ForkStatusResponse",
    "MemoryNode",
    "MemoryResetResponse",
    "MemoryResponse",
    "MemorySearchResponse",
    "MemorySearchResult",
    "MemorySummary",
    "MemoryTimelineResponse",
    "SeedMemoriesResponse",
    "TimelineSession",
    # Types - Personality
    "BatchPersonalityEntry",
    "BatchPersonalityResponse",
    "Big5",
    "Big5Trait",
    "PersonalityBehaviors",
    "PersonalityDelta",
    "PersonalityDimensions",
    "PersonalityPreferences",
    "PersonalityProfile",
    "PersonalityResponse",
    "PersonalityShift",
    "TraitPrecision",
    "PersonalityUpdateResponse",
    "RecentShiftsResponse",
    "SignificantMoment",
    "SignificantMomentsResponse",
    "UserOverlayDetailResponse",
    "UserOverlaysListResponse",
    "UserPersonalityOverlay",
    # Types - Context Engine
    "Breakthrough",
    "BreakthroughsResponse",
    "ConstellationNode",
    "ConstellationResponse",
    "DiaryResponse",
    "Goal",
    "GoalsResponse",
    "Habit",
    "InitialGoal",
    "HabitsResponse",
    "InterestsResponse",
    "MoodAggregateResponse",
    "MoodHistoryEntry",
    "MoodHistoryResponse",
    "MoodResponse",
    "MoodState",
    "RelationshipResponse",
    "UsersResponse",
    "WakeupsResponse",
    "WisdomAuditResponse",
    # Types - Instances
    "AgentInstance",
    "InstanceListResponse",
    # Types - Notifications
    "Notification",
    "NotificationListResponse",
    # Types - Sessions
    "SessionResponse",
    # Types - Voice
    "Voice",
    "VoiceListResponse",
    "VoiceStreamEvent",
    "VoiceStreamToken",
    "VoiceUsage",
    "TTSResponse",
    "STTResponse",
    # Types - Generation
    "GenerateBioResponse",
    "GenerateCharacterResponse",
    "GeneratedGoal",
    "GenerateSeedMemoriesResponse",
    "ImageGenerateResponse",
    # Types - Custom States
    "CustomState",
    "CustomStateListResponse",
    # Types - Webhooks
    "DeliveryAttemptsResponse",
    "WebhookDeliveryAttempt",
    "WebhookEndpoint",
    "WebhookListResponse",
    "WebhookRegisterResponse",
    # Types - Project Config
    "ProjectConfigEntry",
    "ProjectConfigListResponse",
    # Types - Custom LLM
    "CustomLLMConfigResponse",
    # Types - Project Notifications
    "ProjectNotificationListResponse",
    "AcknowledgeResponse",
    # Types - Wakeups
    "ScheduledWakeup",
    # Types - Schedules
    "Schedule",
    "ScheduleCreateResponse",
    "ScheduleListResponse",
    "ScheduleUpcomingResponse",
    # Types - Capabilities
    "CustomToolDefinition",
    "CustomToolListResponse",
    "PendingCapability",
    # Types - Process / Extractions
    "ProcessResponse",
    "ProcessSideEffectsSummary",
    "SideEffectExtraction",
    "ExtractionFact",
    "ExtractionPersonalityDelta",
    "ExtractionDimensionDelta",
    "ExtractionMoodDelta",
    "ExtractionHabit",
    "ExtractionInterest",
    "ExtractionRelationshipDelta",
    "ExtractionProactive",
    "ExtractionRecurring",
    "ExtractionInnerThoughts",
    # Types - Consolidation / Summaries
    "ConsolidateResponse",
    "SummariesResponse",
    # Types - Time Machine
    "TimeMachineMoodSnapshot",
    "TimeMachineResponse",
    # Types - Evaluation
    "EvalCategory",
    "EvalRun",
    "EvalRunListResponse",
    "EvalTemplate",
    "EvalTemplateCategory",
    "EvalTemplateListResponse",
    "EvaluationResult",
    "RunRef",
    "SimulationEvent",
    # Types - User Persona
    "UserPersona",
    "UserPersonaRecord",
    "UserPersonaList",
    "DeleteUserPersonaResponse",
    # Types - Projects
    "Project",
    "ProjectList",
    "ProjectAPIKey",
    "ProjectAPIKeyList",
    "CreateAPIKeyResponse",
    "RevokeAPIKeyResponse",
    "DeleteProjectResponse",
    # Types - Inventory
    "BatchImportUser",
    "ImportJob",
    "InventoryUpdateResponse",
    "InventoryQueryResponse",
    "InventoryItem",
    "InventoryGroupResult",
    "InventoryBatchImportResponse",
    "InventoryDirectUpdateResponse",
    "JobUser",
    "KBResolutionInfo",
    "KBCandidate",
    "StoredFact",
    "ListAllFactsResponse",
    "StructuredColumnMapping",
    "StructuredImportSpec",
    # Types - KB Bulk Update
    "KBBulkUpdateEntry",
    "KBBulkUpdateResponse",
    # Types - KB Analytics
    "KBAnalyticsRule",
    "KBConversionStats",
    "KBRecommendationScore",
    "KBSearchResponse",
    "KBSearchResult",
    "KBTrendAggregation",
    "KBTrendRanking",
    # Types - KB Core
    "KBDocument",
    "KBEdge",
    "KBEntitySchema",
    "KBNode",
    "KBNodeHistory",
    "KBRelatedNode",
    "KBSchemaField",
    "KBSimilarityConfig",
    # Types - Organization-global KB
    "KBScope",
    "KBNodeWithScope",
    "CreateOrgNodeOptions",
    # Types - Agent Knowledge Search
    "AgentKBSearchResult",
    "AgentKBSearchResponse",
    # Types - Tool Schemas (BYO-LLM)
    "ToolSchema",
    "ToolSchemaEntry",
    "ToolSchemasResponse",
    "GetToolSchemasResponse",
    # Types - Priming
    "PrimeContentBlock",
    "PrimeUserMetadata",
    # Types - Platform models
    "ModelVariant",
    "PlatformModelsResponse",
    # Types - Workbench
    "AdvanceTimeResponse",
    "DiaryEntry",
    "WakeupExecution",
    # Types - Support tickets
    "SupportTicket",
    "SupportTicketComment",
    "SupportTicketHistory",
    "TicketDetailResponse",
    "TicketListResponse",
    "TicketSummary",
]
