# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the AccountConfig tag."""

from __future__ import annotations

from typing import Any
from sonzai._generated.models import (
    SetAccountConfigOutputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _AccountConfigBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class AccountConfig(_AccountConfigBase):
    def list_account_configs(
        self,
    ) -> Any:
        """List account config keys"""
        path = f"/account/config"
        params = None
        data = self._http.get(path, params=params)
        return data

    def delete_account_config(
        self,
        key: str,
    ) -> Any:
        """Delete an account config key"""
        path = f"/account/config/{key}"
        params = None
        data = self._http.delete(path, params=params)
        return data

    def get_account_config(
        self,
        key: str,
    ) -> Any:
        """Get an account config value"""
        path = f"/account/config/{key}"
        params = None
        data = self._http.get(path, params=params)
        return data

    def set_account_config(
        self,
        key: str,
    ) -> SetAccountConfigOutputBody:
        """Set an account config value"""
        path = f"/account/config/{key}"
        params = None
        data = self._http.put(path, params=params, body=None)
        return SetAccountConfigOutputBody.model_validate(data)


class AsyncAccountConfig(_AccountConfigBase):
    async def list_account_configs(
        self,
    ) -> Any:
        """List account config keys"""
        path = f"/account/config"
        params = None
        data = await self._http.get(path, params=params)
        return data

    async def delete_account_config(
        self,
        key: str,
    ) -> Any:
        """Delete an account config key"""
        path = f"/account/config/{key}"
        params = None
        data = await self._http.delete(path, params=params)
        return data

    async def get_account_config(
        self,
        key: str,
    ) -> Any:
        """Get an account config value"""
        path = f"/account/config/{key}"
        params = None
        data = await self._http.get(path, params=params)
        return data

    async def set_account_config(
        self,
        key: str,
    ) -> SetAccountConfigOutputBody:
        """Set an account config value"""
        path = f"/account/config/{key}"
        params = None
        data = await self._http.put(path, params=params, body=None)
        return SetAccountConfigOutputBody.model_validate(data)
