# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Agents tag."""

from __future__ import annotations

from typing import Any

from sonzai._generated.models import (
    AgentCapabilities,
    AgentDetailResponse,
    AgentIndex,
    CreateAgentBody,
    CreateCustomToolInputBody,
    CustomToolDefinition,
    DeleteAgentOutputBody,
    DeleteCustomToolOutputBody,
    EffectivePostProcessingModelOutputBody,
    ForkAgentInputBody,
    ForkResponse,
    ForkStatusResponse,
    ListCustomToolsOutputBody,
    PaginatedAgentsResponse,
    SetAgentStatusInputBody,
    SetAgentStatusOutputBody,
    UpdateAgentPostProcessingModelInputBody,
    UpdateAgentPostProcessingModelOutputBody,
    UpdateAgentProfileInputBody,
    UpdateAgentProfileOutputBody,
    UpdateAgentProjectInputBody,
    UpdateAgentProjectOutputBody,
    UpdateCapabilitiesInputBody,
    UpdateCustomToolInputBody,
    UpdateCustomToolOutputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _AgentsBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Agents(_AgentsBase):
    def list_agents(
        self,
        *,
        page_size: int | None = 30,
        search: str | None = None,
        project_id: str | None = None,
        include_count: str | None = None,
        limit: int = 100,
    ) -> Page[AgentIndex]:
        """List agents"""
        path = f"/agents"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        if page_size is not None:
            params["page_size"] = page_size
        if search is not None:
            params["search"] = search
        if project_id is not None:
            params["project_id"] = project_id
        if include_count is not None:
            params["include_count"] = include_count
        return Page(
            fetcher=lambda p: self._http.get(path, params=p),
            params=params,
            item_key="items",
            item_parser=AgentIndex.model_validate,
            mode="offset",
        )
    def create_agent(
        self,
        **body_fields: Any,
    ) -> AgentDetailResponse:
        """Create or update an agent"""
        path = f"/agents"
        params = None
        body = encode_body(CreateAgentBody, body_fields)
        data = self._http.post(path, params=params, body=body)
        return AgentDetailResponse.model_validate(data)
    def delete_agent(
        self,
        agent_id: str,
    ) -> DeleteAgentOutputBody:
        """Delete an agent and all data"""
        path = f"/agents/{agentId}"
        params = None
        data = self._http.delete(path, params=params)
        return DeleteAgentOutputBody.model_validate(data)
    def get_agent(
        self,
        agent_id: str,
    ) -> AgentDetailResponse:
        """Get a single agent by ID"""
        path = f"/agents/{agentId}"
        params = None
        data = self._http.get(path, params=params)
        return AgentDetailResponse.model_validate(data)
    def get_capabilities(
        self,
        agent_id: str,
    ) -> AgentCapabilities:
        """Get agent capabilities"""
        path = f"/agents/{agentId}/capabilities"
        params = None
        data = self._http.get(path, params=params)
        return AgentCapabilities.model_validate(data)
    def update_capabilities(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> AgentCapabilities:
        """Update agent capabilities"""
        path = f"/agents/{agentId}/capabilities"
        params = None
        body = encode_body(UpdateCapabilitiesInputBody, body_fields)
        data = self._http.put(path, params=params, body=body)
        return AgentCapabilities.model_validate(data)
    def get_effective_post_processing_model(
        self,
        agent_id: str,
        *,
        chat_model: str,
    ) -> EffectivePostProcessingModelOutputBody:
        """Preview the resolved post-processing model for this agent"""
        path = f"/agents/{agentId}/effective-post-processing-model"
        params: dict[str, Any] = {}
        if chat_model is not None:
            params["chat_model"] = chat_model
        data = self._http.get(path, params=params)
        return EffectivePostProcessingModelOutputBody.model_validate(data)
    def fork_agent(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> ForkResponse:
        """Fork (clone) an agent"""
        path = f"/agents/{agentId}/fork"
        params = None
        body = encode_body(ForkAgentInputBody, body_fields)
        data = self._http.post(path, params=params, body=body)
        return ForkResponse.model_validate(data)
    def get_fork_status(
        self,
        agent_id: str,
    ) -> ForkStatusResponse:
        """Get fork operation status"""
        path = f"/agents/{agentId}/fork/status"
        params = None
        data = self._http.get(path, params=params)
        return ForkStatusResponse.model_validate(data)
    def update_agent_post_processing_model(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> UpdateAgentPostProcessingModelOutputBody:
        """Set or clear agent-scope post-processing model override"""
        path = f"/agents/{agentId}/post-processing-model"
        params = None
        body = encode_body(UpdateAgentPostProcessingModelInputBody, body_fields)
        data = self._http.patch(path, params=params, body=body)
        return UpdateAgentPostProcessingModelOutputBody.model_validate(data)
    def update_agent_profile(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> UpdateAgentProfileOutputBody:
        """Update agent profile fields"""
        path = f"/agents/{agentId}/profile"
        params = None
        body = encode_body(UpdateAgentProfileInputBody, body_fields)
        data = self._http.patch(path, params=params, body=body)
        return UpdateAgentProfileOutputBody.model_validate(data)
    def update_agent_project(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> UpdateAgentProjectOutputBody:
        """Assign an agent to a different project"""
        path = f"/agents/{agentId}/project"
        params = None
        body = encode_body(UpdateAgentProjectInputBody, body_fields)
        data = self._http.patch(path, params=params, body=body)
        return UpdateAgentProjectOutputBody.model_validate(data)
    def set_agent_status(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> SetAgentStatusOutputBody:
        """Activate or deactivate an agent"""
        path = f"/agents/{agentId}/status"
        params = None
        body = encode_body(SetAgentStatusInputBody, body_fields)
        data = self._http.patch(path, params=params, body=body)
        return SetAgentStatusOutputBody.model_validate(data)
    def list_custom_tools(
        self,
        agent_id: str,
    ) -> ListCustomToolsOutputBody:
        """List custom tools"""
        path = f"/agents/{agentId}/tools"
        params = None
        data = self._http.get(path, params=params)
        return ListCustomToolsOutputBody.model_validate(data)
    def create_custom_tool(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> CustomToolDefinition:
        """Create a custom tool"""
        path = f"/agents/{agentId}/tools"
        params = None
        body = encode_body(CreateCustomToolInputBody, body_fields)
        data = self._http.post(path, params=params, body=body)
        return CustomToolDefinition.model_validate(data)
    def delete_custom_tool(
        self,
        agent_id: str,
        tool_name: str,
    ) -> DeleteCustomToolOutputBody:
        """Delete a custom tool"""
        path = f"/agents/{agentId}/tools/{toolName}"
        params = None
        data = self._http.delete(path, params=params)
        return DeleteCustomToolOutputBody.model_validate(data)
    def update_custom_tool(
        self,
        agent_id: str,
        tool_name: str,
        **body_fields: Any,
    ) -> UpdateCustomToolOutputBody:
        """Update a custom tool"""
        path = f"/agents/{agentId}/tools/{toolName}"
        params = None
        body = encode_body(UpdateCustomToolInputBody, body_fields)
        data = self._http.put(path, params=params, body=body)
        return UpdateCustomToolOutputBody.model_validate(data)


class AsyncAgents(_AgentsBase):
    async def list_agents(
        self,
        *,
        page_size: int | None = 30,
        search: str | None = None,
        project_id: str | None = None,
        include_count: str | None = None,
        limit: int = 100,
    ) -> AsyncPage[AgentIndex]:
        """List agents"""
        path = f"/agents"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        if page_size is not None:
            params["page_size"] = page_size
        if search is not None:
            params["search"] = search
        if project_id is not None:
            params["project_id"] = project_id
        if include_count is not None:
            params["include_count"] = include_count

        async def fetcher(p: dict[str, Any]) -> dict[str, Any]:
            return await self._http.get(path, params=p)

        return AsyncPage(
            fetcher=fetcher,
            params=params,
            item_key="items",
            item_parser=AgentIndex.model_validate,
            mode="offset",
        )
    async def create_agent(
        self,
        **body_fields: Any,
    ) -> AgentDetailResponse:
        """Create or update an agent"""
        path = f"/agents"
        params = None
        body = encode_body(CreateAgentBody, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return AgentDetailResponse.model_validate(data)
    async def delete_agent(
        self,
        agent_id: str,
    ) -> DeleteAgentOutputBody:
        """Delete an agent and all data"""
        path = f"/agents/{agentId}"
        params = None
        data = await self._http.delete(path, params=params)
        return DeleteAgentOutputBody.model_validate(data)
    async def get_agent(
        self,
        agent_id: str,
    ) -> AgentDetailResponse:
        """Get a single agent by ID"""
        path = f"/agents/{agentId}"
        params = None
        data = await self._http.get(path, params=params)
        return AgentDetailResponse.model_validate(data)
    async def get_capabilities(
        self,
        agent_id: str,
    ) -> AgentCapabilities:
        """Get agent capabilities"""
        path = f"/agents/{agentId}/capabilities"
        params = None
        data = await self._http.get(path, params=params)
        return AgentCapabilities.model_validate(data)
    async def update_capabilities(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> AgentCapabilities:
        """Update agent capabilities"""
        path = f"/agents/{agentId}/capabilities"
        params = None
        body = encode_body(UpdateCapabilitiesInputBody, body_fields)
        data = await self._http.put(path, params=params, body=body)
        return AgentCapabilities.model_validate(data)
    async def get_effective_post_processing_model(
        self,
        agent_id: str,
        *,
        chat_model: str,
    ) -> EffectivePostProcessingModelOutputBody:
        """Preview the resolved post-processing model for this agent"""
        path = f"/agents/{agentId}/effective-post-processing-model"
        params: dict[str, Any] = {}
        if chat_model is not None:
            params["chat_model"] = chat_model
        data = await self._http.get(path, params=params)
        return EffectivePostProcessingModelOutputBody.model_validate(data)
    async def fork_agent(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> ForkResponse:
        """Fork (clone) an agent"""
        path = f"/agents/{agentId}/fork"
        params = None
        body = encode_body(ForkAgentInputBody, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return ForkResponse.model_validate(data)
    async def get_fork_status(
        self,
        agent_id: str,
    ) -> ForkStatusResponse:
        """Get fork operation status"""
        path = f"/agents/{agentId}/fork/status"
        params = None
        data = await self._http.get(path, params=params)
        return ForkStatusResponse.model_validate(data)
    async def update_agent_post_processing_model(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> UpdateAgentPostProcessingModelOutputBody:
        """Set or clear agent-scope post-processing model override"""
        path = f"/agents/{agentId}/post-processing-model"
        params = None
        body = encode_body(UpdateAgentPostProcessingModelInputBody, body_fields)
        data = await self._http.patch(path, params=params, body=body)
        return UpdateAgentPostProcessingModelOutputBody.model_validate(data)
    async def update_agent_profile(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> UpdateAgentProfileOutputBody:
        """Update agent profile fields"""
        path = f"/agents/{agentId}/profile"
        params = None
        body = encode_body(UpdateAgentProfileInputBody, body_fields)
        data = await self._http.patch(path, params=params, body=body)
        return UpdateAgentProfileOutputBody.model_validate(data)
    async def update_agent_project(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> UpdateAgentProjectOutputBody:
        """Assign an agent to a different project"""
        path = f"/agents/{agentId}/project"
        params = None
        body = encode_body(UpdateAgentProjectInputBody, body_fields)
        data = await self._http.patch(path, params=params, body=body)
        return UpdateAgentProjectOutputBody.model_validate(data)
    async def set_agent_status(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> SetAgentStatusOutputBody:
        """Activate or deactivate an agent"""
        path = f"/agents/{agentId}/status"
        params = None
        body = encode_body(SetAgentStatusInputBody, body_fields)
        data = await self._http.patch(path, params=params, body=body)
        return SetAgentStatusOutputBody.model_validate(data)
    async def list_custom_tools(
        self,
        agent_id: str,
    ) -> ListCustomToolsOutputBody:
        """List custom tools"""
        path = f"/agents/{agentId}/tools"
        params = None
        data = await self._http.get(path, params=params)
        return ListCustomToolsOutputBody.model_validate(data)
    async def create_custom_tool(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> CustomToolDefinition:
        """Create a custom tool"""
        path = f"/agents/{agentId}/tools"
        params = None
        body = encode_body(CreateCustomToolInputBody, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return CustomToolDefinition.model_validate(data)
    async def delete_custom_tool(
        self,
        agent_id: str,
        tool_name: str,
    ) -> DeleteCustomToolOutputBody:
        """Delete a custom tool"""
        path = f"/agents/{agentId}/tools/{toolName}"
        params = None
        data = await self._http.delete(path, params=params)
        return DeleteCustomToolOutputBody.model_validate(data)
    async def update_custom_tool(
        self,
        agent_id: str,
        tool_name: str,
        **body_fields: Any,
    ) -> UpdateCustomToolOutputBody:
        """Update a custom tool"""
        path = f"/agents/{agentId}/tools/{toolName}"
        params = None
        body = encode_body(UpdateCustomToolInputBody, body_fields)
        data = await self._http.put(path, params=params, body=body)
        return UpdateCustomToolOutputBody.model_validate(data)
