# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Analytics tag."""

from __future__ import annotations

from typing import Any
from sonzai._generated.models import (
    AnalyticsOverview,
    AnalyticsRealtimeResponse,
    CostBreakdownResponse,
    CostResponse,
    UsageResponse,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _AnalyticsBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Analytics(_AnalyticsBase):
    def analytics_cost(
        self,
        *,
        start: str | None = None,
        end: str | None = None,
        group_by: str | None = None,
        project_id: str | None = None,
    ) -> CostResponse:
        """Cost analytics with billing-aware pricing"""
        path = f"/analytics/cost"
        params: dict[str, Any] = {}
        if start is not None:
            params["start"] = start
        if end is not None:
            params["end"] = end
        if group_by is not None:
            params["group_by"] = group_by
        if project_id is not None:
            params["project_id"] = project_id
        data = self._http.get(path, params=params)
        return CostResponse.model_validate(data)

    def analytics_cost_breakdown(
        self,
        *,
        month: str | None = None,
        start: str | None = None,
        end: str | None = None,
        project_id: str | None = None,
    ) -> CostBreakdownResponse:
        """Cost breakdown by operation / model / agent"""
        path = f"/analytics/cost/breakdown"
        params: dict[str, Any] = {}
        if month is not None:
            params["month"] = month
        if start is not None:
            params["start"] = start
        if end is not None:
            params["end"] = end
        if project_id is not None:
            params["project_id"] = project_id
        data = self._http.get(path, params=params)
        return CostBreakdownResponse.model_validate(data)

    def analytics_overview(
        self,
    ) -> AnalyticsOverview:
        """Dashboard analytics overview"""
        path = f"/analytics/overview"
        params = None
        data = self._http.get(path, params=params)
        return AnalyticsOverview.model_validate(data)

    def analytics_realtime(
        self,
    ) -> AnalyticsRealtimeResponse:
        """Dashboard analytics realtime"""
        path = f"/analytics/realtime"
        params = None
        data = self._http.get(path, params=params)
        return AnalyticsRealtimeResponse.model_validate(data)

    def analytics_usage(
        self,
        *,
        month: str | None = None,
        project_id: str | None = None,
    ) -> UsageResponse:
        """Token and session usage analytics"""
        path = f"/analytics/usage"
        params: dict[str, Any] = {}
        if month is not None:
            params["month"] = month
        if project_id is not None:
            params["project_id"] = project_id
        data = self._http.get(path, params=params)
        return UsageResponse.model_validate(data)


class AsyncAnalytics(_AnalyticsBase):
    async def analytics_cost(
        self,
        *,
        start: str | None = None,
        end: str | None = None,
        group_by: str | None = None,
        project_id: str | None = None,
    ) -> CostResponse:
        """Cost analytics with billing-aware pricing"""
        path = f"/analytics/cost"
        params: dict[str, Any] = {}
        if start is not None:
            params["start"] = start
        if end is not None:
            params["end"] = end
        if group_by is not None:
            params["group_by"] = group_by
        if project_id is not None:
            params["project_id"] = project_id
        data = await self._http.get(path, params=params)
        return CostResponse.model_validate(data)

    async def analytics_cost_breakdown(
        self,
        *,
        month: str | None = None,
        start: str | None = None,
        end: str | None = None,
        project_id: str | None = None,
    ) -> CostBreakdownResponse:
        """Cost breakdown by operation / model / agent"""
        path = f"/analytics/cost/breakdown"
        params: dict[str, Any] = {}
        if month is not None:
            params["month"] = month
        if start is not None:
            params["start"] = start
        if end is not None:
            params["end"] = end
        if project_id is not None:
            params["project_id"] = project_id
        data = await self._http.get(path, params=params)
        return CostBreakdownResponse.model_validate(data)

    async def analytics_overview(
        self,
    ) -> AnalyticsOverview:
        """Dashboard analytics overview"""
        path = f"/analytics/overview"
        params = None
        data = await self._http.get(path, params=params)
        return AnalyticsOverview.model_validate(data)

    async def analytics_realtime(
        self,
    ) -> AnalyticsRealtimeResponse:
        """Dashboard analytics realtime"""
        path = f"/analytics/realtime"
        params = None
        data = await self._http.get(path, params=params)
        return AnalyticsRealtimeResponse.model_validate(data)

    async def analytics_usage(
        self,
        *,
        month: str | None = None,
        project_id: str | None = None,
    ) -> UsageResponse:
        """Token and session usage analytics"""
        path = f"/analytics/usage"
        params: dict[str, Any] = {}
        if month is not None:
            params["month"] = month
        if project_id is not None:
            params["project_id"] = project_id
        data = await self._http.get(path, params=params)
        return UsageResponse.model_validate(data)
