# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the BuiltInAgents tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    ChatMsgInputBody,
    GetBuiltinAgentSessionResponse,
    InvokeInputBody,
    ListBuiltinAgentSessionsResponse,
    ListBuiltinAgentsResponse,
    SessionBody,
    StartChatInputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _BuiltInAgentsBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class BuiltInAgents(_BuiltInAgentsBase):
    def list_builtin_agents(
        self,
    ) -> ListBuiltinAgentsResponse:
        """List Sonzai built-in backend agents"""
        path = f"/api/v1/builtin-agents"
        params = None
        data = self._http.get(path, params=params)
        return ListBuiltinAgentsResponse.model_validate(data)

    def list_builtin_agent_sessions(
        self,
        *,
        limit: int | None = 50,
    ) -> ListBuiltinAgentSessionsResponse:
        """List built-in agent chat sessions"""
        path = f"/api/v1/builtin-agents/sessions"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return ListBuiltinAgentSessionsResponse.model_validate(data)

    def start_builtin_agent_session(
        self,
        *,
        agent: str,
        title: str | None = None,
    ) -> SessionBody:
        """Start a chat session with a built-in agent"""
        path = f"/api/v1/builtin-agents/sessions"
        params = None
        _raw: dict[str, Any] = {}
        if agent is not None:
            _raw["agent"] = agent
        if title is not None:
            _raw["title"] = title
        body = encode_body(StartChatInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return SessionBody.model_validate(data)

    def get_builtin_agent_session(
        self,
        id: str,
    ) -> GetBuiltinAgentSessionResponse:
        """Get a built-in agent session (status, billed usage, cost)"""
        path = f"/api/v1/builtin-agents/sessions/{quote(id, safe='')}"
        params = None
        data = self._http.get(path, params=params)
        return GetBuiltinAgentSessionResponse.model_validate(data)

    def send_builtin_agent_message(
        self,
        id: str,
        *,
        stream: bool | None = None,
        text: str,
    ) -> Any:
        """Send a chat message to a built-in agent session"""
        path = f"/api/v1/builtin-agents/sessions/{quote(id, safe='')}/messages"
        params: dict[str, Any] = {}
        if stream is not None:
            params["stream"] = stream
        _raw: dict[str, Any] = {}
        if text is not None:
            _raw["text"] = text
        body = encode_body(ChatMsgInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return data

    def invoke_builtin_agent(
        self,
        slug: str,
        *,
        stream: bool | None = None,
        input: dict[str, Any],
        title: str | None = None,
    ) -> Any:
        """Run a built-in agent task"""
        path = f"/api/v1/builtin-agents/{quote(slug, safe='')}/invoke"
        params: dict[str, Any] = {}
        if stream is not None:
            params["stream"] = stream
        _raw: dict[str, Any] = {}
        if input is not None:
            _raw["input"] = input
        if title is not None:
            _raw["title"] = title
        body = encode_body(InvokeInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return data


class AsyncBuiltInAgents(_BuiltInAgentsBase):
    async def list_builtin_agents(
        self,
    ) -> ListBuiltinAgentsResponse:
        """List Sonzai built-in backend agents"""
        path = f"/api/v1/builtin-agents"
        params = None
        data = await self._http.get(path, params=params)
        return ListBuiltinAgentsResponse.model_validate(data)

    async def list_builtin_agent_sessions(
        self,
        *,
        limit: int | None = 50,
    ) -> ListBuiltinAgentSessionsResponse:
        """List built-in agent chat sessions"""
        path = f"/api/v1/builtin-agents/sessions"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return ListBuiltinAgentSessionsResponse.model_validate(data)

    async def start_builtin_agent_session(
        self,
        *,
        agent: str,
        title: str | None = None,
    ) -> SessionBody:
        """Start a chat session with a built-in agent"""
        path = f"/api/v1/builtin-agents/sessions"
        params = None
        _raw: dict[str, Any] = {}
        if agent is not None:
            _raw["agent"] = agent
        if title is not None:
            _raw["title"] = title
        body = encode_body(StartChatInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return SessionBody.model_validate(data)

    async def get_builtin_agent_session(
        self,
        id: str,
    ) -> GetBuiltinAgentSessionResponse:
        """Get a built-in agent session (status, billed usage, cost)"""
        path = f"/api/v1/builtin-agents/sessions/{quote(id, safe='')}"
        params = None
        data = await self._http.get(path, params=params)
        return GetBuiltinAgentSessionResponse.model_validate(data)

    async def send_builtin_agent_message(
        self,
        id: str,
        *,
        stream: bool | None = None,
        text: str,
    ) -> Any:
        """Send a chat message to a built-in agent session"""
        path = f"/api/v1/builtin-agents/sessions/{quote(id, safe='')}/messages"
        params: dict[str, Any] = {}
        if stream is not None:
            params["stream"] = stream
        _raw: dict[str, Any] = {}
        if text is not None:
            _raw["text"] = text
        body = encode_body(ChatMsgInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return data

    async def invoke_builtin_agent(
        self,
        slug: str,
        *,
        stream: bool | None = None,
        input: dict[str, Any],
        title: str | None = None,
    ) -> Any:
        """Run a built-in agent task"""
        path = f"/api/v1/builtin-agents/{quote(slug, safe='')}/invoke"
        params: dict[str, Any] = {}
        if stream is not None:
            params["stream"] = stream
        _raw: dict[str, Any] = {}
        if input is not None:
            _raw["input"] = input
        if title is not None:
            _raw["title"] = title
        body = encode_body(InvokeInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return data
