# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the ChannelConnections tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote

from sonzai._generated.models import (
    ChannelConnectionDTO,
    ChannelConnectionsOutputBody,
    CreateChannelConnectionInputBody,
    PatchChannelConnectionInputBody,
    TestChannelConnectionInputBody,
)
from sonzai._request_helpers import encode_body


class _ChannelConnectionsBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class ChannelConnections(_ChannelConnectionsBase):
    def list_channel_connections(
        self,
        project_id: str,
    ) -> ChannelConnectionsOutputBody:
        """List channel connections"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/channel-connections"
        params = None
        data = self._http.get(path, params=params)
        return ChannelConnectionsOutputBody.model_validate(data)

    def create_channel_connection(
        self,
        project_id: str,
        *,
        access_token: str | None = None,
        app_id: str | None = None,
        app_secret: str | None = None,
        channel_type: str,
        code: str | None = None,
        default_agent_id: str | None = None,
        display_name: str | None = None,
        ig_account_id: str | None = None,
        page_id: str | None = None,
        phone_number_id: str | None = None,
        provider_mode: str | None = None,
        templates: str | None = None,
        test_message: str | None = None,
        test_to: str | None = None,
        verify_token: str | None = None,
        waba_id: str | None = None,
    ) -> ChannelConnectionDTO:
        """Create channel connection"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/channel-connections"
        params = None
        _raw: dict[str, Any] = {}
        if access_token is not None:
            _raw["access_token"] = access_token
        if app_id is not None:
            _raw["app_id"] = app_id
        if app_secret is not None:
            _raw["app_secret"] = app_secret
        if channel_type is not None:
            _raw["channel_type"] = channel_type
        if code is not None:
            _raw["code"] = code
        if default_agent_id is not None:
            _raw["default_agent_id"] = default_agent_id
        if display_name is not None:
            _raw["display_name"] = display_name
        if ig_account_id is not None:
            _raw["ig_account_id"] = ig_account_id
        if page_id is not None:
            _raw["page_id"] = page_id
        if phone_number_id is not None:
            _raw["phone_number_id"] = phone_number_id
        if provider_mode is not None:
            _raw["provider_mode"] = provider_mode
        if templates is not None:
            _raw["templates"] = templates
        if test_message is not None:
            _raw["test_message"] = test_message
        if test_to is not None:
            _raw["test_to"] = test_to
        if verify_token is not None:
            _raw["verify_token"] = verify_token
        if waba_id is not None:
            _raw["waba_id"] = waba_id
        body = encode_body(CreateChannelConnectionInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return ChannelConnectionDTO.model_validate(data)

    def delete_channel_connection(
        self,
        project_id: str,
        id: str,
    ) -> Any:
        """Delete channel connection"""
        path = (
            f"/api/v1/projects/{quote(project_id, safe='')}/channel-connections/"
            f"{quote(id, safe='')}"
        )
        params = None
        data = self._http.delete(path, params=params)
        return data

    def get_channel_connection(
        self,
        project_id: str,
        id: str,
    ) -> ChannelConnectionDTO:
        """Get channel connection"""
        path = (
            f"/api/v1/projects/{quote(project_id, safe='')}/channel-connections/"
            f"{quote(id, safe='')}"
        )
        params = None
        data = self._http.get(path, params=params)
        return ChannelConnectionDTO.model_validate(data)

    def patch_channel_connection(
        self,
        project_id: str,
        id: str,
        *,
        default_agent_id: str | None = None,
        status: str | None = None,
        templates: str | None = None,
    ) -> ChannelConnectionDTO:
        """Update channel connection"""
        path = (
            f"/api/v1/projects/{quote(project_id, safe='')}/channel-connections/"
            f"{quote(id, safe='')}"
        )
        params = None
        _raw: dict[str, Any] = {}
        if default_agent_id is not None:
            _raw["default_agent_id"] = default_agent_id
        if status is not None:
            _raw["status"] = status
        if templates is not None:
            _raw["templates"] = templates
        body = encode_body(PatchChannelConnectionInputBody, _raw)
        data = self._http.patch(path, params=params, json_data=body)
        return ChannelConnectionDTO.model_validate(data)

    def test_channel_connection(
        self,
        project_id: str,
        id: str,
        *,
        message: str,
        to: str,
    ) -> ChannelConnectionDTO:
        """Test channel connection"""
        path = (
            f"/api/v1/projects/{quote(project_id, safe='')}/channel-connections/"
            f"{quote(id, safe='')}/test"
        )
        params = None
        _raw: dict[str, Any] = {}
        if message is not None:
            _raw["message"] = message
        if to is not None:
            _raw["to"] = to
        body = encode_body(TestChannelConnectionInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return ChannelConnectionDTO.model_validate(data)


class AsyncChannelConnections(_ChannelConnectionsBase):
    async def list_channel_connections(
        self,
        project_id: str,
    ) -> ChannelConnectionsOutputBody:
        """List channel connections"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/channel-connections"
        params = None
        data = await self._http.get(path, params=params)
        return ChannelConnectionsOutputBody.model_validate(data)

    async def create_channel_connection(
        self,
        project_id: str,
        *,
        access_token: str | None = None,
        app_id: str | None = None,
        app_secret: str | None = None,
        channel_type: str,
        code: str | None = None,
        default_agent_id: str | None = None,
        display_name: str | None = None,
        ig_account_id: str | None = None,
        page_id: str | None = None,
        phone_number_id: str | None = None,
        provider_mode: str | None = None,
        templates: str | None = None,
        test_message: str | None = None,
        test_to: str | None = None,
        verify_token: str | None = None,
        waba_id: str | None = None,
    ) -> ChannelConnectionDTO:
        """Create channel connection"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/channel-connections"
        params = None
        _raw: dict[str, Any] = {}
        if access_token is not None:
            _raw["access_token"] = access_token
        if app_id is not None:
            _raw["app_id"] = app_id
        if app_secret is not None:
            _raw["app_secret"] = app_secret
        if channel_type is not None:
            _raw["channel_type"] = channel_type
        if code is not None:
            _raw["code"] = code
        if default_agent_id is not None:
            _raw["default_agent_id"] = default_agent_id
        if display_name is not None:
            _raw["display_name"] = display_name
        if ig_account_id is not None:
            _raw["ig_account_id"] = ig_account_id
        if page_id is not None:
            _raw["page_id"] = page_id
        if phone_number_id is not None:
            _raw["phone_number_id"] = phone_number_id
        if provider_mode is not None:
            _raw["provider_mode"] = provider_mode
        if templates is not None:
            _raw["templates"] = templates
        if test_message is not None:
            _raw["test_message"] = test_message
        if test_to is not None:
            _raw["test_to"] = test_to
        if verify_token is not None:
            _raw["verify_token"] = verify_token
        if waba_id is not None:
            _raw["waba_id"] = waba_id
        body = encode_body(CreateChannelConnectionInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return ChannelConnectionDTO.model_validate(data)

    async def delete_channel_connection(
        self,
        project_id: str,
        id: str,
    ) -> Any:
        """Delete channel connection"""
        path = (
            f"/api/v1/projects/{quote(project_id, safe='')}/channel-connections/"
            f"{quote(id, safe='')}"
        )
        params = None
        data = await self._http.delete(path, params=params)
        return data

    async def get_channel_connection(
        self,
        project_id: str,
        id: str,
    ) -> ChannelConnectionDTO:
        """Get channel connection"""
        path = (
            f"/api/v1/projects/{quote(project_id, safe='')}/channel-connections/"
            f"{quote(id, safe='')}"
        )
        params = None
        data = await self._http.get(path, params=params)
        return ChannelConnectionDTO.model_validate(data)

    async def patch_channel_connection(
        self,
        project_id: str,
        id: str,
        *,
        default_agent_id: str | None = None,
        status: str | None = None,
        templates: str | None = None,
    ) -> ChannelConnectionDTO:
        """Update channel connection"""
        path = (
            f"/api/v1/projects/{quote(project_id, safe='')}/channel-connections/"
            f"{quote(id, safe='')}"
        )
        params = None
        _raw: dict[str, Any] = {}
        if default_agent_id is not None:
            _raw["default_agent_id"] = default_agent_id
        if status is not None:
            _raw["status"] = status
        if templates is not None:
            _raw["templates"] = templates
        body = encode_body(PatchChannelConnectionInputBody, _raw)
        data = await self._http.patch(path, params=params, json_data=body)
        return ChannelConnectionDTO.model_validate(data)

    async def test_channel_connection(
        self,
        project_id: str,
        id: str,
        *,
        message: str,
        to: str,
    ) -> ChannelConnectionDTO:
        """Test channel connection"""
        path = (
            f"/api/v1/projects/{quote(project_id, safe='')}/channel-connections/"
            f"{quote(id, safe='')}/test"
        )
        params = None
        _raw: dict[str, Any] = {}
        if message is not None:
            _raw["message"] = message
        if to is not None:
            _raw["to"] = to
        body = encode_body(TestChannelConnectionInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return ChannelConnectionDTO.model_validate(data)
