# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Chat tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    AsyncChatResultOutputBody,
    AsyncChatStartOutputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _ChatBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Chat(_ChatBase):
    def chat_with_agent(
        self,
        agent_id: str,
    ) -> Any:
        """Chat with agent (SSE streaming)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/chat"
        params = None
        data = self._http.post(path, params=params)
        return data

    def async_chat(
        self,
        agent_id: str,
    ) -> AsyncChatStartOutputBody:
        """Queue an asynchronous chat request"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/chat/async"
        params = None
        data = self._http.post(path, params=params)
        return AsyncChatStartOutputBody.model_validate(data)

    def async_chat_result(
        self,
        agent_id: str,
        processing_id: str,
    ) -> AsyncChatResultOutputBody:
        """Poll an async chat result"""
        path = (
            f"/api/v1/agents/{quote(agent_id, safe='')}/chat/result/{quote(processing_id, safe='')}"
        )
        params = None
        data = self._http.get(path, params=params)
        return AsyncChatResultOutputBody.model_validate(data)

    def playground_chat(
        self,
        agent_id: str,
    ) -> Any:
        """Playground chat with agent (SSE streaming)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/playground/chat"
        params = None
        data = self._http.post(path, params=params)
        return data


class AsyncChat(_ChatBase):
    async def chat_with_agent(
        self,
        agent_id: str,
    ) -> Any:
        """Chat with agent (SSE streaming)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/chat"
        params = None
        data = await self._http.post(path, params=params)
        return data

    async def async_chat(
        self,
        agent_id: str,
    ) -> AsyncChatStartOutputBody:
        """Queue an asynchronous chat request"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/chat/async"
        params = None
        data = await self._http.post(path, params=params)
        return AsyncChatStartOutputBody.model_validate(data)

    async def async_chat_result(
        self,
        agent_id: str,
        processing_id: str,
    ) -> AsyncChatResultOutputBody:
        """Poll an async chat result"""
        path = (
            f"/api/v1/agents/{quote(agent_id, safe='')}/chat/result/{quote(processing_id, safe='')}"
        )
        params = None
        data = await self._http.get(path, params=params)
        return AsyncChatResultOutputBody.model_validate(data)

    async def playground_chat(
        self,
        agent_id: str,
    ) -> Any:
        """Playground chat with agent (SSE streaming)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/playground/chat"
        params = None
        data = await self._http.post(path, params=params)
        return data
