# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Chat tag."""

from __future__ import annotations

from typing import Any

from sonzai._generated.models import (
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _ChatBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Chat(_ChatBase):
    def chat_with_agent(
        self,
        agent_id: str,
    ) -> Any:
        """Chat with agent (SSE streaming)"""
        path = f"/agents/{agentId}/chat"
        params = None
        data = self._http.post(path, params=params, body=None)
        return data
    def playground_chat(
        self,
        agent_id: str,
    ) -> Any:
        """Playground chat with agent (SSE streaming)"""
        path = f"/agents/{agentId}/playground/chat"
        params = None
        data = self._http.post(path, params=params, body=None)
        return data


class AsyncChat(_ChatBase):
    async def chat_with_agent(
        self,
        agent_id: str,
    ) -> Any:
        """Chat with agent (SSE streaming)"""
        path = f"/agents/{agentId}/chat"
        params = None
        data = await self._http.post(path, params=params, body=None)
        return data
    async def playground_chat(
        self,
        agent_id: str,
    ) -> Any:
        """Playground chat with agent (SSE streaming)"""
        path = f"/agents/{agentId}/playground/chat"
        params = None
        data = await self._http.post(path, params=params, body=None)
        return data
