# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Composio tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    ComposioConnectCallbackInputBody,
    ComposioConnectCallbackOutputBody,
    InitiateComposioConnectInputBody,
    InitiateComposioConnectOutputBody,
    ListComposioAuditOutputBody,
    ListComposioAvailableActionsOutputBody,
    ListComposioConnectionsOutputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _ComposioBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Composio(_ComposioBase):
    def list_composio_audit(
        self,
        agent_id: str,
        *,
        from_: str | None = None,
        to: str | None = None,
        status: str | None = None,
        limit: int | None = None,
    ) -> ListComposioAuditOutputBody:
        """List Composio action audit entries for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/composio/audit"
        params: dict[str, Any] = {}
        if from_ is not None:
            params["from"] = from_
        if to is not None:
            params["to"] = to
        if status is not None:
            params["status"] = status
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return ListComposioAuditOutputBody.model_validate(data)

    def list_composio_available_actions(
        self,
        agent_id: str,
    ) -> ListComposioAvailableActionsOutputBody:
        """List Composio actions available to an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/composio/available_actions"
        params = None
        data = self._http.get(path, params=params)
        return ListComposioAvailableActionsOutputBody.model_validate(data)

    def list_composio_connections(
        self,
        agent_id: str,
    ) -> ListComposioConnectionsOutputBody:
        """List Composio connections for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/composio/connections"
        params = None
        data = self._http.get(path, params=params)
        return ListComposioConnectionsOutputBody.model_validate(data)

    def initiate_composio_connect(
        self,
        agent_id: str,
        *,
        app: str,
    ) -> InitiateComposioConnectOutputBody:
        """Initiate a Composio OAuth flow for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/composio/connections"
        params = None
        _raw: dict[str, Any] = {}
        if app is not None:
            _raw["app"] = app
        body = encode_body(InitiateComposioConnectInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return InitiateComposioConnectOutputBody.model_validate(data)

    def composio_connect_callback(
        self,
        agent_id: str,
        *,
        account_label: str | None = None,
        app: str,
        connected_account_id: str,
        connected_by_user_id: str | None = None,
    ) -> ComposioConnectCallbackOutputBody:
        """Finalize a Composio OAuth flow"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/composio/connections/callback"
        params = None
        _raw: dict[str, Any] = {}
        if account_label is not None:
            _raw["account_label"] = account_label
        if app is not None:
            _raw["app"] = app
        if connected_account_id is not None:
            _raw["connected_account_id"] = connected_account_id
        if connected_by_user_id is not None:
            _raw["connected_by_user_id"] = connected_by_user_id
        body = encode_body(ComposioConnectCallbackInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return ComposioConnectCallbackOutputBody.model_validate(data)

    def delete_composio_connection(
        self,
        agent_id: str,
        app: str,
    ) -> Any:
        """Disconnect a Composio app for an agent"""
        path = (
            f"/api/v1/agents/{quote(agent_id, safe='')}/composio/connections/{quote(app, safe='')}"
        )
        params = None
        data = self._http.delete(path, params=params)
        return data


class AsyncComposio(_ComposioBase):
    async def list_composio_audit(
        self,
        agent_id: str,
        *,
        from_: str | None = None,
        to: str | None = None,
        status: str | None = None,
        limit: int | None = None,
    ) -> ListComposioAuditOutputBody:
        """List Composio action audit entries for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/composio/audit"
        params: dict[str, Any] = {}
        if from_ is not None:
            params["from"] = from_
        if to is not None:
            params["to"] = to
        if status is not None:
            params["status"] = status
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return ListComposioAuditOutputBody.model_validate(data)

    async def list_composio_available_actions(
        self,
        agent_id: str,
    ) -> ListComposioAvailableActionsOutputBody:
        """List Composio actions available to an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/composio/available_actions"
        params = None
        data = await self._http.get(path, params=params)
        return ListComposioAvailableActionsOutputBody.model_validate(data)

    async def list_composio_connections(
        self,
        agent_id: str,
    ) -> ListComposioConnectionsOutputBody:
        """List Composio connections for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/composio/connections"
        params = None
        data = await self._http.get(path, params=params)
        return ListComposioConnectionsOutputBody.model_validate(data)

    async def initiate_composio_connect(
        self,
        agent_id: str,
        *,
        app: str,
    ) -> InitiateComposioConnectOutputBody:
        """Initiate a Composio OAuth flow for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/composio/connections"
        params = None
        _raw: dict[str, Any] = {}
        if app is not None:
            _raw["app"] = app
        body = encode_body(InitiateComposioConnectInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return InitiateComposioConnectOutputBody.model_validate(data)

    async def composio_connect_callback(
        self,
        agent_id: str,
        *,
        account_label: str | None = None,
        app: str,
        connected_account_id: str,
        connected_by_user_id: str | None = None,
    ) -> ComposioConnectCallbackOutputBody:
        """Finalize a Composio OAuth flow"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/composio/connections/callback"
        params = None
        _raw: dict[str, Any] = {}
        if account_label is not None:
            _raw["account_label"] = account_label
        if app is not None:
            _raw["app"] = app
        if connected_account_id is not None:
            _raw["connected_account_id"] = connected_account_id
        if connected_by_user_id is not None:
            _raw["connected_by_user_id"] = connected_by_user_id
        body = encode_body(ComposioConnectCallbackInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return ComposioConnectCallbackOutputBody.model_validate(data)

    async def delete_composio_connection(
        self,
        agent_id: str,
        app: str,
    ) -> Any:
        """Disconnect a Composio app for an agent"""
        path = (
            f"/api/v1/agents/{quote(agent_id, safe='')}/composio/connections/{quote(app, safe='')}"
        )
        params = None
        data = await self._http.delete(path, params=params)
        return data
