# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Conversations tag."""

from __future__ import annotations

from typing import Any, cast
from urllib.parse import quote

from sonzai._generated.models import (
    ConversationBody,
    ConversationDetailBody,
    OmnichannelConversationDTO,
    OmnichannelMessageDTO,
    PatchConversationInputBody,
    SendConversationMessageInputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _ConversationsBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Conversations(_ConversationsBase):
    def list_conversations(
        self,
        *,
        project_id: str | None = None,
        channel: str | None = None,
        agent_id: str | None = None,
        user_id: str | None = None,
        controller: str | None = None,
        status: str | None = None,
        q: str | None = None,
        search: str | None = None,
        agent: str | None = None,
        tier: str | None = None,
        limit: int = 100,
    ) -> Page[ConversationBody]:
        """List conversations"""
        path = "/api/v1/conversations"
        params: dict[str, Any] = {"limit": limit, "cursor": None}
        if project_id is not None:
            params["project_id"] = project_id
        if channel is not None:
            params["channel"] = channel
        if agent_id is not None:
            params["agent_id"] = agent_id
        if user_id is not None:
            params["user_id"] = user_id
        if controller is not None:
            params["controller"] = controller
        if status is not None:
            params["status"] = status
        if q is not None:
            params["q"] = q
        if search is not None:
            params["search"] = search
        if agent is not None:
            params["agent"] = agent
        if tier is not None:
            params["tier"] = tier
        return Page(
            fetcher=lambda p: self._http.get(path, params=p),
            params=params,
            item_key="conversations",
            item_parser=ConversationBody.model_validate,
            mode="cursor",
            total_key="total",
        )

    def stream_conversations(
        self,
        *,
        project_id: str | None = None,
    ) -> Any:
        """Stream conversation events"""
        path = "/api/v1/conversations/stream"
        params: dict[str, Any] = {}
        if project_id is not None:
            params["project_id"] = project_id
        data = self._http.get(path, params=params)
        return data

    def get_conversation(
        self,
        id: str,
    ) -> ConversationDetailBody:
        """Get conversation"""
        path = f"/api/v1/conversations/{quote(id, safe='')}"
        params = None
        data = self._http.get(path, params=params)
        return ConversationDetailBody.model_validate(data)

    def patch_conversation(
        self,
        id: str,
        *,
        agent_id: str | None = None,
        status: str | None = None,
    ) -> OmnichannelConversationDTO:
        """Update conversation"""
        path = f"/api/v1/conversations/{quote(id, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if agent_id is not None:
            _raw["agent_id"] = agent_id
        if status is not None:
            _raw["status"] = status
        body = encode_body(PatchConversationInputBody, _raw)
        data = self._http.patch(path, params=params, json_data=body)
        return OmnichannelConversationDTO.model_validate(data)

    def list_conversation_messages(
        self,
        id: str,
        *,
        limit: int = 100,
    ) -> Page[OmnichannelMessageDTO]:
        """List conversation messages"""
        path = f"/api/v1/conversations/{quote(id, safe='')}/messages"
        params: dict[str, Any] = {"limit": limit, "cursor": None}
        return Page(
            fetcher=lambda p: self._http.get(path, params=p),
            params=params,
            item_key="items",
            item_parser=OmnichannelMessageDTO.model_validate,
            mode="cursor",
        )

    def send_conversation_message(
        self,
        id: str,
        *,
        attachments: str | None = None,
        content: str,
    ) -> OmnichannelConversationDTO:
        """Send operator message"""
        path = f"/api/v1/conversations/{quote(id, safe='')}/messages"
        params = None
        _raw: dict[str, Any] = {}
        if attachments is not None:
            _raw["attachments"] = attachments
        if content is not None:
            _raw["content"] = content
        body = encode_body(SendConversationMessageInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return OmnichannelConversationDTO.model_validate(data)

    def mark_conversation_read(
        self,
        id: str,
    ) -> OmnichannelConversationDTO:
        """Mark conversation read"""
        path = f"/api/v1/conversations/{quote(id, safe='')}/read"
        params = None
        data = self._http.post(path, params=params)
        return OmnichannelConversationDTO.model_validate(data)

    def release_conversation_takeover(
        self,
        id: str,
    ) -> OmnichannelConversationDTO:
        """Release conversation takeover"""
        path = f"/api/v1/conversations/{quote(id, safe='')}/takeover"
        params = None
        data = self._http.delete(path, params=params)
        if isinstance(data, dict):
            return OmnichannelConversationDTO.model_validate(data)
        return OmnichannelConversationDTO.model_construct()

    def take_over_conversation(
        self,
        id: str,
        *,
        force: bool | None = None,
        operator_id: str | None = None,
    ) -> OmnichannelConversationDTO:
        """Take over conversation"""
        path = f"/api/v1/conversations/{quote(id, safe='')}/takeover"
        params: dict[str, Any] = {}
        if force is not None:
            params["force"] = force
        if operator_id is not None:
            params["operator_id"] = operator_id
        data = self._http.post(path, params=params)
        return OmnichannelConversationDTO.model_validate(data)


class AsyncConversations(_ConversationsBase):
    async def list_conversations(
        self,
        *,
        project_id: str | None = None,
        channel: str | None = None,
        agent_id: str | None = None,
        user_id: str | None = None,
        controller: str | None = None,
        status: str | None = None,
        q: str | None = None,
        search: str | None = None,
        agent: str | None = None,
        tier: str | None = None,
        limit: int = 100,
    ) -> AsyncPage[ConversationBody]:
        """List conversations"""
        path = "/api/v1/conversations"
        params: dict[str, Any] = {"limit": limit, "cursor": None}
        if project_id is not None:
            params["project_id"] = project_id
        if channel is not None:
            params["channel"] = channel
        if agent_id is not None:
            params["agent_id"] = agent_id
        if user_id is not None:
            params["user_id"] = user_id
        if controller is not None:
            params["controller"] = controller
        if status is not None:
            params["status"] = status
        if q is not None:
            params["q"] = q
        if search is not None:
            params["search"] = search
        if agent is not None:
            params["agent"] = agent
        if tier is not None:
            params["tier"] = tier

        async def fetcher(p: dict[str, Any]) -> dict[str, Any]:
            return cast(dict[str, Any], await self._http.get(path, params=p))

        return AsyncPage(
            fetcher=fetcher,
            params=params,
            item_key="conversations",
            item_parser=ConversationBody.model_validate,
            mode="cursor",
            total_key="total",
        )

    async def stream_conversations(
        self,
        *,
        project_id: str | None = None,
    ) -> Any:
        """Stream conversation events"""
        path = "/api/v1/conversations/stream"
        params: dict[str, Any] = {}
        if project_id is not None:
            params["project_id"] = project_id
        data = await self._http.get(path, params=params)
        return data

    async def get_conversation(
        self,
        id: str,
    ) -> ConversationDetailBody:
        """Get conversation"""
        path = f"/api/v1/conversations/{quote(id, safe='')}"
        params = None
        data = await self._http.get(path, params=params)
        return ConversationDetailBody.model_validate(data)

    async def patch_conversation(
        self,
        id: str,
        *,
        agent_id: str | None = None,
        status: str | None = None,
    ) -> OmnichannelConversationDTO:
        """Update conversation"""
        path = f"/api/v1/conversations/{quote(id, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if agent_id is not None:
            _raw["agent_id"] = agent_id
        if status is not None:
            _raw["status"] = status
        body = encode_body(PatchConversationInputBody, _raw)
        data = await self._http.patch(path, params=params, json_data=body)
        return OmnichannelConversationDTO.model_validate(data)

    async def list_conversation_messages(
        self,
        id: str,
        *,
        limit: int = 100,
    ) -> AsyncPage[OmnichannelMessageDTO]:
        """List conversation messages"""
        path = f"/api/v1/conversations/{quote(id, safe='')}/messages"
        params: dict[str, Any] = {"limit": limit, "cursor": None}

        async def fetcher(p: dict[str, Any]) -> dict[str, Any]:
            return cast(dict[str, Any], await self._http.get(path, params=p))

        return AsyncPage(
            fetcher=fetcher,
            params=params,
            item_key="items",
            item_parser=OmnichannelMessageDTO.model_validate,
            mode="cursor",
        )

    async def send_conversation_message(
        self,
        id: str,
        *,
        attachments: str | None = None,
        content: str,
    ) -> OmnichannelConversationDTO:
        """Send operator message"""
        path = f"/api/v1/conversations/{quote(id, safe='')}/messages"
        params = None
        _raw: dict[str, Any] = {}
        if attachments is not None:
            _raw["attachments"] = attachments
        if content is not None:
            _raw["content"] = content
        body = encode_body(SendConversationMessageInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return OmnichannelConversationDTO.model_validate(data)

    async def mark_conversation_read(
        self,
        id: str,
    ) -> OmnichannelConversationDTO:
        """Mark conversation read"""
        path = f"/api/v1/conversations/{quote(id, safe='')}/read"
        params = None
        data = await self._http.post(path, params=params)
        return OmnichannelConversationDTO.model_validate(data)

    async def release_conversation_takeover(
        self,
        id: str,
    ) -> OmnichannelConversationDTO:
        """Release conversation takeover"""
        path = f"/api/v1/conversations/{quote(id, safe='')}/takeover"
        params = None
        data = await self._http.delete(path, params=params)
        if isinstance(data, dict):
            return OmnichannelConversationDTO.model_validate(data)
        return OmnichannelConversationDTO.model_construct()

    async def take_over_conversation(
        self,
        id: str,
        *,
        force: bool | None = None,
        operator_id: str | None = None,
    ) -> OmnichannelConversationDTO:
        """Take over conversation"""
        path = f"/api/v1/conversations/{quote(id, safe='')}/takeover"
        params: dict[str, Any] = {}
        if force is not None:
            params["force"] = force
        if operator_id is not None:
            params["operator_id"] = operator_id
        data = await self._http.post(path, params=params)
        return OmnichannelConversationDTO.model_validate(data)
