# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the CustomLlm tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    CustomLLMConfigResponse,
    SetCustomLLMConfigInputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _CustomLlmBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class CustomLlm(_CustomLlmBase):
    def delete_custom_llm_config(
        self,
        project_id: str,
    ) -> Any:
        """Delete custom LLM config"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/custom-llm"
        params = None
        data = self._http.delete(path, params=params)
        return data
    def get_custom_llm_config(
        self,
        project_id: str,
    ) -> CustomLLMConfigResponse:
        """Get custom LLM config for a project"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/custom-llm"
        params = None
        data = self._http.get(path, params=params)
        return CustomLLMConfigResponse.model_validate(data)
    def set_custom_llm_config(
        self,
        project_id: str,
        *,
        api_key: str,
        display_name: str | None = None,
        endpoint: str,
        is_active: bool | None = None,
        model: str | None = None,
    ) -> CustomLLMConfigResponse:
        """Set custom LLM config for a project"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/custom-llm"
        params = None
        _raw: dict[str, Any] = {}
        if api_key is not None:
            _raw["api_key"] = api_key
        if display_name is not None:
            _raw["display_name"] = display_name
        if endpoint is not None:
            _raw["endpoint"] = endpoint
        if is_active is not None:
            _raw["is_active"] = is_active
        if model is not None:
            _raw["model"] = model
        body = encode_body(SetCustomLLMConfigInputBody, _raw)
        data = self._http.put(path, params=params, json_data=body)
        return CustomLLMConfigResponse.model_validate(data)


class AsyncCustomLlm(_CustomLlmBase):
    async def delete_custom_llm_config(
        self,
        project_id: str,
    ) -> Any:
        """Delete custom LLM config"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/custom-llm"
        params = None
        data = await self._http.delete(path, params=params)
        return data
    async def get_custom_llm_config(
        self,
        project_id: str,
    ) -> CustomLLMConfigResponse:
        """Get custom LLM config for a project"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/custom-llm"
        params = None
        data = await self._http.get(path, params=params)
        return CustomLLMConfigResponse.model_validate(data)
    async def set_custom_llm_config(
        self,
        project_id: str,
        *,
        api_key: str,
        display_name: str | None = None,
        endpoint: str,
        is_active: bool | None = None,
        model: str | None = None,
    ) -> CustomLLMConfigResponse:
        """Set custom LLM config for a project"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/custom-llm"
        params = None
        _raw: dict[str, Any] = {}
        if api_key is not None:
            _raw["api_key"] = api_key
        if display_name is not None:
            _raw["display_name"] = display_name
        if endpoint is not None:
            _raw["endpoint"] = endpoint
        if is_active is not None:
            _raw["is_active"] = is_active
        if model is not None:
            _raw["model"] = model
        body = encode_body(SetCustomLLMConfigInputBody, _raw)
        data = await self._http.put(path, params=params, json_data=body)
        return CustomLLMConfigResponse.model_validate(data)
