# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the CustomStates tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    CreateCustomStateInputBody,
    CustomState,
    ListCustomStatesOutputBody,
    UpdateCustomStateInputBody,
    UpsertCustomStateByKeyInputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _CustomStatesBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class CustomStates(_CustomStatesBase):
    def list_custom_states(
        self,
        agent_id: str,
        *,
        scope: str | None = None,
        user_id: str | None = None,
        instance_id: str | None = None,
        key: str | None = None,
    ) -> ListCustomStatesOutputBody:
        """List custom states"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states"
        params: dict[str, Any] = {}
        if scope is not None:
            params["scope"] = scope
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        if key is not None:
            params["key"] = key
        data = self._http.get(path, params=params)
        return ListCustomStatesOutputBody.model_validate(data)

    def create_custom_state(
        self,
        agent_id: str,
        *,
        content_type: str | None = None,
        instance_id: str | None = None,
        key: str,
        scope: str | None = None,
        user_id: str | None = None,
        value: str,
    ) -> CustomState:
        """Create a custom state"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states"
        params = None
        _raw: dict[str, Any] = {}
        if content_type is not None:
            _raw["content_type"] = content_type
        if instance_id is not None:
            _raw["instance_id"] = instance_id
        if key is not None:
            _raw["key"] = key
        if scope is not None:
            _raw["scope"] = scope
        if user_id is not None:
            _raw["user_id"] = user_id
        if value is not None:
            _raw["value"] = value
        body = encode_body(CreateCustomStateInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return CustomState.model_validate(data)

    def delete_custom_state_by_key(
        self,
        agent_id: str,
        *,
        key: str,
        scope: str | None = None,
        user_id: str | None = None,
        instance_id: str | None = None,
    ) -> Any:
        """Delete a custom state by key"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states/by-key"
        params: dict[str, Any] = {}
        if key is not None:
            params["key"] = key
        if scope is not None:
            params["scope"] = scope
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        data = self._http.delete(path, params=params)
        return data

    def get_custom_state_by_key(
        self,
        agent_id: str,
        *,
        key: str,
        scope: str | None = None,
        user_id: str | None = None,
        instance_id: str | None = None,
    ) -> CustomState:
        """Get a custom state by key"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states/by-key"
        params: dict[str, Any] = {}
        if key is not None:
            params["key"] = key
        if scope is not None:
            params["scope"] = scope
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        data = self._http.get(path, params=params)
        return CustomState.model_validate(data)

    def upsert_custom_state_by_key(
        self,
        agent_id: str,
        *,
        content_type: str | None = None,
        instance_id: str | None = None,
        key: str,
        scope: str | None = None,
        user_id: str | None = None,
        value: str,
    ) -> CustomState:
        """Upsert a custom state by key"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states/by-key"
        params = None
        _raw: dict[str, Any] = {}
        if content_type is not None:
            _raw["content_type"] = content_type
        if instance_id is not None:
            _raw["instance_id"] = instance_id
        if key is not None:
            _raw["key"] = key
        if scope is not None:
            _raw["scope"] = scope
        if user_id is not None:
            _raw["user_id"] = user_id
        if value is not None:
            _raw["value"] = value
        body = encode_body(UpsertCustomStateByKeyInputBody, _raw)
        data = self._http.put(path, params=params, json_data=body)
        return CustomState.model_validate(data)

    def delete_custom_state(
        self,
        agent_id: str,
        state_id: str,
    ) -> Any:
        """Delete a custom state"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states/{quote(state_id, safe='')}"
        params = None
        data = self._http.delete(path, params=params)
        return data

    def update_custom_state(
        self,
        agent_id: str,
        state_id: str,
        *,
        content_type: str | None = None,
        value: str,
    ) -> CustomState:
        """Update a custom state"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states/{quote(state_id, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if content_type is not None:
            _raw["content_type"] = content_type
        if value is not None:
            _raw["value"] = value
        body = encode_body(UpdateCustomStateInputBody, _raw)
        data = self._http.put(path, params=params, json_data=body)
        return CustomState.model_validate(data)


class AsyncCustomStates(_CustomStatesBase):
    async def list_custom_states(
        self,
        agent_id: str,
        *,
        scope: str | None = None,
        user_id: str | None = None,
        instance_id: str | None = None,
        key: str | None = None,
    ) -> ListCustomStatesOutputBody:
        """List custom states"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states"
        params: dict[str, Any] = {}
        if scope is not None:
            params["scope"] = scope
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        if key is not None:
            params["key"] = key
        data = await self._http.get(path, params=params)
        return ListCustomStatesOutputBody.model_validate(data)

    async def create_custom_state(
        self,
        agent_id: str,
        *,
        content_type: str | None = None,
        instance_id: str | None = None,
        key: str,
        scope: str | None = None,
        user_id: str | None = None,
        value: str,
    ) -> CustomState:
        """Create a custom state"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states"
        params = None
        _raw: dict[str, Any] = {}
        if content_type is not None:
            _raw["content_type"] = content_type
        if instance_id is not None:
            _raw["instance_id"] = instance_id
        if key is not None:
            _raw["key"] = key
        if scope is not None:
            _raw["scope"] = scope
        if user_id is not None:
            _raw["user_id"] = user_id
        if value is not None:
            _raw["value"] = value
        body = encode_body(CreateCustomStateInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return CustomState.model_validate(data)

    async def delete_custom_state_by_key(
        self,
        agent_id: str,
        *,
        key: str,
        scope: str | None = None,
        user_id: str | None = None,
        instance_id: str | None = None,
    ) -> Any:
        """Delete a custom state by key"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states/by-key"
        params: dict[str, Any] = {}
        if key is not None:
            params["key"] = key
        if scope is not None:
            params["scope"] = scope
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        data = await self._http.delete(path, params=params)
        return data

    async def get_custom_state_by_key(
        self,
        agent_id: str,
        *,
        key: str,
        scope: str | None = None,
        user_id: str | None = None,
        instance_id: str | None = None,
    ) -> CustomState:
        """Get a custom state by key"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states/by-key"
        params: dict[str, Any] = {}
        if key is not None:
            params["key"] = key
        if scope is not None:
            params["scope"] = scope
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        data = await self._http.get(path, params=params)
        return CustomState.model_validate(data)

    async def upsert_custom_state_by_key(
        self,
        agent_id: str,
        *,
        content_type: str | None = None,
        instance_id: str | None = None,
        key: str,
        scope: str | None = None,
        user_id: str | None = None,
        value: str,
    ) -> CustomState:
        """Upsert a custom state by key"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states/by-key"
        params = None
        _raw: dict[str, Any] = {}
        if content_type is not None:
            _raw["content_type"] = content_type
        if instance_id is not None:
            _raw["instance_id"] = instance_id
        if key is not None:
            _raw["key"] = key
        if scope is not None:
            _raw["scope"] = scope
        if user_id is not None:
            _raw["user_id"] = user_id
        if value is not None:
            _raw["value"] = value
        body = encode_body(UpsertCustomStateByKeyInputBody, _raw)
        data = await self._http.put(path, params=params, json_data=body)
        return CustomState.model_validate(data)

    async def delete_custom_state(
        self,
        agent_id: str,
        state_id: str,
    ) -> Any:
        """Delete a custom state"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states/{quote(state_id, safe='')}"
        params = None
        data = await self._http.delete(path, params=params)
        return data

    async def update_custom_state(
        self,
        agent_id: str,
        state_id: str,
        *,
        content_type: str | None = None,
        value: str,
    ) -> CustomState:
        """Update a custom state"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/custom-states/{quote(state_id, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if content_type is not None:
            _raw["content_type"] = content_type
        if value is not None:
            _raw["value"] = value
        body = encode_body(UpdateCustomStateInputBody, _raw)
        data = await self._http.put(path, params=params, json_data=body)
        return CustomState.model_validate(data)
