# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Dialogue tag."""

from __future__ import annotations

from typing import Any
from sonzai._generated.models import (
    AgentDialogueInputBody,
    AgentDialogueOutputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _DialogueBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Dialogue(_DialogueBase):
    def agent_dialogue(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> AgentDialogueOutputBody:
        """Multi-agent dialogue"""
        path = f"/agents/{agentId}/dialogue"
        params = None
        body = encode_body(AgentDialogueInputBody, body_fields)
        data = self._http.post(path, params=params, body=body)
        return AgentDialogueOutputBody.model_validate(data)


class AsyncDialogue(_DialogueBase):
    async def agent_dialogue(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> AgentDialogueOutputBody:
        """Multi-agent dialogue"""
        path = f"/agents/{agentId}/dialogue"
        params = None
        body = encode_body(AgentDialogueInputBody, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return AgentDialogueOutputBody.model_validate(data)
