# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Enrichment tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    EnrichPersonInputBody,
    EnrichPersonOutputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _EnrichmentBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Enrichment(_EnrichmentBase):
    def enrich_person(
        self,
        *,
        country: str | None = None,
        email: str | None = None,
        employer: str | None = None,
        linkedin_url: str | None = None,
        name: str | None = None,
        want: list[Any] | None = None,
    ) -> EnrichPersonOutputBody:
        """Enrich a person (cost-ordered vendor waterfall)"""
        path = f"/api/v1/enrichment/person"
        params = None
        _raw: dict[str, Any] = {}
        if country is not None:
            _raw["country"] = country
        if email is not None:
            _raw["email"] = email
        if employer is not None:
            _raw["employer"] = employer
        if linkedin_url is not None:
            _raw["linkedin_url"] = linkedin_url
        if name is not None:
            _raw["name"] = name
        if want is not None:
            _raw["want"] = want
        body = encode_body(EnrichPersonInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return EnrichPersonOutputBody.model_validate(data)


class AsyncEnrichment(_EnrichmentBase):
    async def enrich_person(
        self,
        *,
        country: str | None = None,
        email: str | None = None,
        employer: str | None = None,
        linkedin_url: str | None = None,
        name: str | None = None,
        want: list[Any] | None = None,
    ) -> EnrichPersonOutputBody:
        """Enrich a person (cost-ordered vendor waterfall)"""
        path = f"/api/v1/enrichment/person"
        params = None
        _raw: dict[str, Any] = {}
        if country is not None:
            _raw["country"] = country
        if email is not None:
            _raw["email"] = email
        if employer is not None:
            _raw["employer"] = employer
        if linkedin_url is not None:
            _raw["linkedin_url"] = linkedin_url
        if name is not None:
            _raw["name"] = name
        if want is not None:
            _raw["want"] = want
        body = encode_body(EnrichPersonInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return EnrichPersonOutputBody.model_validate(data)
