# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Goals tag."""

from __future__ import annotations

from typing import Any
from sonzai._generated.models import (
    BreakthroughsResponse,
    CreateGoalInputBody,
    Goal,
    GoalsResponse,
    UpdateGoalInputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _GoalsBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Goals(_GoalsBase):
    def list_breakthroughs(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
    ) -> BreakthroughsResponse:
        """List breakthroughs for an agent"""
        path = f"/api/v1/agents/{agent_id}/breakthroughs"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        data = self._http.get(path, params=params)
        return BreakthroughsResponse.model_validate(data)

    def list_goals(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
    ) -> GoalsResponse:
        """List goals for an agent"""
        path = f"/api/v1/agents/{agent_id}/goals"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        data = self._http.get(path, params=params)
        return GoalsResponse.model_validate(data)

    def create_goal(
        self,
        agent_id: str,
        *,
        description: str | None = None,
        priority: int | None = None,
        related_traits: list[Any] | None = None,
        title: str | None = None,
        type: str | None = None,
        user_id: str | None = None,
    ) -> Goal:
        """Create a goal for an agent"""
        path = f"/api/v1/agents/{agent_id}/goals"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if priority is not None:
            _raw["priority"] = priority
        if related_traits is not None:
            _raw["related_traits"] = related_traits
        if title is not None:
            _raw["title"] = title
        if type is not None:
            _raw["type"] = type
        if user_id is not None:
            _raw["user_id"] = user_id
        body = encode_body(CreateGoalInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return Goal.model_validate(data)

    def delete_goal(
        self,
        agent_id: str,
        goal_id: str,
        *,
        user_id: str | None = None,
    ) -> Any:
        """Delete (abandon) a goal"""
        path = f"/api/v1/agents/{agent_id}/goals/{goal_id}"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        data = self._http.delete(path, params=params)
        return data

    def update_goal(
        self,
        agent_id: str,
        goal_id: str,
        *,
        description: str | None = None,
        priority: int | None = None,
        related_traits: list[Any] | None = None,
        status: str | None = None,
        title: str | None = None,
        user_id: str | None = None,
    ) -> Goal:
        """Update a goal"""
        path = f"/api/v1/agents/{agent_id}/goals/{goal_id}"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if priority is not None:
            _raw["priority"] = priority
        if related_traits is not None:
            _raw["related_traits"] = related_traits
        if status is not None:
            _raw["status"] = status
        if title is not None:
            _raw["title"] = title
        if user_id is not None:
            _raw["user_id"] = user_id
        body = encode_body(UpdateGoalInputBody, _raw)
        data = self._http.put(path, params=params, json_data=body)
        return Goal.model_validate(data)


class AsyncGoals(_GoalsBase):
    async def list_breakthroughs(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
    ) -> BreakthroughsResponse:
        """List breakthroughs for an agent"""
        path = f"/api/v1/agents/{agent_id}/breakthroughs"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        data = await self._http.get(path, params=params)
        return BreakthroughsResponse.model_validate(data)

    async def list_goals(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
    ) -> GoalsResponse:
        """List goals for an agent"""
        path = f"/api/v1/agents/{agent_id}/goals"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        data = await self._http.get(path, params=params)
        return GoalsResponse.model_validate(data)

    async def create_goal(
        self,
        agent_id: str,
        *,
        description: str | None = None,
        priority: int | None = None,
        related_traits: list[Any] | None = None,
        title: str | None = None,
        type: str | None = None,
        user_id: str | None = None,
    ) -> Goal:
        """Create a goal for an agent"""
        path = f"/api/v1/agents/{agent_id}/goals"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if priority is not None:
            _raw["priority"] = priority
        if related_traits is not None:
            _raw["related_traits"] = related_traits
        if title is not None:
            _raw["title"] = title
        if type is not None:
            _raw["type"] = type
        if user_id is not None:
            _raw["user_id"] = user_id
        body = encode_body(CreateGoalInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return Goal.model_validate(data)

    async def delete_goal(
        self,
        agent_id: str,
        goal_id: str,
        *,
        user_id: str | None = None,
    ) -> Any:
        """Delete (abandon) a goal"""
        path = f"/api/v1/agents/{agent_id}/goals/{goal_id}"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        data = await self._http.delete(path, params=params)
        return data

    async def update_goal(
        self,
        agent_id: str,
        goal_id: str,
        *,
        description: str | None = None,
        priority: int | None = None,
        related_traits: list[Any] | None = None,
        status: str | None = None,
        title: str | None = None,
        user_id: str | None = None,
    ) -> Goal:
        """Update a goal"""
        path = f"/api/v1/agents/{agent_id}/goals/{goal_id}"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if priority is not None:
            _raw["priority"] = priority
        if related_traits is not None:
            _raw["related_traits"] = related_traits
        if status is not None:
            _raw["status"] = status
        if title is not None:
            _raw["title"] = title
        if user_id is not None:
            _raw["user_id"] = user_id
        body = encode_body(UpdateGoalInputBody, _raw)
        data = await self._http.put(path, params=params, json_data=body)
        return Goal.model_validate(data)
