# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Grounding tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    GroundingAvailabilityInputBody,
    GroundingAvailabilityOutputBody,
    GroundingQueryInputBody,
    QueryResponse,
    ResultItem,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _GroundingBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Grounding(_GroundingBase):
    def grounding_batch_availability(
        self,
        project_id: str,
        *,
        availability: str,
        item_ids: list[Any],
    ) -> GroundingAvailabilityOutputBody:
        """Batch-check live availability for a set of items"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/grounding/availability"
        params = None
        _raw: dict[str, Any] = {}
        if availability is not None:
            _raw["availability"] = availability
        if item_ids is not None:
            _raw["item_ids"] = item_ids
        body = encode_body(GroundingAvailabilityInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return GroundingAvailabilityOutputBody.model_validate(data)

    def grounding_item_detail(
        self,
        project_id: str,
        item_id: str,
        *,
        from_: str | None = None,
        to: str | None = None,
    ) -> ResultItem:
        """Get one item with live availability"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/grounding/items/{quote(item_id, safe='')}"
        params: dict[str, Any] = {}
        if from_ is not None:
            params["from"] = from_
        if to is not None:
            params["to"] = to
        data = self._http.get(path, params=params)
        return ResultItem.model_validate(data)

    def grounding_query(
        self,
        project_id: str,
        *,
        availability: str | None = None,
        filters: str | None = None,
        query: str | None = None,
        scope: str | None = None,
        top_k: int | None = None,
    ) -> QueryResponse:
        """Query live inventory: hybrid KB search + structured catalog filters + availability"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/grounding/query"
        params = None
        _raw: dict[str, Any] = {}
        if availability is not None:
            _raw["availability"] = availability
        if filters is not None:
            _raw["filters"] = filters
        if query is not None:
            _raw["query"] = query
        if scope is not None:
            _raw["scope"] = scope
        if top_k is not None:
            _raw["top_k"] = top_k
        body = encode_body(GroundingQueryInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return QueryResponse.model_validate(data)


class AsyncGrounding(_GroundingBase):
    async def grounding_batch_availability(
        self,
        project_id: str,
        *,
        availability: str,
        item_ids: list[Any],
    ) -> GroundingAvailabilityOutputBody:
        """Batch-check live availability for a set of items"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/grounding/availability"
        params = None
        _raw: dict[str, Any] = {}
        if availability is not None:
            _raw["availability"] = availability
        if item_ids is not None:
            _raw["item_ids"] = item_ids
        body = encode_body(GroundingAvailabilityInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return GroundingAvailabilityOutputBody.model_validate(data)

    async def grounding_item_detail(
        self,
        project_id: str,
        item_id: str,
        *,
        from_: str | None = None,
        to: str | None = None,
    ) -> ResultItem:
        """Get one item with live availability"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/grounding/items/{quote(item_id, safe='')}"
        params: dict[str, Any] = {}
        if from_ is not None:
            params["from"] = from_
        if to is not None:
            params["to"] = to
        data = await self._http.get(path, params=params)
        return ResultItem.model_validate(data)

    async def grounding_query(
        self,
        project_id: str,
        *,
        availability: str | None = None,
        filters: str | None = None,
        query: str | None = None,
        scope: str | None = None,
        top_k: int | None = None,
    ) -> QueryResponse:
        """Query live inventory: hybrid KB search + structured catalog filters + availability"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/grounding/query"
        params = None
        _raw: dict[str, Any] = {}
        if availability is not None:
            _raw["availability"] = availability
        if filters is not None:
            _raw["filters"] = filters
        if query is not None:
            _raw["query"] = query
        if scope is not None:
            _raw["scope"] = scope
        if top_k is not None:
            _raw["top_k"] = top_k
        body = encode_body(GroundingQueryInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return QueryResponse.model_validate(data)
