# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Instances tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    AgentInstance,
    CreateInstanceInputBody,
    DeleteInstanceOutputBody,
    ListInstancesOutputBody,
    ResetInstanceOutputBody,
    UpdateInstanceInputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _InstancesBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Instances(_InstancesBase):
    def list_instances(
        self,
        agent_id: str,
    ) -> ListInstancesOutputBody:
        """List agent instances"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/instances"
        params = None
        data = self._http.get(path, params=params)
        return ListInstancesOutputBody.model_validate(data)

    def create_instance(
        self,
        agent_id: str,
        *,
        description: str | None = None,
        name: str,
    ) -> AgentInstance:
        """Create an agent instance"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/instances"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if name is not None:
            _raw["name"] = name
        body = encode_body(CreateInstanceInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return AgentInstance.model_validate(data)

    def delete_instance(
        self,
        agent_id: str,
        instance_id: str,
    ) -> DeleteInstanceOutputBody:
        """Delete an instance"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/instances/{quote(instance_id, safe='')}"
        params = None
        data = self._http.delete(path, params=params)
        if isinstance(data, dict):
            return DeleteInstanceOutputBody.model_validate(data)
        return DeleteInstanceOutputBody()

    def get_instance(
        self,
        agent_id: str,
        instance_id: str,
    ) -> AgentInstance:
        """Get a single instance"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/instances/{quote(instance_id, safe='')}"
        params = None
        data = self._http.get(path, params=params)
        return AgentInstance.model_validate(data)

    def update_instance(
        self,
        agent_id: str,
        instance_id: str,
        *,
        description: str | None = None,
        name: str | None = None,
        status: str | None = None,
    ) -> AgentInstance:
        """Update an instance"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/instances/{quote(instance_id, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if name is not None:
            _raw["name"] = name
        if status is not None:
            _raw["status"] = status
        body = encode_body(UpdateInstanceInputBody, _raw)
        data = self._http.patch(path, params=params, json_data=body)
        return AgentInstance.model_validate(data)

    def reset_instance(
        self,
        agent_id: str,
        instance_id: str,
    ) -> ResetInstanceOutputBody:
        """Reset an instance"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/instances/{quote(instance_id, safe='')}/reset"
        params = None
        data = self._http.post(path, params=params)
        return ResetInstanceOutputBody.model_validate(data)


class AsyncInstances(_InstancesBase):
    async def list_instances(
        self,
        agent_id: str,
    ) -> ListInstancesOutputBody:
        """List agent instances"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/instances"
        params = None
        data = await self._http.get(path, params=params)
        return ListInstancesOutputBody.model_validate(data)

    async def create_instance(
        self,
        agent_id: str,
        *,
        description: str | None = None,
        name: str,
    ) -> AgentInstance:
        """Create an agent instance"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/instances"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if name is not None:
            _raw["name"] = name
        body = encode_body(CreateInstanceInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return AgentInstance.model_validate(data)

    async def delete_instance(
        self,
        agent_id: str,
        instance_id: str,
    ) -> DeleteInstanceOutputBody:
        """Delete an instance"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/instances/{quote(instance_id, safe='')}"
        params = None
        data = await self._http.delete(path, params=params)
        if isinstance(data, dict):
            return DeleteInstanceOutputBody.model_validate(data)
        return DeleteInstanceOutputBody()

    async def get_instance(
        self,
        agent_id: str,
        instance_id: str,
    ) -> AgentInstance:
        """Get a single instance"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/instances/{quote(instance_id, safe='')}"
        params = None
        data = await self._http.get(path, params=params)
        return AgentInstance.model_validate(data)

    async def update_instance(
        self,
        agent_id: str,
        instance_id: str,
        *,
        description: str | None = None,
        name: str | None = None,
        status: str | None = None,
    ) -> AgentInstance:
        """Update an instance"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/instances/{quote(instance_id, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if name is not None:
            _raw["name"] = name
        if status is not None:
            _raw["status"] = status
        body = encode_body(UpdateInstanceInputBody, _raw)
        data = await self._http.patch(path, params=params, json_data=body)
        return AgentInstance.model_validate(data)

    async def reset_instance(
        self,
        agent_id: str,
        instance_id: str,
    ) -> ResetInstanceOutputBody:
        """Reset an instance"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/instances/{quote(instance_id, safe='')}/reset"
        params = None
        data = await self._http.post(path, params=params)
        return ResetInstanceOutputBody.model_validate(data)
