# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Inventory tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    BatchInventoryRequest,
    BatchInventoryResponse,
    CreateInventoryItemHumaInputBody,
    DirectUpdateRequest,
    DirectUpdateResponse,
    GroupResult,
    InventoryReadResponse,
    InventoryWriteRequest,
    InventoryWriteResponse,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _InventoryBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Inventory(_InventoryBase):
    def query_inventory(
        self,
        agent_id: str,
        user_id: str,
        *,
        instance_id: str | None = None,
        mode: str | None = "list",
        item_type: str | None = None,
        query: str | None = None,
        project_id: str | None = None,
        aggregations: str | None = None,
        group_by: str | None = None,
        filters: str | None = None,
        sort_by: str | None = None,
        sort_order: str | None = "asc",
        limit: int = 100,
    ) -> Page[GroupResult]:
        """Query user inventory"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/inventory"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        if instance_id is not None:
            params["instance_id"] = instance_id
        if mode is not None:
            params["mode"] = mode
        if item_type is not None:
            params["item_type"] = item_type
        if query is not None:
            params["query"] = query
        if project_id is not None:
            params["project_id"] = project_id
        if aggregations is not None:
            params["aggregations"] = aggregations
        if group_by is not None:
            params["group_by"] = group_by
        if filters is not None:
            params["filters"] = filters
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order
        return Page(
            fetcher=lambda p: self._http.get(path, params=p),
            params=params,
            item_key="groups",
            item_parser=GroupResult.model_validate,
            mode="offset",
        )
    def update_inventory(
        self,
        agent_id: str,
        user_id: str,
        *,
        instance_id: str | None = None,
        action: str,
        description: str | None = None,
        item_type: str,
        kb_node_id: str | None = None,
        label: str | None = None,
        project_id: str | None = None,
        properties: dict[str, Any] | None = None,
    ) -> InventoryWriteResponse:
        """Add, update, or remove an inventory item"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/inventory"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        _raw: dict[str, Any] = {}
        if action is not None:
            _raw["action"] = action
        if description is not None:
            _raw["description"] = description
        if item_type is not None:
            _raw["item_type"] = item_type
        if kb_node_id is not None:
            _raw["kb_node_id"] = kb_node_id
        if label is not None:
            _raw["label"] = label
        if project_id is not None:
            _raw["project_id"] = project_id
        if properties is not None:
            _raw["properties"] = properties
        body = encode_body(InventoryWriteRequest, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return InventoryWriteResponse.model_validate(data)
    def batch_import_inventory(
        self,
        agent_id: str,
        user_id: str,
        *,
        instance_id: str | None = None,
        items: list[Any],
        project_id: str | None = None,
    ) -> BatchInventoryResponse:
        """Batch import inventory items"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/inventory/batch"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        _raw: dict[str, Any] = {}
        if items is not None:
            _raw["items"] = items
        if project_id is not None:
            _raw["project_id"] = project_id
        body = encode_body(BatchInventoryRequest, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return BatchInventoryResponse.model_validate(data)
    def create_inventory_item(
        self,
        agent_id: str,
        user_id: str,
        *,
        instance_id: str | None = None,
        description: str | None = None,
        item_type: str,
        kb_node_id: str | None = None,
        label: str | None = None,
        project_id: str | None = None,
        properties: dict[str, Any] | None = None,
    ) -> InventoryWriteResponse:
        """Create an inventory item (dedicated add endpoint)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/inventory/items"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if item_type is not None:
            _raw["item_type"] = item_type
        if kb_node_id is not None:
            _raw["kb_node_id"] = kb_node_id
        if label is not None:
            _raw["label"] = label
        if project_id is not None:
            _raw["project_id"] = project_id
        if properties is not None:
            _raw["properties"] = properties
        body = encode_body(CreateInventoryItemHumaInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return InventoryWriteResponse.model_validate(data)
    def direct_delete_inventory(
        self,
        agent_id: str,
        user_id: str,
        fact_id: str,
        *,
        instance_id: str | None = None,
    ) -> DirectUpdateResponse:
        """Delete a specific inventory fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/inventory/{quote(fact_id, safe='')}"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        data = self._http.delete(path, params=params)
        if isinstance(data, dict):
            return DirectUpdateResponse.model_validate(data)
        return DirectUpdateResponse()
    def direct_update_inventory(
        self,
        agent_id: str,
        user_id: str,
        fact_id: str,
        *,
        instance_id: str | None = None,
        properties: dict[str, Any],
    ) -> DirectUpdateResponse:
        """Update a specific inventory fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/inventory/{quote(fact_id, safe='')}"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        _raw: dict[str, Any] = {}
        if properties is not None:
            _raw["properties"] = properties
        body = encode_body(DirectUpdateRequest, _raw)
        data = self._http.put(path, params=params, json_data=body)
        return DirectUpdateResponse.model_validate(data)


class AsyncInventory(_InventoryBase):
    async def query_inventory(
        self,
        agent_id: str,
        user_id: str,
        *,
        instance_id: str | None = None,
        mode: str | None = "list",
        item_type: str | None = None,
        query: str | None = None,
        project_id: str | None = None,
        aggregations: str | None = None,
        group_by: str | None = None,
        filters: str | None = None,
        sort_by: str | None = None,
        sort_order: str | None = "asc",
        limit: int = 100,
    ) -> AsyncPage[GroupResult]:
        """Query user inventory"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/inventory"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        if instance_id is not None:
            params["instance_id"] = instance_id
        if mode is not None:
            params["mode"] = mode
        if item_type is not None:
            params["item_type"] = item_type
        if query is not None:
            params["query"] = query
        if project_id is not None:
            params["project_id"] = project_id
        if aggregations is not None:
            params["aggregations"] = aggregations
        if group_by is not None:
            params["group_by"] = group_by
        if filters is not None:
            params["filters"] = filters
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order

        async def fetcher(p: dict[str, Any]) -> dict[str, Any]:
            return await self._http.get(path, params=p)

        return AsyncPage(
            fetcher=fetcher,
            params=params,
            item_key="groups",
            item_parser=GroupResult.model_validate,
            mode="offset",
        )
    async def update_inventory(
        self,
        agent_id: str,
        user_id: str,
        *,
        instance_id: str | None = None,
        action: str,
        description: str | None = None,
        item_type: str,
        kb_node_id: str | None = None,
        label: str | None = None,
        project_id: str | None = None,
        properties: dict[str, Any] | None = None,
    ) -> InventoryWriteResponse:
        """Add, update, or remove an inventory item"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/inventory"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        _raw: dict[str, Any] = {}
        if action is not None:
            _raw["action"] = action
        if description is not None:
            _raw["description"] = description
        if item_type is not None:
            _raw["item_type"] = item_type
        if kb_node_id is not None:
            _raw["kb_node_id"] = kb_node_id
        if label is not None:
            _raw["label"] = label
        if project_id is not None:
            _raw["project_id"] = project_id
        if properties is not None:
            _raw["properties"] = properties
        body = encode_body(InventoryWriteRequest, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return InventoryWriteResponse.model_validate(data)
    async def batch_import_inventory(
        self,
        agent_id: str,
        user_id: str,
        *,
        instance_id: str | None = None,
        items: list[Any],
        project_id: str | None = None,
    ) -> BatchInventoryResponse:
        """Batch import inventory items"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/inventory/batch"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        _raw: dict[str, Any] = {}
        if items is not None:
            _raw["items"] = items
        if project_id is not None:
            _raw["project_id"] = project_id
        body = encode_body(BatchInventoryRequest, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return BatchInventoryResponse.model_validate(data)
    async def create_inventory_item(
        self,
        agent_id: str,
        user_id: str,
        *,
        instance_id: str | None = None,
        description: str | None = None,
        item_type: str,
        kb_node_id: str | None = None,
        label: str | None = None,
        project_id: str | None = None,
        properties: dict[str, Any] | None = None,
    ) -> InventoryWriteResponse:
        """Create an inventory item (dedicated add endpoint)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/inventory/items"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if item_type is not None:
            _raw["item_type"] = item_type
        if kb_node_id is not None:
            _raw["kb_node_id"] = kb_node_id
        if label is not None:
            _raw["label"] = label
        if project_id is not None:
            _raw["project_id"] = project_id
        if properties is not None:
            _raw["properties"] = properties
        body = encode_body(CreateInventoryItemHumaInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return InventoryWriteResponse.model_validate(data)
    async def direct_delete_inventory(
        self,
        agent_id: str,
        user_id: str,
        fact_id: str,
        *,
        instance_id: str | None = None,
    ) -> DirectUpdateResponse:
        """Delete a specific inventory fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/inventory/{quote(fact_id, safe='')}"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        data = await self._http.delete(path, params=params)
        if isinstance(data, dict):
            return DirectUpdateResponse.model_validate(data)
        return DirectUpdateResponse()
    async def direct_update_inventory(
        self,
        agent_id: str,
        user_id: str,
        fact_id: str,
        *,
        instance_id: str | None = None,
        properties: dict[str, Any],
    ) -> DirectUpdateResponse:
        """Update a specific inventory fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/inventory/{quote(fact_id, safe='')}"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        _raw: dict[str, Any] = {}
        if properties is not None:
            _raw["properties"] = properties
        body = encode_body(DirectUpdateRequest, _raw)
        data = await self._http.put(path, params=params, json_data=body)
        return DirectUpdateResponse.model_validate(data)
