# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Knowledge tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    KBAnalyticsRule,
    KbBulkUpdateInputBody,
    KbBulkUpdateOutputBody,
    KbCreateAnalyticsRuleInputBody,
    KbCreateOrgNodeInputBody,
    KbCreateSchemaInputBody,
    KBDocument,
    KBEntitySchema,
    KbGetConversionStatsOutputBody,
    KbGetNodeHistoryOutputBody,
    KbGetNodeOutputBody,
    KbGetRecommendationsOutputBody,
    KbGetStatsOutputBody,
    KbGetTrendRankingsOutputBody,
    KbGetTrendsOutputBody,
    KbInsertFactsInputBody,
    KbInsertFactsOutputBody,
    KbListAnalyticsRulesOutputBody,
    KbListDocumentsOutputBody,
    KbListNodesOutputBody,
    KbListOrgNodesOutputBody,
    KbListSchemasOutputBody,
    KBNode,
    KBNodeWithScope,
    KbPromoteNodeInputBody,
    KbRecordFeedbackInputBody,
    KbRecordFeedbackOutputBody,
    KbRunAnalyticsRuleOutputBody,
    KBSearchResponse,
    KbUpdateAnalyticsRuleInputBody,
    KbUpdateSchemaInputBody,
    KbUploadDocumentOutputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _KnowledgeBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Knowledge(_KnowledgeBase):
    def kb_get_conversion_stats(
        self,
        project_id: str,
        *,
        rule_id: str,
        segment: str | None = None,
    ) -> KbGetConversionStatsOutputBody:
        """Get conversion statistics"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/conversions"
        params: dict[str, Any] = {}
        if rule_id is not None:
            params["rule_id"] = rule_id
        if segment is not None:
            params["segment"] = segment
        data = self._http.get(path, params=params)
        return KbGetConversionStatsOutputBody.model_validate(data)
    def kb_record_feedback(
        self,
        project_id: str,
        *,
        action: str | None = None,
        converted: bool,
        rule_id: str,
        score_at_time: float,
        source_node_id: str,
        target_node_id: str,
    ) -> KbRecordFeedbackOutputBody:
        """Record recommendation feedback"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/feedback"
        params = None
        _raw: dict[str, Any] = {}
        if action is not None:
            _raw["action"] = action
        if converted is not None:
            _raw["converted"] = converted
        if rule_id is not None:
            _raw["rule_id"] = rule_id
        if score_at_time is not None:
            _raw["score_at_time"] = score_at_time
        if source_node_id is not None:
            _raw["source_node_id"] = source_node_id
        if target_node_id is not None:
            _raw["target_node_id"] = target_node_id
        body = encode_body(KbRecordFeedbackInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return KbRecordFeedbackOutputBody.model_validate(data)
    def kb_get_trend_rankings(
        self,
        project_id: str,
        *,
        rule_id: str,
        type: str,
        window: str,
        limit: int | None = 10,
    ) -> KbGetTrendRankingsOutputBody:
        """Get trend rankings"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rankings"
        params: dict[str, Any] = {}
        if rule_id is not None:
            params["rule_id"] = rule_id
        if type is not None:
            params["type"] = type
        if window is not None:
            params["window"] = window
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return KbGetTrendRankingsOutputBody.model_validate(data)
    def kb_get_recommendations(
        self,
        project_id: str,
        *,
        source_id: str,
        rule_id: str,
        limit: int | None = 10,
    ) -> KbGetRecommendationsOutputBody:
        """Get knowledge base recommendations"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/recommendations"
        params: dict[str, Any] = {}
        if source_id is not None:
            params["source_id"] = source_id
        if rule_id is not None:
            params["rule_id"] = rule_id
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return KbGetRecommendationsOutputBody.model_validate(data)
    def kb_list_analytics_rules(
        self,
        project_id: str,
    ) -> KbListAnalyticsRulesOutputBody:
        """List analytics rules"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rules"
        params = None
        data = self._http.get(path, params=params)
        return KbListAnalyticsRulesOutputBody.model_validate(data)
    def kb_create_analytics_rule(
        self,
        project_id: str,
        *,
        config: str,
        enabled: bool,
        name: str,
        rule_type: str,
        schedule: str | None = None,
    ) -> KBAnalyticsRule:
        """Create an analytics rule"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rules"
        params = None
        _raw: dict[str, Any] = {}
        if config is not None:
            _raw["config"] = config
        if enabled is not None:
            _raw["enabled"] = enabled
        if name is not None:
            _raw["name"] = name
        if rule_type is not None:
            _raw["rule_type"] = rule_type
        if schedule is not None:
            _raw["schedule"] = schedule
        body = encode_body(KbCreateAnalyticsRuleInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return KBAnalyticsRule.model_validate(data)
    def kb_delete_analytics_rule(
        self,
        project_id: str,
        rule_id: str,
    ) -> Any:
        """Delete an analytics rule"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rules/{quote(rule_id, safe='')}"
        params = None
        data = self._http.delete(path, params=params)
        return data
    def kb_get_analytics_rule(
        self,
        project_id: str,
        rule_id: str,
    ) -> KBAnalyticsRule:
        """Get an analytics rule"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rules/{quote(rule_id, safe='')}"
        params = None
        data = self._http.get(path, params=params)
        return KBAnalyticsRule.model_validate(data)
    def kb_update_analytics_rule(
        self,
        project_id: str,
        rule_id: str,
        *,
        config: str | None = None,
        enabled: bool,
        name: str | None = None,
        schedule: str | None = None,
    ) -> KBAnalyticsRule:
        """Update an analytics rule"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rules/{quote(rule_id, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if config is not None:
            _raw["config"] = config
        if enabled is not None:
            _raw["enabled"] = enabled
        if name is not None:
            _raw["name"] = name
        if schedule is not None:
            _raw["schedule"] = schedule
        body = encode_body(KbUpdateAnalyticsRuleInputBody, _raw)
        data = self._http.put(path, params=params, json_data=body)
        return KBAnalyticsRule.model_validate(data)
    def kb_run_analytics_rule(
        self,
        project_id: str,
        rule_id: str,
    ) -> KbRunAnalyticsRuleOutputBody:
        """Manually trigger an analytics rule"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rules/{quote(rule_id, safe='')}/run"
        params = None
        data = self._http.post(path, params=params)
        return KbRunAnalyticsRuleOutputBody.model_validate(data)
    def kb_get_trends(
        self,
        project_id: str,
        *,
        node_id: str,
    ) -> KbGetTrendsOutputBody:
        """Get knowledge base trends"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/trends"
        params: dict[str, Any] = {}
        if node_id is not None:
            params["node_id"] = node_id
        data = self._http.get(path, params=params)
        return KbGetTrendsOutputBody.model_validate(data)
    def kb_bulk_update_properties(
        self,
        project_id: str,
        *,
        source: str | None = None,
        updates: list[Any],
        upsert: bool | None = None,
    ) -> KbBulkUpdateOutputBody:
        """Bulk update node properties"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/bulk-update"
        params = None
        _raw: dict[str, Any] = {}
        if source is not None:
            _raw["source"] = source
        if updates is not None:
            _raw["updates"] = updates
        if upsert is not None:
            _raw["upsert"] = upsert
        body = encode_body(KbBulkUpdateInputBody, _raw)
        data = self._http.patch(path, params=params, json_data=body)
        return KbBulkUpdateOutputBody.model_validate(data)
    def kb_list_documents(
        self,
        project_id: str,
        *,
        limit: int | None = 50,
    ) -> KbListDocumentsOutputBody:
        """List knowledge base documents"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/documents"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return KbListDocumentsOutputBody.model_validate(data)
    def kb_upload_document(
        self,
        project_id: str,
    ) -> KbUploadDocumentOutputBody:
        """Upload a document for knowledge extraction"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/documents"
        params = None
        data = self._http.post(path, params=params)
        return KbUploadDocumentOutputBody.model_validate(data)
    def kb_delete_document(
        self,
        project_id: str,
        doc_id: str,
    ) -> Any:
        """Delete a document"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/documents/{quote(doc_id, safe='')}"
        params = None
        data = self._http.delete(path, params=params)
        return data
    def kb_get_document(
        self,
        project_id: str,
        doc_id: str,
    ) -> KBDocument:
        """Get a single document"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/documents/{quote(doc_id, safe='')}"
        params = None
        data = self._http.get(path, params=params)
        return KBDocument.model_validate(data)
    def kb_insert_facts(
        self,
        project_id: str,
        *,
        facts: list[Any],
        relationships: list[Any] | None = None,
        source: str | None = None,
    ) -> KbInsertFactsOutputBody:
        """Insert facts into the knowledge base"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/facts"
        params = None
        _raw: dict[str, Any] = {}
        if facts is not None:
            _raw["facts"] = facts
        if relationships is not None:
            _raw["relationships"] = relationships
        if source is not None:
            _raw["source"] = source
        body = encode_body(KbInsertFactsInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return KbInsertFactsOutputBody.model_validate(data)
    def kb_list_nodes(
        self,
        project_id: str,
        *,
        type: str | None = None,
        sort_by: str | None = None,
        sort_order: str | None = None,
        limit: int = 100,
    ) -> Page[KBNode]:
        """List knowledge base nodes"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/nodes"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        if type is not None:
            params["type"] = type
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order
        return Page(
            fetcher=lambda p: self._http.get(path, params=p),
            params=params,
            item_key="nodes",
            item_parser=KBNode.model_validate,
            mode="offset",
            total_key="total",
        )
    def kb_delete_node(
        self,
        project_id: str,
        node_id: str,
    ) -> Any:
        """Delete a knowledge base node"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/nodes/{quote(node_id, safe='')}"
        params = None
        data = self._http.delete(path, params=params)
        return data
    def kb_get_node(
        self,
        project_id: str,
        node_id: str,
        *,
        history: str | None = None,
    ) -> KbGetNodeOutputBody:
        """Get a knowledge base node with edges"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/nodes/{quote(node_id, safe='')}"
        params: dict[str, Any] = {}
        if history is not None:
            params["history"] = history
        data = self._http.get(path, params=params)
        return KbGetNodeOutputBody.model_validate(data)
    def kb_get_node_history(
        self,
        project_id: str,
        node_id: str,
        *,
        limit: int | None = 50,
    ) -> KbGetNodeHistoryOutputBody:
        """Get node version history"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/nodes/{quote(node_id, safe='')}/history"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return KbGetNodeHistoryOutputBody.model_validate(data)
    def kb_promote_node_to_org(
        self,
        project_id: str,
        node_id: str,
        *,
        tenant_id: str,
    ) -> KBNodeWithScope:
        """Promote a project-scoped node to the organization-global scope"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/nodes/{quote(node_id, safe='')}/promote-to-org"
        params = None
        _raw: dict[str, Any] = {}
        if tenant_id is not None:
            _raw["tenant_id"] = tenant_id
        body = encode_body(KbPromoteNodeInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return KBNodeWithScope.model_validate(data)
    def kb_list_schemas(
        self,
        project_id: str,
    ) -> KbListSchemasOutputBody:
        """List entity schemas"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/schemas"
        params = None
        data = self._http.get(path, params=params)
        return KbListSchemasOutputBody.model_validate(data)
    def kb_create_schema(
        self,
        project_id: str,
        *,
        description: str | None = None,
        display_name: str | None = None,
        entity_type: str,
        fields: list[Any],
        similarity_config: str | None = None,
    ) -> KBEntitySchema:
        """Create an entity schema"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/schemas"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if display_name is not None:
            _raw["display_name"] = display_name
        if entity_type is not None:
            _raw["entity_type"] = entity_type
        if fields is not None:
            _raw["fields"] = fields
        if similarity_config is not None:
            _raw["similarity_config"] = similarity_config
        body = encode_body(KbCreateSchemaInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return KBEntitySchema.model_validate(data)
    def kb_delete_schema(
        self,
        project_id: str,
        schema_id: str,
    ) -> Any:
        """Delete an entity schema"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/schemas/{quote(schema_id, safe='')}"
        params = None
        data = self._http.delete(path, params=params)
        return data
    def kb_update_schema(
        self,
        project_id: str,
        schema_id: str,
        *,
        description: str | None = None,
        display_name: str | None = None,
        entity_type: str | None = None,
        fields: list[Any] | None = None,
        similarity_config: str | None = None,
    ) -> KBEntitySchema:
        """Update an entity schema"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/schemas/{quote(schema_id, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if display_name is not None:
            _raw["display_name"] = display_name
        if entity_type is not None:
            _raw["entity_type"] = entity_type
        if fields is not None:
            _raw["fields"] = fields
        if similarity_config is not None:
            _raw["similarity_config"] = similarity_config
        body = encode_body(KbUpdateSchemaInputBody, _raw)
        data = self._http.put(path, params=params, json_data=body)
        return KBEntitySchema.model_validate(data)
    def kb_search(
        self,
        project_id: str,
        *,
        q: str,
        limit: int | None = 20,
        depth: int | None = 1,
        history: str | None = None,
        type: str | None = None,
        mode: str | None = None,
        filters: str | None = None,
    ) -> KBSearchResponse:
        """Search the knowledge base"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/search"
        params: dict[str, Any] = {}
        if q is not None:
            params["q"] = q
        if limit is not None:
            params["limit"] = limit
        if depth is not None:
            params["depth"] = depth
        if history is not None:
            params["history"] = history
        if type is not None:
            params["type"] = type
        if mode is not None:
            params["mode"] = mode
        if filters is not None:
            params["filters"] = filters
        data = self._http.get(path, params=params)
        return KBSearchResponse.model_validate(data)
    def kb_get_stats(
        self,
        project_id: str,
    ) -> KbGetStatsOutputBody:
        """Get knowledge base statistics"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/stats"
        params = None
        data = self._http.get(path, params=params)
        return KbGetStatsOutputBody.model_validate(data)
    def kb_list_org_nodes(
        self,
        tenant_id: str,
        *,
        limit: int | None = 200,
    ) -> KbListOrgNodesOutputBody:
        """List nodes in the organization-global KB scope"""
        path = f"/api/v1/tenants/{quote(tenant_id, safe='')}/knowledge/org-nodes"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return KbListOrgNodesOutputBody.model_validate(data)
    def kb_create_org_node(
        self,
        tenant_id: str,
        *,
        confidence: float | None = None,
        label: str,
        node_type: str,
        properties: dict[str, Any] | None = None,
    ) -> KBNode:
        """Create a knowledge-base node in the organization-global scope"""
        path = f"/api/v1/tenants/{quote(tenant_id, safe='')}/knowledge/org-nodes"
        params = None
        _raw: dict[str, Any] = {}
        if confidence is not None:
            _raw["confidence"] = confidence
        if label is not None:
            _raw["label"] = label
        if node_type is not None:
            _raw["node_type"] = node_type
        if properties is not None:
            _raw["properties"] = properties
        body = encode_body(KbCreateOrgNodeInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return KBNode.model_validate(data)


class AsyncKnowledge(_KnowledgeBase):
    async def kb_get_conversion_stats(
        self,
        project_id: str,
        *,
        rule_id: str,
        segment: str | None = None,
    ) -> KbGetConversionStatsOutputBody:
        """Get conversion statistics"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/conversions"
        params: dict[str, Any] = {}
        if rule_id is not None:
            params["rule_id"] = rule_id
        if segment is not None:
            params["segment"] = segment
        data = await self._http.get(path, params=params)
        return KbGetConversionStatsOutputBody.model_validate(data)
    async def kb_record_feedback(
        self,
        project_id: str,
        *,
        action: str | None = None,
        converted: bool,
        rule_id: str,
        score_at_time: float,
        source_node_id: str,
        target_node_id: str,
    ) -> KbRecordFeedbackOutputBody:
        """Record recommendation feedback"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/feedback"
        params = None
        _raw: dict[str, Any] = {}
        if action is not None:
            _raw["action"] = action
        if converted is not None:
            _raw["converted"] = converted
        if rule_id is not None:
            _raw["rule_id"] = rule_id
        if score_at_time is not None:
            _raw["score_at_time"] = score_at_time
        if source_node_id is not None:
            _raw["source_node_id"] = source_node_id
        if target_node_id is not None:
            _raw["target_node_id"] = target_node_id
        body = encode_body(KbRecordFeedbackInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return KbRecordFeedbackOutputBody.model_validate(data)
    async def kb_get_trend_rankings(
        self,
        project_id: str,
        *,
        rule_id: str,
        type: str,
        window: str,
        limit: int | None = 10,
    ) -> KbGetTrendRankingsOutputBody:
        """Get trend rankings"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rankings"
        params: dict[str, Any] = {}
        if rule_id is not None:
            params["rule_id"] = rule_id
        if type is not None:
            params["type"] = type
        if window is not None:
            params["window"] = window
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return KbGetTrendRankingsOutputBody.model_validate(data)
    async def kb_get_recommendations(
        self,
        project_id: str,
        *,
        source_id: str,
        rule_id: str,
        limit: int | None = 10,
    ) -> KbGetRecommendationsOutputBody:
        """Get knowledge base recommendations"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/recommendations"
        params: dict[str, Any] = {}
        if source_id is not None:
            params["source_id"] = source_id
        if rule_id is not None:
            params["rule_id"] = rule_id
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return KbGetRecommendationsOutputBody.model_validate(data)
    async def kb_list_analytics_rules(
        self,
        project_id: str,
    ) -> KbListAnalyticsRulesOutputBody:
        """List analytics rules"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rules"
        params = None
        data = await self._http.get(path, params=params)
        return KbListAnalyticsRulesOutputBody.model_validate(data)
    async def kb_create_analytics_rule(
        self,
        project_id: str,
        *,
        config: str,
        enabled: bool,
        name: str,
        rule_type: str,
        schedule: str | None = None,
    ) -> KBAnalyticsRule:
        """Create an analytics rule"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rules"
        params = None
        _raw: dict[str, Any] = {}
        if config is not None:
            _raw["config"] = config
        if enabled is not None:
            _raw["enabled"] = enabled
        if name is not None:
            _raw["name"] = name
        if rule_type is not None:
            _raw["rule_type"] = rule_type
        if schedule is not None:
            _raw["schedule"] = schedule
        body = encode_body(KbCreateAnalyticsRuleInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return KBAnalyticsRule.model_validate(data)
    async def kb_delete_analytics_rule(
        self,
        project_id: str,
        rule_id: str,
    ) -> Any:
        """Delete an analytics rule"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rules/{quote(rule_id, safe='')}"
        params = None
        data = await self._http.delete(path, params=params)
        return data
    async def kb_get_analytics_rule(
        self,
        project_id: str,
        rule_id: str,
    ) -> KBAnalyticsRule:
        """Get an analytics rule"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rules/{quote(rule_id, safe='')}"
        params = None
        data = await self._http.get(path, params=params)
        return KBAnalyticsRule.model_validate(data)
    async def kb_update_analytics_rule(
        self,
        project_id: str,
        rule_id: str,
        *,
        config: str | None = None,
        enabled: bool,
        name: str | None = None,
        schedule: str | None = None,
    ) -> KBAnalyticsRule:
        """Update an analytics rule"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rules/{quote(rule_id, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if config is not None:
            _raw["config"] = config
        if enabled is not None:
            _raw["enabled"] = enabled
        if name is not None:
            _raw["name"] = name
        if schedule is not None:
            _raw["schedule"] = schedule
        body = encode_body(KbUpdateAnalyticsRuleInputBody, _raw)
        data = await self._http.put(path, params=params, json_data=body)
        return KBAnalyticsRule.model_validate(data)
    async def kb_run_analytics_rule(
        self,
        project_id: str,
        rule_id: str,
    ) -> KbRunAnalyticsRuleOutputBody:
        """Manually trigger an analytics rule"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/rules/{quote(rule_id, safe='')}/run"
        params = None
        data = await self._http.post(path, params=params)
        return KbRunAnalyticsRuleOutputBody.model_validate(data)
    async def kb_get_trends(
        self,
        project_id: str,
        *,
        node_id: str,
    ) -> KbGetTrendsOutputBody:
        """Get knowledge base trends"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/analytics/trends"
        params: dict[str, Any] = {}
        if node_id is not None:
            params["node_id"] = node_id
        data = await self._http.get(path, params=params)
        return KbGetTrendsOutputBody.model_validate(data)
    async def kb_bulk_update_properties(
        self,
        project_id: str,
        *,
        source: str | None = None,
        updates: list[Any],
        upsert: bool | None = None,
    ) -> KbBulkUpdateOutputBody:
        """Bulk update node properties"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/bulk-update"
        params = None
        _raw: dict[str, Any] = {}
        if source is not None:
            _raw["source"] = source
        if updates is not None:
            _raw["updates"] = updates
        if upsert is not None:
            _raw["upsert"] = upsert
        body = encode_body(KbBulkUpdateInputBody, _raw)
        data = await self._http.patch(path, params=params, json_data=body)
        return KbBulkUpdateOutputBody.model_validate(data)
    async def kb_list_documents(
        self,
        project_id: str,
        *,
        limit: int | None = 50,
    ) -> KbListDocumentsOutputBody:
        """List knowledge base documents"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/documents"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return KbListDocumentsOutputBody.model_validate(data)
    async def kb_upload_document(
        self,
        project_id: str,
    ) -> KbUploadDocumentOutputBody:
        """Upload a document for knowledge extraction"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/documents"
        params = None
        data = await self._http.post(path, params=params)
        return KbUploadDocumentOutputBody.model_validate(data)
    async def kb_delete_document(
        self,
        project_id: str,
        doc_id: str,
    ) -> Any:
        """Delete a document"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/documents/{quote(doc_id, safe='')}"
        params = None
        data = await self._http.delete(path, params=params)
        return data
    async def kb_get_document(
        self,
        project_id: str,
        doc_id: str,
    ) -> KBDocument:
        """Get a single document"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/documents/{quote(doc_id, safe='')}"
        params = None
        data = await self._http.get(path, params=params)
        return KBDocument.model_validate(data)
    async def kb_insert_facts(
        self,
        project_id: str,
        *,
        facts: list[Any],
        relationships: list[Any] | None = None,
        source: str | None = None,
    ) -> KbInsertFactsOutputBody:
        """Insert facts into the knowledge base"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/facts"
        params = None
        _raw: dict[str, Any] = {}
        if facts is not None:
            _raw["facts"] = facts
        if relationships is not None:
            _raw["relationships"] = relationships
        if source is not None:
            _raw["source"] = source
        body = encode_body(KbInsertFactsInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return KbInsertFactsOutputBody.model_validate(data)
    async def kb_list_nodes(
        self,
        project_id: str,
        *,
        type: str | None = None,
        sort_by: str | None = None,
        sort_order: str | None = None,
        limit: int = 100,
    ) -> AsyncPage[KBNode]:
        """List knowledge base nodes"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/nodes"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        if type is not None:
            params["type"] = type
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order

        async def fetcher(p: dict[str, Any]) -> dict[str, Any]:
            return await self._http.get(path, params=p)

        return AsyncPage(
            fetcher=fetcher,
            params=params,
            item_key="nodes",
            item_parser=KBNode.model_validate,
            mode="offset",
            total_key="total",
        )
    async def kb_delete_node(
        self,
        project_id: str,
        node_id: str,
    ) -> Any:
        """Delete a knowledge base node"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/nodes/{quote(node_id, safe='')}"
        params = None
        data = await self._http.delete(path, params=params)
        return data
    async def kb_get_node(
        self,
        project_id: str,
        node_id: str,
        *,
        history: str | None = None,
    ) -> KbGetNodeOutputBody:
        """Get a knowledge base node with edges"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/nodes/{quote(node_id, safe='')}"
        params: dict[str, Any] = {}
        if history is not None:
            params["history"] = history
        data = await self._http.get(path, params=params)
        return KbGetNodeOutputBody.model_validate(data)
    async def kb_get_node_history(
        self,
        project_id: str,
        node_id: str,
        *,
        limit: int | None = 50,
    ) -> KbGetNodeHistoryOutputBody:
        """Get node version history"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/nodes/{quote(node_id, safe='')}/history"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return KbGetNodeHistoryOutputBody.model_validate(data)
    async def kb_promote_node_to_org(
        self,
        project_id: str,
        node_id: str,
        *,
        tenant_id: str,
    ) -> KBNodeWithScope:
        """Promote a project-scoped node to the organization-global scope"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/nodes/{quote(node_id, safe='')}/promote-to-org"
        params = None
        _raw: dict[str, Any] = {}
        if tenant_id is not None:
            _raw["tenant_id"] = tenant_id
        body = encode_body(KbPromoteNodeInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return KBNodeWithScope.model_validate(data)
    async def kb_list_schemas(
        self,
        project_id: str,
    ) -> KbListSchemasOutputBody:
        """List entity schemas"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/schemas"
        params = None
        data = await self._http.get(path, params=params)
        return KbListSchemasOutputBody.model_validate(data)
    async def kb_create_schema(
        self,
        project_id: str,
        *,
        description: str | None = None,
        display_name: str | None = None,
        entity_type: str,
        fields: list[Any],
        similarity_config: str | None = None,
    ) -> KBEntitySchema:
        """Create an entity schema"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/schemas"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if display_name is not None:
            _raw["display_name"] = display_name
        if entity_type is not None:
            _raw["entity_type"] = entity_type
        if fields is not None:
            _raw["fields"] = fields
        if similarity_config is not None:
            _raw["similarity_config"] = similarity_config
        body = encode_body(KbCreateSchemaInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return KBEntitySchema.model_validate(data)
    async def kb_delete_schema(
        self,
        project_id: str,
        schema_id: str,
    ) -> Any:
        """Delete an entity schema"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/schemas/{quote(schema_id, safe='')}"
        params = None
        data = await self._http.delete(path, params=params)
        return data
    async def kb_update_schema(
        self,
        project_id: str,
        schema_id: str,
        *,
        description: str | None = None,
        display_name: str | None = None,
        entity_type: str | None = None,
        fields: list[Any] | None = None,
        similarity_config: str | None = None,
    ) -> KBEntitySchema:
        """Update an entity schema"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/schemas/{quote(schema_id, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if display_name is not None:
            _raw["display_name"] = display_name
        if entity_type is not None:
            _raw["entity_type"] = entity_type
        if fields is not None:
            _raw["fields"] = fields
        if similarity_config is not None:
            _raw["similarity_config"] = similarity_config
        body = encode_body(KbUpdateSchemaInputBody, _raw)
        data = await self._http.put(path, params=params, json_data=body)
        return KBEntitySchema.model_validate(data)
    async def kb_search(
        self,
        project_id: str,
        *,
        q: str,
        limit: int | None = 20,
        depth: int | None = 1,
        history: str | None = None,
        type: str | None = None,
        mode: str | None = None,
        filters: str | None = None,
    ) -> KBSearchResponse:
        """Search the knowledge base"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/search"
        params: dict[str, Any] = {}
        if q is not None:
            params["q"] = q
        if limit is not None:
            params["limit"] = limit
        if depth is not None:
            params["depth"] = depth
        if history is not None:
            params["history"] = history
        if type is not None:
            params["type"] = type
        if mode is not None:
            params["mode"] = mode
        if filters is not None:
            params["filters"] = filters
        data = await self._http.get(path, params=params)
        return KBSearchResponse.model_validate(data)
    async def kb_get_stats(
        self,
        project_id: str,
    ) -> KbGetStatsOutputBody:
        """Get knowledge base statistics"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/knowledge/stats"
        params = None
        data = await self._http.get(path, params=params)
        return KbGetStatsOutputBody.model_validate(data)
    async def kb_list_org_nodes(
        self,
        tenant_id: str,
        *,
        limit: int | None = 200,
    ) -> KbListOrgNodesOutputBody:
        """List nodes in the organization-global KB scope"""
        path = f"/api/v1/tenants/{quote(tenant_id, safe='')}/knowledge/org-nodes"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return KbListOrgNodesOutputBody.model_validate(data)
    async def kb_create_org_node(
        self,
        tenant_id: str,
        *,
        confidence: float | None = None,
        label: str,
        node_type: str,
        properties: dict[str, Any] | None = None,
    ) -> KBNode:
        """Create a knowledge-base node in the organization-global scope"""
        path = f"/api/v1/tenants/{quote(tenant_id, safe='')}/knowledge/org-nodes"
        params = None
        _raw: dict[str, Any] = {}
        if confidence is not None:
            _raw["confidence"] = confidence
        if label is not None:
            _raw["label"] = label
        if node_type is not None:
            _raw["node_type"] = node_type
        if properties is not None:
            _raw["properties"] = properties
        body = encode_body(KbCreateOrgNodeInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return KBNode.model_validate(data)
