# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the LeadAssignments tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    LeadAssignmentBody,
    ListLeadAssignmentsResponse,
    OfferLeadAssignmentRequest,
    OfferLeadAssignmentResponse,
    TransitionInputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _LeadAssignmentsBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class LeadAssignments(_LeadAssignmentsBase):
    def list_lead_assignments(
        self,
        *,
        rep_user_id: str | None = None,
        state: str | None = None,
        limit: int | None = None,
    ) -> ListLeadAssignmentsResponse:
        """List lead assignments"""
        path = f"/api/v1/lead-assignments"
        params: dict[str, Any] = {}
        if rep_user_id is not None:
            params["rep_user_id"] = rep_user_id
        if state is not None:
            params["state"] = state
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return ListLeadAssignmentsResponse.model_validate(data)

    def offer_lead_assignment(
        self,
        *,
        candidates: list[Any],
        features: dict[str, Any] | None = None,
        lead_ref: str,
        policy: str | None = None,
        sla_seconds: int | None = None,
    ) -> OfferLeadAssignmentResponse:
        """Offer a unit of work to a rep"""
        path = f"/api/v1/lead-assignments/offer"
        params = None
        _raw: dict[str, Any] = {}
        if candidates is not None:
            _raw["candidates"] = candidates
        if features is not None:
            _raw["features"] = features
        if lead_ref is not None:
            _raw["lead_ref"] = lead_ref
        if policy is not None:
            _raw["policy"] = policy
        if sla_seconds is not None:
            _raw["sla_seconds"] = sla_seconds
        body = encode_body(OfferLeadAssignmentRequest, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return OfferLeadAssignmentResponse.model_validate(data)

    def get_lead_assignment(
        self,
        assignment_id: str,
    ) -> LeadAssignmentBody:
        """Read one lead assignment"""
        path = f"/api/v1/lead-assignments/{quote(assignment_id, safe='')}"
        params = None
        data = self._http.get(path, params=params)
        return LeadAssignmentBody.model_validate(data)

    def claim_lead_assignment(
        self,
        assignment_id: str,
        *,
        rep_user_id: str,
    ) -> LeadAssignmentBody:
        """Claim an offered lead"""
        path = f"/api/v1/lead-assignments/{quote(assignment_id, safe='')}/claim"
        params = None
        _raw: dict[str, Any] = {}
        if rep_user_id is not None:
            _raw["rep_user_id"] = rep_user_id
        body = encode_body(TransitionInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return LeadAssignmentBody.model_validate(data)

    def complete_lead_assignment(
        self,
        assignment_id: str,
        *,
        rep_user_id: str,
    ) -> LeadAssignmentBody:
        """Complete a claimed lead"""
        path = f"/api/v1/lead-assignments/{quote(assignment_id, safe='')}/complete"
        params = None
        _raw: dict[str, Any] = {}
        if rep_user_id is not None:
            _raw["rep_user_id"] = rep_user_id
        body = encode_body(TransitionInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return LeadAssignmentBody.model_validate(data)

    def release_lead_assignment(
        self,
        assignment_id: str,
        *,
        rep_user_id: str,
    ) -> LeadAssignmentBody:
        """Release an active lead back to the pool"""
        path = f"/api/v1/lead-assignments/{quote(assignment_id, safe='')}/release"
        params = None
        _raw: dict[str, Any] = {}
        if rep_user_id is not None:
            _raw["rep_user_id"] = rep_user_id
        body = encode_body(TransitionInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return LeadAssignmentBody.model_validate(data)


class AsyncLeadAssignments(_LeadAssignmentsBase):
    async def list_lead_assignments(
        self,
        *,
        rep_user_id: str | None = None,
        state: str | None = None,
        limit: int | None = None,
    ) -> ListLeadAssignmentsResponse:
        """List lead assignments"""
        path = f"/api/v1/lead-assignments"
        params: dict[str, Any] = {}
        if rep_user_id is not None:
            params["rep_user_id"] = rep_user_id
        if state is not None:
            params["state"] = state
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return ListLeadAssignmentsResponse.model_validate(data)

    async def offer_lead_assignment(
        self,
        *,
        candidates: list[Any],
        features: dict[str, Any] | None = None,
        lead_ref: str,
        policy: str | None = None,
        sla_seconds: int | None = None,
    ) -> OfferLeadAssignmentResponse:
        """Offer a unit of work to a rep"""
        path = f"/api/v1/lead-assignments/offer"
        params = None
        _raw: dict[str, Any] = {}
        if candidates is not None:
            _raw["candidates"] = candidates
        if features is not None:
            _raw["features"] = features
        if lead_ref is not None:
            _raw["lead_ref"] = lead_ref
        if policy is not None:
            _raw["policy"] = policy
        if sla_seconds is not None:
            _raw["sla_seconds"] = sla_seconds
        body = encode_body(OfferLeadAssignmentRequest, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return OfferLeadAssignmentResponse.model_validate(data)

    async def get_lead_assignment(
        self,
        assignment_id: str,
    ) -> LeadAssignmentBody:
        """Read one lead assignment"""
        path = f"/api/v1/lead-assignments/{quote(assignment_id, safe='')}"
        params = None
        data = await self._http.get(path, params=params)
        return LeadAssignmentBody.model_validate(data)

    async def claim_lead_assignment(
        self,
        assignment_id: str,
        *,
        rep_user_id: str,
    ) -> LeadAssignmentBody:
        """Claim an offered lead"""
        path = f"/api/v1/lead-assignments/{quote(assignment_id, safe='')}/claim"
        params = None
        _raw: dict[str, Any] = {}
        if rep_user_id is not None:
            _raw["rep_user_id"] = rep_user_id
        body = encode_body(TransitionInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return LeadAssignmentBody.model_validate(data)

    async def complete_lead_assignment(
        self,
        assignment_id: str,
        *,
        rep_user_id: str,
    ) -> LeadAssignmentBody:
        """Complete a claimed lead"""
        path = f"/api/v1/lead-assignments/{quote(assignment_id, safe='')}/complete"
        params = None
        _raw: dict[str, Any] = {}
        if rep_user_id is not None:
            _raw["rep_user_id"] = rep_user_id
        body = encode_body(TransitionInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return LeadAssignmentBody.model_validate(data)

    async def release_lead_assignment(
        self,
        assignment_id: str,
        *,
        rep_user_id: str,
    ) -> LeadAssignmentBody:
        """Release an active lead back to the pool"""
        path = f"/api/v1/lead-assignments/{quote(assignment_id, safe='')}/release"
        params = None
        _raw: dict[str, Any] = {}
        if rep_user_id is not None:
            _raw["rep_user_id"] = rep_user_id
        body = encode_body(TransitionInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return LeadAssignmentBody.model_validate(data)
