# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Memory tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    AtomicFact,
    CreateFactInputBody,
    FactHistoryResponse,
    ListAllFactsResponse,
    ListFactsResponse,
    MemoryResponse,
    SearchResponse,
    StoredFact,
    SummariesResponse,
    TimelineResponse,
    TriggerConsolidationInputBody,
    TriggerConsolidationOutputBody,
    UpdateFactInputBody,
    WisdomAuditResponse,
)
from sonzai.types import (
    DeleteWisdomResponse,
    MemoryResetResponse,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _MemoryBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Memory(_MemoryBase):
    def reset(
        self,
        agent_id: str,
        *,
        user_id: str,
        instance_id: str | None = None,
    ) -> MemoryResetResponse:
        """Reset memory for an agent-user pair"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        data = self._http.delete(path, params=params)
        if isinstance(data, dict):
            return MemoryResetResponse.model_validate(data)
        return MemoryResetResponse()

    def list(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
        instance_id: str | None = None,
        parent_id: str | None = None,
        include_contents: str | None = None,
        scope: str | None = None,
        limit: str | None = None,
        memory_type: str | None = None,
    ) -> MemoryResponse:
        """Get memory tree nodes for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        if parent_id is not None:
            params["parent_id"] = parent_id
        if include_contents is not None:
            params["include_contents"] = include_contents
        if scope is not None:
            params["scope"] = scope
        if limit is not None:
            params["limit"] = limit
        if memory_type is not None:
            params["memory_type"] = memory_type
        data = self._http.get(path, params=params)
        return MemoryResponse.model_validate(data)

    def consolidate_memory(
        self,
        agent_id: str,
        *,
        period: str,
        user_id: str,
    ) -> TriggerConsolidationOutputBody:
        """Trigger memory consolidation"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/consolidate"
        params = None
        _raw: dict[str, Any] = {}
        if period is not None:
            _raw["period"] = period
        if user_id is not None:
            _raw["user_id"] = user_id
        body = encode_body(TriggerConsolidationInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return TriggerConsolidationOutputBody.model_validate(data)

    def get_fact_history(
        self,
        agent_id: str,
        fact_id: str,
    ) -> FactHistoryResponse:
        """Get fact supersedes history"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/fact/{quote(fact_id, safe='')}/history"
        params = None
        data = self._http.get(path, params=params)
        return FactHistoryResponse.model_validate(data)

    def list_facts(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
        instance_id: str | None = None,
        fact_type: str | None = None,
        limit: int = 100,
    ) -> Page[StoredFact]:
        """List facts for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/facts"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        if fact_type is not None:
            params["fact_type"] = fact_type
        return Page(
            fetcher=lambda p: self._http.get(path, params=p),
            params=params,
            item_key="facts",
            item_parser=StoredFact.model_validate,
            mode="offset",
        )

    def create_fact(
        self,
        agent_id: str,
        *,
        instance_id: str | None = None,
        confidence: float | None = None,
        content: str,
        entities: list[Any] | None = None,
        fact_type: str | None = None,
        importance: float | None = None,
        metadata: dict[str, Any] | None = None,
        node_id: str | None = None,
        user_id: str | None = None,
    ) -> AtomicFact:
        """Create a new fact for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/facts"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        _raw: dict[str, Any] = {}
        if confidence is not None:
            _raw["confidence"] = confidence
        if content is not None:
            _raw["content"] = content
        if entities is not None:
            _raw["entities"] = entities
        if fact_type is not None:
            _raw["fact_type"] = fact_type
        if importance is not None:
            _raw["importance"] = importance
        if metadata is not None:
            _raw["metadata"] = metadata
        if node_id is not None:
            _raw["node_id"] = node_id
        if user_id is not None:
            _raw["user_id"] = user_id
        body = encode_body(CreateFactInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return AtomicFact.model_validate(data)

    def delete_fact(
        self,
        agent_id: str,
        fact_id: str,
    ) -> Any:
        """Delete a fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/facts/{quote(fact_id, safe='')}"
        params = None
        data = self._http.delete(path, params=params)
        return data

    def update_fact(
        self,
        agent_id: str,
        fact_id: str,
        *,
        confidence: float | None = None,
        content: str | None = None,
        entities: list[Any] | None = None,
        fact_type: str | None = None,
        importance: float | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> AtomicFact:
        """Update an existing fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/facts/{quote(fact_id, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if confidence is not None:
            _raw["confidence"] = confidence
        if content is not None:
            _raw["content"] = content
        if entities is not None:
            _raw["entities"] = entities
        if fact_type is not None:
            _raw["fact_type"] = fact_type
        if importance is not None:
            _raw["importance"] = importance
        if metadata is not None:
            _raw["metadata"] = metadata
        body = encode_body(UpdateFactInputBody, _raw)
        data = self._http.put(path, params=params, json_data=body)
        return AtomicFact.model_validate(data)

    def search(
        self,
        agent_id: str,
        *,
        query: str,
        user_id: str | None = None,
        instance_id: str | None = None,
        mode: str | None = None,
        limit: str | None = None,
        include_verbatim: str | None = None,
    ) -> SearchResponse:
        """Search agent memories (semantic or BM25)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/search"
        params: dict[str, Any] = {}
        if query is not None:
            params["q"] = query
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        if mode is not None:
            params["mode"] = mode
        if limit is not None:
            params["limit"] = limit
        if include_verbatim is not None:
            params["include_verbatim"] = include_verbatim
        data = self._http.get(path, params=params)
        return SearchResponse.model_validate(data)

    def list_summaries(
        self,
        agent_id: str,
        *,
        period: str | None = None,
        limit: int | None = 20,
    ) -> SummariesResponse:
        """List memory consolidation summaries"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/summaries"
        params: dict[str, Any] = {}
        if period is not None:
            params["period"] = period
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return SummariesResponse.model_validate(data)

    def timeline(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
        instance_id: str | None = None,
        start: str | None = None,
        end: str | None = None,
    ) -> TimelineResponse:
        """Get memory timeline grouped by session"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/timeline"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        if start is not None:
            params["start"] = start
        if end is not None:
            params["end"] = end
        data = self._http.get(path, params=params)
        return TimelineResponse.model_validate(data)

    def get_wisdom_audit(
        self,
        agent_id: str,
        fact_id: str,
    ) -> WisdomAuditResponse:
        """Get wisdom fact audit trail"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/wisdom/audit/{quote(fact_id, safe='')}"
        params = None
        data = self._http.get(path, params=params)
        return WisdomAuditResponse.model_validate(data)

    def delete_wisdom_fact(
        self,
        agent_id: str,
        fact_id: str,
    ) -> DeleteWisdomResponse:
        """Delete a wisdom fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/wisdom/{quote(fact_id, safe='')}"
        params = None
        data = self._http.delete(path, params=params)
        if isinstance(data, dict):
            return DeleteWisdomResponse.model_validate(data)
        return DeleteWisdomResponse()

    def list_user_facts(
        self,
        agent_id: str,
        user_id: str,
        *,
        instance_id: str | None = None,
        limit: str | None = None,
        has_metadata: str | None = None,
        metadata_item_type: str | None = None,
    ) -> ListAllFactsResponse:
        """List all active facts for a specific user"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/facts"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        if limit is not None:
            params["limit"] = limit
        if has_metadata is not None:
            params["has_metadata"] = has_metadata
        if metadata_item_type is not None:
            params["metadata.item_type"] = metadata_item_type
        data = self._http.get(path, params=params)
        return ListAllFactsResponse.model_validate(data)


class AsyncMemory(_MemoryBase):
    async def reset(
        self,
        agent_id: str,
        *,
        user_id: str,
        instance_id: str | None = None,
    ) -> MemoryResetResponse:
        """Reset memory for an agent-user pair"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        data = await self._http.delete(path, params=params)
        if isinstance(data, dict):
            return MemoryResetResponse.model_validate(data)
        return MemoryResetResponse()

    async def list(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
        instance_id: str | None = None,
        parent_id: str | None = None,
        include_contents: str | None = None,
        scope: str | None = None,
        limit: str | None = None,
        memory_type: str | None = None,
    ) -> MemoryResponse:
        """Get memory tree nodes for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        if parent_id is not None:
            params["parent_id"] = parent_id
        if include_contents is not None:
            params["include_contents"] = include_contents
        if scope is not None:
            params["scope"] = scope
        if limit is not None:
            params["limit"] = limit
        if memory_type is not None:
            params["memory_type"] = memory_type
        data = await self._http.get(path, params=params)
        return MemoryResponse.model_validate(data)

    async def consolidate_memory(
        self,
        agent_id: str,
        *,
        period: str,
        user_id: str,
    ) -> TriggerConsolidationOutputBody:
        """Trigger memory consolidation"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/consolidate"
        params = None
        _raw: dict[str, Any] = {}
        if period is not None:
            _raw["period"] = period
        if user_id is not None:
            _raw["user_id"] = user_id
        body = encode_body(TriggerConsolidationInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return TriggerConsolidationOutputBody.model_validate(data)

    async def get_fact_history(
        self,
        agent_id: str,
        fact_id: str,
    ) -> FactHistoryResponse:
        """Get fact supersedes history"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/fact/{quote(fact_id, safe='')}/history"
        params = None
        data = await self._http.get(path, params=params)
        return FactHistoryResponse.model_validate(data)

    async def list_facts(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
        instance_id: str | None = None,
        fact_type: str | None = None,
        limit: int = 100,
    ) -> AsyncPage[StoredFact]:
        """List facts for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/facts"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        if fact_type is not None:
            params["fact_type"] = fact_type

        async def fetcher(p: dict[str, Any]) -> dict[str, Any]:
            return await self._http.get(path, params=p)

        return AsyncPage(
            fetcher=fetcher,
            params=params,
            item_key="facts",
            item_parser=StoredFact.model_validate,
            mode="offset",
        )

    async def create_fact(
        self,
        agent_id: str,
        *,
        instance_id: str | None = None,
        confidence: float | None = None,
        content: str,
        entities: list[Any] | None = None,
        fact_type: str | None = None,
        importance: float | None = None,
        metadata: dict[str, Any] | None = None,
        node_id: str | None = None,
        user_id: str | None = None,
    ) -> AtomicFact:
        """Create a new fact for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/facts"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        _raw: dict[str, Any] = {}
        if confidence is not None:
            _raw["confidence"] = confidence
        if content is not None:
            _raw["content"] = content
        if entities is not None:
            _raw["entities"] = entities
        if fact_type is not None:
            _raw["fact_type"] = fact_type
        if importance is not None:
            _raw["importance"] = importance
        if metadata is not None:
            _raw["metadata"] = metadata
        if node_id is not None:
            _raw["node_id"] = node_id
        if user_id is not None:
            _raw["user_id"] = user_id
        body = encode_body(CreateFactInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return AtomicFact.model_validate(data)

    async def delete_fact(
        self,
        agent_id: str,
        fact_id: str,
    ) -> Any:
        """Delete a fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/facts/{quote(fact_id, safe='')}"
        params = None
        data = await self._http.delete(path, params=params)
        return data

    async def update_fact(
        self,
        agent_id: str,
        fact_id: str,
        *,
        confidence: float | None = None,
        content: str | None = None,
        entities: list[Any] | None = None,
        fact_type: str | None = None,
        importance: float | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> AtomicFact:
        """Update an existing fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/facts/{quote(fact_id, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if confidence is not None:
            _raw["confidence"] = confidence
        if content is not None:
            _raw["content"] = content
        if entities is not None:
            _raw["entities"] = entities
        if fact_type is not None:
            _raw["fact_type"] = fact_type
        if importance is not None:
            _raw["importance"] = importance
        if metadata is not None:
            _raw["metadata"] = metadata
        body = encode_body(UpdateFactInputBody, _raw)
        data = await self._http.put(path, params=params, json_data=body)
        return AtomicFact.model_validate(data)

    async def search(
        self,
        agent_id: str,
        *,
        query: str,
        user_id: str | None = None,
        instance_id: str | None = None,
        mode: str | None = None,
        limit: str | None = None,
        include_verbatim: str | None = None,
    ) -> SearchResponse:
        """Search agent memories (semantic or BM25)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/search"
        params: dict[str, Any] = {}
        if query is not None:
            params["q"] = query
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        if mode is not None:
            params["mode"] = mode
        if limit is not None:
            params["limit"] = limit
        if include_verbatim is not None:
            params["include_verbatim"] = include_verbatim
        data = await self._http.get(path, params=params)
        return SearchResponse.model_validate(data)

    async def list_summaries(
        self,
        agent_id: str,
        *,
        period: str | None = None,
        limit: int | None = 20,
    ) -> SummariesResponse:
        """List memory consolidation summaries"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/summaries"
        params: dict[str, Any] = {}
        if period is not None:
            params["period"] = period
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return SummariesResponse.model_validate(data)

    async def timeline(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
        instance_id: str | None = None,
        start: str | None = None,
        end: str | None = None,
    ) -> TimelineResponse:
        """Get memory timeline grouped by session"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/timeline"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        if start is not None:
            params["start"] = start
        if end is not None:
            params["end"] = end
        data = await self._http.get(path, params=params)
        return TimelineResponse.model_validate(data)

    async def get_wisdom_audit(
        self,
        agent_id: str,
        fact_id: str,
    ) -> WisdomAuditResponse:
        """Get wisdom fact audit trail"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/wisdom/audit/{quote(fact_id, safe='')}"
        params = None
        data = await self._http.get(path, params=params)
        return WisdomAuditResponse.model_validate(data)

    async def delete_wisdom_fact(
        self,
        agent_id: str,
        fact_id: str,
    ) -> DeleteWisdomResponse:
        """Delete a wisdom fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/memory/wisdom/{quote(fact_id, safe='')}"
        params = None
        data = await self._http.delete(path, params=params)
        if isinstance(data, dict):
            return DeleteWisdomResponse.model_validate(data)
        return DeleteWisdomResponse()

    async def list_user_facts(
        self,
        agent_id: str,
        user_id: str,
        *,
        instance_id: str | None = None,
        limit: str | None = None,
        has_metadata: str | None = None,
        metadata_item_type: str | None = None,
    ) -> ListAllFactsResponse:
        """List all active facts for a specific user"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users/{quote(user_id, safe='')}/facts"
        params: dict[str, Any] = {}
        if instance_id is not None:
            params["instance_id"] = instance_id
        if limit is not None:
            params["limit"] = limit
        if has_metadata is not None:
            params["has_metadata"] = has_metadata
        if metadata_item_type is not None:
            params["metadata.item_type"] = metadata_item_type
        data = await self._http.get(path, params=params)
        return ListAllFactsResponse.model_validate(data)
