# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the MlModels tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    ModelExportOutputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _MlModelsBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class MlModels(_MlModelsBase):
    def export_model(
        self,
        use_case: str,
        *,
        format: str | None = None,
    ) -> ModelExportOutputBody:
        """Export the tenant's trained model artifact"""
        path = f"/api/v1/models/{quote(use_case, safe='')}/export"
        params: dict[str, Any] = {}
        if format is not None:
            params["format"] = format
        data = self._http.get(path, params=params)
        return ModelExportOutputBody.model_validate(data)


class AsyncMlModels(_MlModelsBase):
    async def export_model(
        self,
        use_case: str,
        *,
        format: str | None = None,
    ) -> ModelExportOutputBody:
        """Export the tenant's trained model artifact"""
        path = f"/api/v1/models/{quote(use_case, safe='')}/export"
        params: dict[str, Any] = {}
        if format is not None:
            params["format"] = format
        data = await self._http.get(path, params=params)
        return ModelExportOutputBody.model_validate(data)
