# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Models tag."""

from __future__ import annotations

from typing import Any
from sonzai._generated.models import (
    CachedModelsPayload,
    GetAgentModelsOutputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _ModelsBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Models(_ModelsBase):
    def get_agent_models(
        self,
        agent_id: str,
    ) -> GetAgentModelsOutputBody:
        """List available models for an agent"""
        path = f"/api/v1/agents/{agent_id}/models"
        params = None
        data = self._http.get(path, params=params)
        return GetAgentModelsOutputBody.model_validate(data)

    def list_models(
        self,
    ) -> CachedModelsPayload:
        """List LLM providers and model variants"""
        path = f"/api/v1/models"
        params = None
        data = self._http.get(path, params=params)
        return CachedModelsPayload.model_validate(data)


class AsyncModels(_ModelsBase):
    async def get_agent_models(
        self,
        agent_id: str,
    ) -> GetAgentModelsOutputBody:
        """List available models for an agent"""
        path = f"/api/v1/agents/{agent_id}/models"
        params = None
        data = await self._http.get(path, params=params)
        return GetAgentModelsOutputBody.model_validate(data)

    async def list_models(
        self,
    ) -> CachedModelsPayload:
        """List LLM providers and model variants"""
        path = f"/api/v1/models"
        params = None
        data = await self._http.get(path, params=params)
        return CachedModelsPayload.model_validate(data)
