# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Mood tag."""

from __future__ import annotations

from typing import Any

from sonzai._generated.models import (
    MoodAggregateResponse,
    MoodHistoryResponse,
    MoodResponse,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _MoodBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Mood(_MoodBase):
    def get_mood(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
        instance_id: str | None = None,
    ) -> MoodResponse:
        """Get agent mood state"""
        path = f"/agents/{agentId}/mood"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        data = self._http.get(path, params=params)
        return MoodResponse.model_validate(data)
    def get_mood_history(
        self,
        agent_id: str,
        *,
        limit: int | None = 50,
        user_id: str | None = None,
        instance_id: str | None = None,
    ) -> MoodHistoryResponse:
        """Get agent mood history"""
        path = f"/agents/{agentId}/mood-history"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        data = self._http.get(path, params=params)
        return MoodHistoryResponse.model_validate(data)
    def get_mood_aggregate(
        self,
        agent_id: str,
        *,
        days: int | None = 5,
    ) -> MoodAggregateResponse:
        """Get aggregated mood across users"""
        path = f"/agents/{agentId}/mood/aggregate"
        params: dict[str, Any] = {}
        if days is not None:
            params["days"] = days
        data = self._http.get(path, params=params)
        return MoodAggregateResponse.model_validate(data)


class AsyncMood(_MoodBase):
    async def get_mood(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
        instance_id: str | None = None,
    ) -> MoodResponse:
        """Get agent mood state"""
        path = f"/agents/{agentId}/mood"
        params: dict[str, Any] = {}
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        data = await self._http.get(path, params=params)
        return MoodResponse.model_validate(data)
    async def get_mood_history(
        self,
        agent_id: str,
        *,
        limit: int | None = 50,
        user_id: str | None = None,
        instance_id: str | None = None,
    ) -> MoodHistoryResponse:
        """Get agent mood history"""
        path = f"/agents/{agentId}/mood-history"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if user_id is not None:
            params["user_id"] = user_id
        if instance_id is not None:
            params["instance_id"] = instance_id
        data = await self._http.get(path, params=params)
        return MoodHistoryResponse.model_validate(data)
    async def get_mood_aggregate(
        self,
        agent_id: str,
        *,
        days: int | None = 5,
    ) -> MoodAggregateResponse:
        """Get aggregated mood across users"""
        path = f"/agents/{agentId}/mood/aggregate"
        params: dict[str, Any] = {}
        if days is not None:
            params["days"] = days
        data = await self._http.get(path, params=params)
        return MoodAggregateResponse.model_validate(data)
