# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Onboarding tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    ClaimInputBody,
    ClaimLinkInputBody,
    ClaimLinkOutputBody,
    ClaimResult,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _OnboardingBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Onboarding(_OnboardingBase):
    def onboarding_claim(
        self,
        *,
        claim_token: str,
    ) -> ClaimResult:
        """Claim a trial tenant into your account"""
        path = f"/api/v1/onboarding/claim"
        params = None
        _raw: dict[str, Any] = {}
        if claim_token is not None:
            _raw["claim_token"] = claim_token
        body = encode_body(ClaimInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return ClaimResult.model_validate(data)

    def onboarding_claim_link(
        self,
    ) -> ClaimLinkOutputBody:
        """Get a claim link for the caller's trial tenant"""
        path = f"/api/v1/onboarding/claim-link"
        params = None
        data = self._http.post(path, params=params)
        return ClaimLinkOutputBody.model_validate(data)


class AsyncOnboarding(_OnboardingBase):
    async def onboarding_claim(
        self,
        *,
        claim_token: str,
    ) -> ClaimResult:
        """Claim a trial tenant into your account"""
        path = f"/api/v1/onboarding/claim"
        params = None
        _raw: dict[str, Any] = {}
        if claim_token is not None:
            _raw["claim_token"] = claim_token
        body = encode_body(ClaimInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return ClaimResult.model_validate(data)

    async def onboarding_claim_link(
        self,
    ) -> ClaimLinkOutputBody:
        """Get a claim link for the caller's trial tenant"""
        path = f"/api/v1/onboarding/claim-link"
        params = None
        data = await self._http.post(path, params=params)
        return ClaimLinkOutputBody.model_validate(data)
