# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the OrgBilling tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    ActiveCharacterSummary,
    ContextEngineEventSummary,
    EnterpriseContract,
    OrgBillingCheckoutInputBody,
    OrgBillingSubscribeInputBody,
    OrgBillingURLBody,
    OrgBillingVoucherInputBody,
    OrgUsageSummaryBody,
    RedeemVoucherResponse,
    ServiceUsageSummary,
    TenantBillingProfile,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _OrgBillingBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class OrgBilling(_OrgBillingBase):
    def get_org_billing(
        self,
    ) -> TenantBillingProfile:
        """Get org billing profile"""
        path = f"/api/v1/org/billing"
        params = None
        data = self._http.get(path, params=params)
        return TenantBillingProfile.model_validate(data)
    def create_org_billing_checkout(
        self,
        *,
        amount: int,
        currency: str | None = None,
    ) -> OrgBillingURLBody:
        """Create Stripe checkout session (credit top-up)"""
        path = f"/api/v1/org/billing/checkout"
        params = None
        _raw: dict[str, Any] = {}
        if amount is not None:
            _raw["amount"] = amount
        if currency is not None:
            _raw["currency"] = currency
        body = encode_body(OrgBillingCheckoutInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return OrgBillingURLBody.model_validate(data)
    def create_org_billing_portal(
        self,
    ) -> OrgBillingURLBody:
        """Create Stripe billing-portal session"""
        path = f"/api/v1/org/billing/portal"
        params = None
        data = self._http.post(path, params=params)
        return OrgBillingURLBody.model_validate(data)
    def list_org_active_characters(
        self,
        *,
        days: int | None = 30,
    ) -> ActiveCharacterSummary:
        """List active characters for billing"""
        path = f"/api/v1/org/characters"
        params: dict[str, Any] = {}
        if days is not None:
            params["days"] = days
        data = self._http.get(path, params=params)
        return ActiveCharacterSummary.model_validate(data)
    def get_org_contract(
        self,
    ) -> EnterpriseContract:
        """Get org enterprise contract"""
        path = f"/api/v1/org/contract"
        params = None
        data = self._http.get(path, params=params)
        return EnterpriseContract.model_validate(data)
    def subscribe_to_org_contract(
        self,
        *,
        contract_id: str,
    ) -> OrgBillingURLBody:
        """Subscribe tenant to an enterprise contract"""
        path = f"/api/v1/org/contract/subscribe"
        params = None
        _raw: dict[str, Any] = {}
        if contract_id is not None:
            _raw["contractId"] = contract_id
        body = encode_body(OrgBillingSubscribeInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return OrgBillingURLBody.model_validate(data)
    def get_org_context_engine_events(
        self,
        *,
        days: int | None = 30,
    ) -> ContextEngineEventSummary:
        """Context engine event usage"""
        path = f"/api/v1/org/events"
        params: dict[str, Any] = {}
        if days is not None:
            params["days"] = days
        data = self._http.get(path, params=params)
        return ContextEngineEventSummary.model_validate(data)
    def get_org_ledger(
        self,
        *,
        days: int | None = 30,
    ) -> Any:
        """Get org billing ledger"""
        path = f"/api/v1/org/ledger"
        params: dict[str, Any] = {}
        if days is not None:
            params["days"] = days
        data = self._http.get(path, params=params)
        return data
    def get_org_model_pricing(
        self,
    ) -> Any:
        """Get active model pricing"""
        path = f"/api/v1/org/model-pricing"
        params = None
        data = self._http.get(path, params=params)
        return data
    def list_org_service_agreements(
        self,
    ) -> Any:
        """List active service agreements"""
        path = f"/api/v1/org/service-agreements"
        params = None
        data = self._http.get(path, params=params)
        return data
    def get_org_service_usage(
        self,
        *,
        days: int | None = 30,
    ) -> ServiceUsageSummary:
        """Get org service usage"""
        path = f"/api/v1/org/service-usage"
        params: dict[str, Any] = {}
        if days is not None:
            params["days"] = days
        data = self._http.get(path, params=params)
        return ServiceUsageSummary.model_validate(data)
    def get_org_usage_summary(
        self,
        *,
        days: int | None = 30,
    ) -> OrgUsageSummaryBody:
        """Get org usage summary"""
        path = f"/api/v1/org/usage-summary"
        params: dict[str, Any] = {}
        if days is not None:
            params["days"] = days
        data = self._http.get(path, params=params)
        return OrgUsageSummaryBody.model_validate(data)
    def redeem_org_voucher(
        self,
        *,
        code: str,
    ) -> RedeemVoucherResponse:
        """Redeem a voucher code"""
        path = f"/api/v1/org/vouchers/redeem"
        params = None
        _raw: dict[str, Any] = {}
        if code is not None:
            _raw["code"] = code
        body = encode_body(OrgBillingVoucherInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return RedeemVoucherResponse.model_validate(data)


class AsyncOrgBilling(_OrgBillingBase):
    async def get_org_billing(
        self,
    ) -> TenantBillingProfile:
        """Get org billing profile"""
        path = f"/api/v1/org/billing"
        params = None
        data = await self._http.get(path, params=params)
        return TenantBillingProfile.model_validate(data)
    async def create_org_billing_checkout(
        self,
        *,
        amount: int,
        currency: str | None = None,
    ) -> OrgBillingURLBody:
        """Create Stripe checkout session (credit top-up)"""
        path = f"/api/v1/org/billing/checkout"
        params = None
        _raw: dict[str, Any] = {}
        if amount is not None:
            _raw["amount"] = amount
        if currency is not None:
            _raw["currency"] = currency
        body = encode_body(OrgBillingCheckoutInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return OrgBillingURLBody.model_validate(data)
    async def create_org_billing_portal(
        self,
    ) -> OrgBillingURLBody:
        """Create Stripe billing-portal session"""
        path = f"/api/v1/org/billing/portal"
        params = None
        data = await self._http.post(path, params=params)
        return OrgBillingURLBody.model_validate(data)
    async def list_org_active_characters(
        self,
        *,
        days: int | None = 30,
    ) -> ActiveCharacterSummary:
        """List active characters for billing"""
        path = f"/api/v1/org/characters"
        params: dict[str, Any] = {}
        if days is not None:
            params["days"] = days
        data = await self._http.get(path, params=params)
        return ActiveCharacterSummary.model_validate(data)
    async def get_org_contract(
        self,
    ) -> EnterpriseContract:
        """Get org enterprise contract"""
        path = f"/api/v1/org/contract"
        params = None
        data = await self._http.get(path, params=params)
        return EnterpriseContract.model_validate(data)
    async def subscribe_to_org_contract(
        self,
        *,
        contract_id: str,
    ) -> OrgBillingURLBody:
        """Subscribe tenant to an enterprise contract"""
        path = f"/api/v1/org/contract/subscribe"
        params = None
        _raw: dict[str, Any] = {}
        if contract_id is not None:
            _raw["contractId"] = contract_id
        body = encode_body(OrgBillingSubscribeInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return OrgBillingURLBody.model_validate(data)
    async def get_org_context_engine_events(
        self,
        *,
        days: int | None = 30,
    ) -> ContextEngineEventSummary:
        """Context engine event usage"""
        path = f"/api/v1/org/events"
        params: dict[str, Any] = {}
        if days is not None:
            params["days"] = days
        data = await self._http.get(path, params=params)
        return ContextEngineEventSummary.model_validate(data)
    async def get_org_ledger(
        self,
        *,
        days: int | None = 30,
    ) -> Any:
        """Get org billing ledger"""
        path = f"/api/v1/org/ledger"
        params: dict[str, Any] = {}
        if days is not None:
            params["days"] = days
        data = await self._http.get(path, params=params)
        return data
    async def get_org_model_pricing(
        self,
    ) -> Any:
        """Get active model pricing"""
        path = f"/api/v1/org/model-pricing"
        params = None
        data = await self._http.get(path, params=params)
        return data
    async def list_org_service_agreements(
        self,
    ) -> Any:
        """List active service agreements"""
        path = f"/api/v1/org/service-agreements"
        params = None
        data = await self._http.get(path, params=params)
        return data
    async def get_org_service_usage(
        self,
        *,
        days: int | None = 30,
    ) -> ServiceUsageSummary:
        """Get org service usage"""
        path = f"/api/v1/org/service-usage"
        params: dict[str, Any] = {}
        if days is not None:
            params["days"] = days
        data = await self._http.get(path, params=params)
        return ServiceUsageSummary.model_validate(data)
    async def get_org_usage_summary(
        self,
        *,
        days: int | None = 30,
    ) -> OrgUsageSummaryBody:
        """Get org usage summary"""
        path = f"/api/v1/org/usage-summary"
        params: dict[str, Any] = {}
        if days is not None:
            params["days"] = days
        data = await self._http.get(path, params=params)
        return OrgUsageSummaryBody.model_validate(data)
    async def redeem_org_voucher(
        self,
        *,
        code: str,
    ) -> RedeemVoucherResponse:
        """Redeem a voucher code"""
        path = f"/api/v1/org/vouchers/redeem"
        params = None
        _raw: dict[str, Any] = {}
        if code is not None:
            _raw["code"] = code
        body = encode_body(OrgBillingVoucherInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return RedeemVoucherResponse.model_validate(data)
