# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Personality tag."""

from __future__ import annotations

from typing import Any

from sonzai._generated.models import (
    BatchGetPersonalitiesInputBody,
    BatchPersonalityResponse,
    PersonalityResponse,
    UpdatePersonalityBody,
    UpdatePersonalityOutputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _PersonalityBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Personality(_PersonalityBase):
    def batch_get_personalities(
        self,
        **body_fields: Any,
    ) -> BatchPersonalityResponse:
        """Batch-fetch agent personalities"""
        path = f"/agents/personalities/batch"
        params = None
        body = encode_body(BatchGetPersonalitiesInputBody, body_fields)
        data = self._http.post(path, params=params, body=body)
        return BatchPersonalityResponse.model_validate(data)
    def get_personality(
        self,
        agent_id: str,
        *,
        history_limit: int | None = 200,
        since: str | None = None,
    ) -> PersonalityResponse:
        """Get agent personality profile and evolution"""
        path = f"/agents/{agentId}/personality"
        params: dict[str, Any] = {}
        if history_limit is not None:
            params["history_limit"] = history_limit
        if since is not None:
            params["since"] = since
        data = self._http.get(path, params=params)
        return PersonalityResponse.model_validate(data)
    def update_personality(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> UpdatePersonalityOutputBody:
        """Update agent personality scores"""
        path = f"/agents/{agentId}/personality"
        params = None
        body = encode_body(UpdatePersonalityBody, body_fields)
        data = self._http.put(path, params=params, body=body)
        return UpdatePersonalityOutputBody.model_validate(data)


class AsyncPersonality(_PersonalityBase):
    async def batch_get_personalities(
        self,
        **body_fields: Any,
    ) -> BatchPersonalityResponse:
        """Batch-fetch agent personalities"""
        path = f"/agents/personalities/batch"
        params = None
        body = encode_body(BatchGetPersonalitiesInputBody, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return BatchPersonalityResponse.model_validate(data)
    async def get_personality(
        self,
        agent_id: str,
        *,
        history_limit: int | None = 200,
        since: str | None = None,
    ) -> PersonalityResponse:
        """Get agent personality profile and evolution"""
        path = f"/agents/{agentId}/personality"
        params: dict[str, Any] = {}
        if history_limit is not None:
            params["history_limit"] = history_limit
        if since is not None:
            params["since"] = since
        data = await self._http.get(path, params=params)
        return PersonalityResponse.model_validate(data)
    async def update_personality(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> UpdatePersonalityOutputBody:
        """Update agent personality scores"""
        path = f"/agents/{agentId}/personality"
        params = None
        body = encode_body(UpdatePersonalityBody, body_fields)
        data = await self._http.put(path, params=params, body=body)
        return UpdatePersonalityOutputBody.model_validate(data)
