# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Priming tag."""

from __future__ import annotations

from typing import Any

from sonzai._generated.models import (
    AddContentRequest,
    AddUserContentHumaOutputBody,
    BatchImportRequest,
    BatchImportUsersHumaOutputBody,
    ImportJob,
    ListImportJobsOutputBody,
    ListImportJobUsersOutputBody,
    PrimeUserRequest,
    UpdateMetadataRequest,
    UpdateUserMetadataHumaOutputBody,
    UserPrimingMetadata,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _PrimingBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Priming(_PrimingBase):
    def batch_import_users(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> BatchImportUsersHumaOutputBody:
        """Batch import users"""
        path = f"/agents/{agentId}/users/import"
        params = None
        body = encode_body(BatchImportRequest, body_fields)
        data = self._http.post(path, params=params, body=body)
        return BatchImportUsersHumaOutputBody.model_validate(data)
    def get_import_status(
        self,
        agent_id: str,
        job_id: str,
    ) -> ImportJob:
        """Get batch import job status"""
        path = f"/agents/{agentId}/users/import/{jobId}"
        params = None
        data = self._http.get(path, params=params)
        return ImportJob.model_validate(data)
    def list_import_job_users(
        self,
        agent_id: str,
        job_id: str,
        *,
        limit: int | None = 100,
    ) -> ListImportJobUsersOutputBody:
        """List per-user progress for a batch import job"""
        path = f"/agents/{agentId}/users/import/{jobId}/users"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return ListImportJobUsersOutputBody.model_validate(data)
    def list_import_jobs(
        self,
        agent_id: str,
        *,
        limit: int | None = 20,
    ) -> ListImportJobsOutputBody:
        """List import jobs for an agent"""
        path = f"/agents/{agentId}/users/imports"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return ListImportJobsOutputBody.model_validate(data)
    def add_user_content(
        self,
        agent_id: str,
        user_id: str,
        **body_fields: Any,
    ) -> AddUserContentHumaOutputBody:
        """Add content for a user"""
        path = f"/agents/{agentId}/users/{userId}/content"
        params = None
        body = encode_body(AddContentRequest, body_fields)
        data = self._http.post(path, params=params, body=body)
        return AddUserContentHumaOutputBody.model_validate(data)
    def get_user_metadata(
        self,
        agent_id: str,
        user_id: str,
    ) -> UserPrimingMetadata:
        """Get user priming metadata"""
        path = f"/agents/{agentId}/users/{userId}/metadata"
        params = None
        data = self._http.get(path, params=params)
        return UserPrimingMetadata.model_validate(data)
    def update_user_metadata(
        self,
        agent_id: str,
        user_id: str,
        **body_fields: Any,
    ) -> UpdateUserMetadataHumaOutputBody:
        """Update user priming metadata"""
        path = f"/agents/{agentId}/users/{userId}/metadata"
        params = None
        body = encode_body(UpdateMetadataRequest, body_fields)
        data = self._http.patch(path, params=params, body=body)
        return UpdateUserMetadataHumaOutputBody.model_validate(data)
    def prime_user(
        self,
        agent_id: str,
        user_id: str,
        **body_fields: Any,
    ) -> Any:
        """Prime a user with external data"""
        path = f"/agents/{agentId}/users/{userId}/prime"
        params = None
        body = encode_body(PrimeUserRequest, body_fields)
        data = self._http.post(path, params=params, body=body)
        return data
    def get_prime_status(
        self,
        agent_id: str,
        user_id: str,
        job_id: str,
    ) -> ImportJob:
        """Get priming job status"""
        path = f"/agents/{agentId}/users/{userId}/prime/{jobId}"
        params = None
        data = self._http.get(path, params=params)
        return ImportJob.model_validate(data)


class AsyncPriming(_PrimingBase):
    async def batch_import_users(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> BatchImportUsersHumaOutputBody:
        """Batch import users"""
        path = f"/agents/{agentId}/users/import"
        params = None
        body = encode_body(BatchImportRequest, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return BatchImportUsersHumaOutputBody.model_validate(data)
    async def get_import_status(
        self,
        agent_id: str,
        job_id: str,
    ) -> ImportJob:
        """Get batch import job status"""
        path = f"/agents/{agentId}/users/import/{jobId}"
        params = None
        data = await self._http.get(path, params=params)
        return ImportJob.model_validate(data)
    async def list_import_job_users(
        self,
        agent_id: str,
        job_id: str,
        *,
        limit: int | None = 100,
    ) -> ListImportJobUsersOutputBody:
        """List per-user progress for a batch import job"""
        path = f"/agents/{agentId}/users/import/{jobId}/users"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return ListImportJobUsersOutputBody.model_validate(data)
    async def list_import_jobs(
        self,
        agent_id: str,
        *,
        limit: int | None = 20,
    ) -> ListImportJobsOutputBody:
        """List import jobs for an agent"""
        path = f"/agents/{agentId}/users/imports"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return ListImportJobsOutputBody.model_validate(data)
    async def add_user_content(
        self,
        agent_id: str,
        user_id: str,
        **body_fields: Any,
    ) -> AddUserContentHumaOutputBody:
        """Add content for a user"""
        path = f"/agents/{agentId}/users/{userId}/content"
        params = None
        body = encode_body(AddContentRequest, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return AddUserContentHumaOutputBody.model_validate(data)
    async def get_user_metadata(
        self,
        agent_id: str,
        user_id: str,
    ) -> UserPrimingMetadata:
        """Get user priming metadata"""
        path = f"/agents/{agentId}/users/{userId}/metadata"
        params = None
        data = await self._http.get(path, params=params)
        return UserPrimingMetadata.model_validate(data)
    async def update_user_metadata(
        self,
        agent_id: str,
        user_id: str,
        **body_fields: Any,
    ) -> UpdateUserMetadataHumaOutputBody:
        """Update user priming metadata"""
        path = f"/agents/{agentId}/users/{userId}/metadata"
        params = None
        body = encode_body(UpdateMetadataRequest, body_fields)
        data = await self._http.patch(path, params=params, body=body)
        return UpdateUserMetadataHumaOutputBody.model_validate(data)
    async def prime_user(
        self,
        agent_id: str,
        user_id: str,
        **body_fields: Any,
    ) -> Any:
        """Prime a user with external data"""
        path = f"/agents/{agentId}/users/{userId}/prime"
        params = None
        body = encode_body(PrimeUserRequest, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return data
    async def get_prime_status(
        self,
        agent_id: str,
        user_id: str,
        job_id: str,
    ) -> ImportJob:
        """Get priming job status"""
        path = f"/agents/{agentId}/users/{userId}/prime/{jobId}"
        params = None
        data = await self._http.get(path, params=params)
        return ImportJob.model_validate(data)
