# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Process tag."""

from __future__ import annotations

from typing import Any
from sonzai._generated.models import (
    ProcessInputBody,
    ProcessResponse,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _ProcessBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Process(_ProcessBase):
    def process_messages(
        self,
        agent_id: str,
        *,
        instance_id: str | None = None,
        messages: list[Any],
        model: str | None = None,
        provider: str | None = None,
        session_id: str | None = None,
        user_id: str,
    ) -> ProcessResponse:
        """Process an external conversation transcript"""
        path = f"/api/v1/agents/{agent_id}/process"
        params = None
        _raw: dict[str, Any] = {}
        if instance_id is not None:
            _raw["instanceId"] = instance_id
        if messages is not None:
            _raw["messages"] = messages
        if model is not None:
            _raw["model"] = model
        if provider is not None:
            _raw["provider"] = provider
        if session_id is not None:
            _raw["sessionId"] = session_id
        if user_id is not None:
            _raw["userId"] = user_id
        body = encode_body(ProcessInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return ProcessResponse.model_validate(data)


class AsyncProcess(_ProcessBase):
    async def process_messages(
        self,
        agent_id: str,
        *,
        instance_id: str | None = None,
        messages: list[Any],
        model: str | None = None,
        provider: str | None = None,
        session_id: str | None = None,
        user_id: str,
    ) -> ProcessResponse:
        """Process an external conversation transcript"""
        path = f"/api/v1/agents/{agent_id}/process"
        params = None
        _raw: dict[str, Any] = {}
        if instance_id is not None:
            _raw["instanceId"] = instance_id
        if messages is not None:
            _raw["messages"] = messages
        if model is not None:
            _raw["model"] = model
        if provider is not None:
            _raw["provider"] = provider
        if session_id is not None:
            _raw["sessionId"] = session_id
        if user_id is not None:
            _raw["userId"] = user_id
        body = encode_body(ProcessInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return ProcessResponse.model_validate(data)
