# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Projects tag."""

from __future__ import annotations

from typing import Any
from sonzai._generated.models import (
    CreateProjectInputBody,
    DeleteProjectOutputBody,
    Project,
    UpdateProjectInputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _ProjectsBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Projects(_ProjectsBase):
    def list_projects(
        self,
        *,
        limit: int | None = 50,
        offset: int | None = 0,
    ) -> Any:
        """List projects"""
        path = f"/api/v1/projects"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = self._http.get(path, params=params)
        return data

    def create_project(
        self,
        *,
        environment: str | None = None,
        name: str,
    ) -> Project:
        """Create a project"""
        path = f"/api/v1/projects"
        params = None
        _raw: dict[str, Any] = {}
        if environment is not None:
            _raw["environment"] = environment
        if name is not None:
            _raw["name"] = name
        body = encode_body(CreateProjectInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return Project.model_validate(data)

    def delete_project(
        self,
        project_id: str,
    ) -> DeleteProjectOutputBody:
        """Delete a project"""
        path = f"/api/v1/projects/{project_id}"
        params = None
        data = self._http.delete(path, params=params)
        return DeleteProjectOutputBody.model_validate(data)

    def get_project(
        self,
        project_id: str,
    ) -> Project:
        """Get a project"""
        path = f"/api/v1/projects/{project_id}"
        params = None
        data = self._http.get(path, params=params)
        return Project.model_validate(data)

    def update_project(
        self,
        project_id: str,
        *,
        environment: str | None = None,
        game_name: str | None = None,
        name: str | None = None,
    ) -> Project:
        """Update a project"""
        path = f"/api/v1/projects/{project_id}"
        params = None
        _raw: dict[str, Any] = {}
        if environment is not None:
            _raw["environment"] = environment
        if game_name is not None:
            _raw["game_name"] = game_name
        if name is not None:
            _raw["name"] = name
        body = encode_body(UpdateProjectInputBody, _raw)
        data = self._http.put(path, params=params, json_data=body)
        return Project.model_validate(data)


class AsyncProjects(_ProjectsBase):
    async def list_projects(
        self,
        *,
        limit: int | None = 50,
        offset: int | None = 0,
    ) -> Any:
        """List projects"""
        path = f"/api/v1/projects"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if offset is not None:
            params["offset"] = offset
        data = await self._http.get(path, params=params)
        return data

    async def create_project(
        self,
        *,
        environment: str | None = None,
        name: str,
    ) -> Project:
        """Create a project"""
        path = f"/api/v1/projects"
        params = None
        _raw: dict[str, Any] = {}
        if environment is not None:
            _raw["environment"] = environment
        if name is not None:
            _raw["name"] = name
        body = encode_body(CreateProjectInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return Project.model_validate(data)

    async def delete_project(
        self,
        project_id: str,
    ) -> DeleteProjectOutputBody:
        """Delete a project"""
        path = f"/api/v1/projects/{project_id}"
        params = None
        data = await self._http.delete(path, params=params)
        return DeleteProjectOutputBody.model_validate(data)

    async def get_project(
        self,
        project_id: str,
    ) -> Project:
        """Get a project"""
        path = f"/api/v1/projects/{project_id}"
        params = None
        data = await self._http.get(path, params=params)
        return Project.model_validate(data)

    async def update_project(
        self,
        project_id: str,
        *,
        environment: str | None = None,
        game_name: str | None = None,
        name: str | None = None,
    ) -> Project:
        """Update a project"""
        path = f"/api/v1/projects/{project_id}"
        params = None
        _raw: dict[str, Any] = {}
        if environment is not None:
            _raw["environment"] = environment
        if game_name is not None:
            _raw["game_name"] = game_name
        if name is not None:
            _raw["name"] = name
        body = encode_body(UpdateProjectInputBody, _raw)
        data = await self._http.put(path, params=params, json_data=body)
        return Project.model_validate(data)
