# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Routing tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    ClassifyContactRequest,
    Config,
    ListPermanentRoutesResponse,
    OverridePermanentRouteRequest,
    PermanentRouteBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _RoutingBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Routing(_RoutingBase):
    def list_permanent_routes(
        self,
        project_id: str,
    ) -> ListPermanentRoutesResponse:
        """List permanently routed contacts"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/permanent-routes"
        params = None
        data = self._http.get(path, params=params)
        return ListPermanentRoutesResponse.model_validate(data)

    def classify_contact(
        self,
        project_id: str,
        *,
        agent_id: str,
        contact_name: str,
        tier: str,
        user_id: str,
    ) -> PermanentRouteBody:
        """Classify a contact and set permanent route"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/permanent-routes"
        params = None
        _raw: dict[str, Any] = {}
        if agent_id is not None:
            _raw["agent_id"] = agent_id
        if contact_name is not None:
            _raw["contact_name"] = contact_name
        if tier is not None:
            _raw["tier"] = tier
        if user_id is not None:
            _raw["user_id"] = user_id
        body = encode_body(ClassifyContactRequest, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return PermanentRouteBody.model_validate(data)

    def override_permanent_route(
        self,
        project_id: str,
        user_id: str,
        *,
        agent_id: str,
    ) -> PermanentRouteBody:
        """Override a contact's permanent route"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/permanent-routes/{quote(user_id, safe='')}/override"
        params = None
        _raw: dict[str, Any] = {}
        if agent_id is not None:
            _raw["agent_id"] = agent_id
        body = encode_body(OverridePermanentRouteRequest, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return PermanentRouteBody.model_validate(data)

    def get_routing_config(
        self,
        project_id: str,
    ) -> Config:
        """Get routing configuration for a project"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/routing-config"
        params = None
        data = self._http.get(path, params=params)
        return Config.model_validate(data)

    def put_routing_config(
        self,
        project_id: str,
        *,
        channel_bindings: list[Any],
        guide_agent: str,
        handoffs: list[Any],
        tiers: list[Any],
    ) -> Config:
        """Update routing configuration for a project"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/routing-config"
        params = None
        _raw: dict[str, Any] = {}
        if channel_bindings is not None:
            _raw["channel_bindings"] = channel_bindings
        if guide_agent is not None:
            _raw["guide_agent"] = guide_agent
        if handoffs is not None:
            _raw["handoffs"] = handoffs
        if tiers is not None:
            _raw["tiers"] = tiers
        body = encode_body(Config, _raw)
        data = self._http.put(path, params=params, json_data=body)
        return Config.model_validate(data)


class AsyncRouting(_RoutingBase):
    async def list_permanent_routes(
        self,
        project_id: str,
    ) -> ListPermanentRoutesResponse:
        """List permanently routed contacts"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/permanent-routes"
        params = None
        data = await self._http.get(path, params=params)
        return ListPermanentRoutesResponse.model_validate(data)

    async def classify_contact(
        self,
        project_id: str,
        *,
        agent_id: str,
        contact_name: str,
        tier: str,
        user_id: str,
    ) -> PermanentRouteBody:
        """Classify a contact and set permanent route"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/permanent-routes"
        params = None
        _raw: dict[str, Any] = {}
        if agent_id is not None:
            _raw["agent_id"] = agent_id
        if contact_name is not None:
            _raw["contact_name"] = contact_name
        if tier is not None:
            _raw["tier"] = tier
        if user_id is not None:
            _raw["user_id"] = user_id
        body = encode_body(ClassifyContactRequest, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return PermanentRouteBody.model_validate(data)

    async def override_permanent_route(
        self,
        project_id: str,
        user_id: str,
        *,
        agent_id: str,
    ) -> PermanentRouteBody:
        """Override a contact's permanent route"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/permanent-routes/{quote(user_id, safe='')}/override"
        params = None
        _raw: dict[str, Any] = {}
        if agent_id is not None:
            _raw["agent_id"] = agent_id
        body = encode_body(OverridePermanentRouteRequest, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return PermanentRouteBody.model_validate(data)

    async def get_routing_config(
        self,
        project_id: str,
    ) -> Config:
        """Get routing configuration for a project"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/routing-config"
        params = None
        data = await self._http.get(path, params=params)
        return Config.model_validate(data)

    async def put_routing_config(
        self,
        project_id: str,
        *,
        channel_bindings: list[Any],
        guide_agent: str,
        handoffs: list[Any],
        tiers: list[Any],
    ) -> Config:
        """Update routing configuration for a project"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/routing-config"
        params = None
        _raw: dict[str, Any] = {}
        if channel_bindings is not None:
            _raw["channel_bindings"] = channel_bindings
        if guide_agent is not None:
            _raw["guide_agent"] = guide_agent
        if handoffs is not None:
            _raw["handoffs"] = handoffs
        if tiers is not None:
            _raw["tiers"] = tiers
        body = encode_body(Config, _raw)
        data = await self._http.put(path, params=params, json_data=body)
        return Config.model_validate(data)
