# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Schedules tag."""

from __future__ import annotations

from typing import Any

from sonzai._generated.models import (
    CreateScheduleInputBody,
    CreateScheduleOutputBody,
    ListSchedulesOutputBody,
    PatchScheduleInputBody,
    ScheduleDTO,
    UpcomingScheduleOutputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _SchedulesBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Schedules(_SchedulesBase):
    def list_schedules(
        self,
        agent_id: str,
        user_id: str,
    ) -> ListSchedulesOutputBody:
        """List all schedules for a (agent, user) pair."""
        path = f"/agents/{agentId}/users/{userId}/schedules"
        params = None
        data = self._http.get(path, params=params)
        return ListSchedulesOutputBody.model_validate(data)
    def create_schedule(
        self,
        agent_id: str,
        user_id: str,
        **body_fields: Any,
    ) -> CreateScheduleOutputBody:
        """Create a recurring schedule for a user."""
        path = f"/agents/{agentId}/users/{userId}/schedules"
        params = None
        body = encode_body(CreateScheduleInputBody, body_fields)
        data = self._http.post(path, params=params, body=body)
        return CreateScheduleOutputBody.model_validate(data)
    def delete_schedule(
        self,
        agent_id: str,
        user_id: str,
        schedule_id: str,
    ) -> Any:
        """Delete a schedule. Idempotent — missing IDs return 204."""
        path = f"/agents/{agentId}/users/{userId}/schedules/{scheduleId}"
        params = None
        data = self._http.delete(path, params=params)
        return data
    def get_schedule(
        self,
        agent_id: str,
        user_id: str,
        schedule_id: str,
    ) -> ScheduleDTO:
        """Fetch a single schedule by ID."""
        path = f"/agents/{agentId}/users/{userId}/schedules/{scheduleId}"
        params = None
        data = self._http.get(path, params=params)
        return ScheduleDTO.model_validate(data)
    def patch_schedule(
        self,
        agent_id: str,
        user_id: str,
        schedule_id: str,
        **body_fields: Any,
    ) -> ScheduleDTO:
        """Partially update a schedule. Recomputes next_fire_at only when cadence/active_window/starts_at change."""
        path = f"/agents/{agentId}/users/{userId}/schedules/{scheduleId}"
        params = None
        body = encode_body(PatchScheduleInputBody, body_fields)
        data = self._http.patch(path, params=params, body=body)
        return ScheduleDTO.model_validate(data)
    def upcoming_schedule(
        self,
        agent_id: str,
        user_id: str,
        schedule_id: str,
        *,
        limit: int | None = 10,
    ) -> UpcomingScheduleOutputBody:
        """Preview the next N allowed fire times (honors active_window). Does not mutate state."""
        path = f"/agents/{agentId}/users/{userId}/schedules/{scheduleId}/upcoming"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return UpcomingScheduleOutputBody.model_validate(data)


class AsyncSchedules(_SchedulesBase):
    async def list_schedules(
        self,
        agent_id: str,
        user_id: str,
    ) -> ListSchedulesOutputBody:
        """List all schedules for a (agent, user) pair."""
        path = f"/agents/{agentId}/users/{userId}/schedules"
        params = None
        data = await self._http.get(path, params=params)
        return ListSchedulesOutputBody.model_validate(data)
    async def create_schedule(
        self,
        agent_id: str,
        user_id: str,
        **body_fields: Any,
    ) -> CreateScheduleOutputBody:
        """Create a recurring schedule for a user."""
        path = f"/agents/{agentId}/users/{userId}/schedules"
        params = None
        body = encode_body(CreateScheduleInputBody, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return CreateScheduleOutputBody.model_validate(data)
    async def delete_schedule(
        self,
        agent_id: str,
        user_id: str,
        schedule_id: str,
    ) -> Any:
        """Delete a schedule. Idempotent — missing IDs return 204."""
        path = f"/agents/{agentId}/users/{userId}/schedules/{scheduleId}"
        params = None
        data = await self._http.delete(path, params=params)
        return data
    async def get_schedule(
        self,
        agent_id: str,
        user_id: str,
        schedule_id: str,
    ) -> ScheduleDTO:
        """Fetch a single schedule by ID."""
        path = f"/agents/{agentId}/users/{userId}/schedules/{scheduleId}"
        params = None
        data = await self._http.get(path, params=params)
        return ScheduleDTO.model_validate(data)
    async def patch_schedule(
        self,
        agent_id: str,
        user_id: str,
        schedule_id: str,
        **body_fields: Any,
    ) -> ScheduleDTO:
        """Partially update a schedule. Recomputes next_fire_at only when cadence/active_window/starts_at change."""
        path = f"/agents/{agentId}/users/{userId}/schedules/{scheduleId}"
        params = None
        body = encode_body(PatchScheduleInputBody, body_fields)
        data = await self._http.patch(path, params=params, body=body)
        return ScheduleDTO.model_validate(data)
    async def upcoming_schedule(
        self,
        agent_id: str,
        user_id: str,
        schedule_id: str,
        *,
        limit: int | None = 10,
    ) -> UpcomingScheduleOutputBody:
        """Preview the next N allowed fire times (honors active_window). Does not mutate state."""
        path = f"/agents/{agentId}/users/{userId}/schedules/{scheduleId}/upcoming"
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return UpcomingScheduleOutputBody.model_validate(data)
