# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Support tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    AddCommentRequest,
    CreateTicketRequest,
    SupportTicket,
    SupportTicketComment,
    TicketDetailResponse,
    TicketListResponse,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _SupportBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Support(_SupportBase):
    def list_my_tickets(
        self,
        *,
        page_size: int | None = None,
        cursor: str | None = None,
        status: str | None = None,
        type: str | None = None,
    ) -> TicketListResponse:
        """List my support tickets"""
        path = f"/api/v1/support/tickets"
        params: dict[str, Any] = {}
        if page_size is not None:
            params["page_size"] = page_size
        if cursor is not None:
            params["cursor"] = cursor
        if status is not None:
            params["status"] = status
        if type is not None:
            params["type"] = type
        data = self._http.get(path, params=params)
        return TicketListResponse.model_validate(data)

    def create_support_ticket(
        self,
        *,
        description: str,
        priority: str | None = None,
        title: str,
        type: str,
    ) -> SupportTicket:
        """Create a support ticket"""
        path = f"/api/v1/support/tickets"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if priority is not None:
            _raw["priority"] = priority
        if title is not None:
            _raw["title"] = title
        if type is not None:
            _raw["type"] = type
        body = encode_body(CreateTicketRequest, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return SupportTicket.model_validate(data)

    def get_support_ticket(
        self,
        ticket_id: str,
    ) -> TicketDetailResponse:
        """Get a support ticket with comments"""
        path = f"/api/v1/support/tickets/{quote(ticket_id, safe='')}"
        params = None
        data = self._http.get(path, params=params)
        return TicketDetailResponse.model_validate(data)

    def close_support_ticket(
        self,
        ticket_id: str,
    ) -> SupportTicket:
        """Close a support ticket (user)"""
        path = f"/api/v1/support/tickets/{quote(ticket_id, safe='')}/close"
        params = None
        data = self._http.post(path, params=params)
        return SupportTicket.model_validate(data)

    def add_support_ticket_comment(
        self,
        ticket_id: str,
        *,
        content: str,
        is_internal: bool | None = None,
    ) -> SupportTicketComment:
        """Add a comment to a support ticket"""
        path = f"/api/v1/support/tickets/{quote(ticket_id, safe='')}/comments"
        params = None
        _raw: dict[str, Any] = {}
        if content is not None:
            _raw["content"] = content
        if is_internal is not None:
            _raw["is_internal"] = is_internal
        body = encode_body(AddCommentRequest, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return SupportTicketComment.model_validate(data)


class AsyncSupport(_SupportBase):
    async def list_my_tickets(
        self,
        *,
        page_size: int | None = None,
        cursor: str | None = None,
        status: str | None = None,
        type: str | None = None,
    ) -> TicketListResponse:
        """List my support tickets"""
        path = f"/api/v1/support/tickets"
        params: dict[str, Any] = {}
        if page_size is not None:
            params["page_size"] = page_size
        if cursor is not None:
            params["cursor"] = cursor
        if status is not None:
            params["status"] = status
        if type is not None:
            params["type"] = type
        data = await self._http.get(path, params=params)
        return TicketListResponse.model_validate(data)

    async def create_support_ticket(
        self,
        *,
        description: str,
        priority: str | None = None,
        title: str,
        type: str,
    ) -> SupportTicket:
        """Create a support ticket"""
        path = f"/api/v1/support/tickets"
        params = None
        _raw: dict[str, Any] = {}
        if description is not None:
            _raw["description"] = description
        if priority is not None:
            _raw["priority"] = priority
        if title is not None:
            _raw["title"] = title
        if type is not None:
            _raw["type"] = type
        body = encode_body(CreateTicketRequest, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return SupportTicket.model_validate(data)

    async def get_support_ticket(
        self,
        ticket_id: str,
    ) -> TicketDetailResponse:
        """Get a support ticket with comments"""
        path = f"/api/v1/support/tickets/{quote(ticket_id, safe='')}"
        params = None
        data = await self._http.get(path, params=params)
        return TicketDetailResponse.model_validate(data)

    async def close_support_ticket(
        self,
        ticket_id: str,
    ) -> SupportTicket:
        """Close a support ticket (user)"""
        path = f"/api/v1/support/tickets/{quote(ticket_id, safe='')}/close"
        params = None
        data = await self._http.post(path, params=params)
        return SupportTicket.model_validate(data)

    async def add_support_ticket_comment(
        self,
        ticket_id: str,
        *,
        content: str,
        is_internal: bool | None = None,
    ) -> SupportTicketComment:
        """Add a comment to a support ticket"""
        path = f"/api/v1/support/tickets/{quote(ticket_id, safe='')}/comments"
        params = None
        _raw: dict[str, Any] = {}
        if content is not None:
            _raw["content"] = content
        if is_internal is not None:
            _raw["is_internal"] = is_internal
        body = encode_body(AddCommentRequest, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return SupportTicketComment.model_validate(data)
