# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the TenantHost tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    CreateTenantDomainRequest,
    DomainBody,
    ListTenantDomainsResponse,
    ManifestVersionOutputBody,
    WorkspaceSessionOutputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _TenantHostBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class TenantHost(_TenantHostBase):
    def list_tenant_domains(
        self,
        id: str,
    ) -> ListTenantDomainsResponse:
        """List a tenant's hostnames"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/domains"
        params = None
        data = self._http.get(path, params=params)
        return ListTenantDomainsResponse.model_validate(data)

    def create_tenant_domain(
        self,
        id: str,
        *,
        domain: str | None = None,
        domain_type: str,
        is_primary: bool | None = None,
        subdomain: str | None = None,
    ) -> DomainBody:
        """Claim a hostname for a tenant"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/domains"
        params = None
        _raw: dict[str, Any] = {}
        if domain is not None:
            _raw["domain"] = domain
        if domain_type is not None:
            _raw["domain_type"] = domain_type
        if is_primary is not None:
            _raw["is_primary"] = is_primary
        if subdomain is not None:
            _raw["subdomain"] = subdomain
        body = encode_body(CreateTenantDomainRequest, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return DomainBody.model_validate(data)

    def delete_tenant_domain(
        self,
        id: str,
        domain: str,
    ) -> Any:
        """Remove a tenant hostname"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/domains/{quote(domain, safe='')}"
        params = None
        data = self._http.delete(path, params=params)
        return data

    def verify_tenant_domain(
        self,
        id: str,
        domain: str,
    ) -> DomainBody:
        """Verify custom-domain ownership via TXT record"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/domains/{quote(domain, safe='')}/verify"
        params = None
        data = self._http.post(path, params=params)
        return DomainBody.model_validate(data)

    def get_tenant_manifest(
        self,
        id: str,
    ) -> ManifestVersionOutputBody:
        """Get a tenant's manifest"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/manifest"
        params = None
        data = self._http.get(path, params=params)
        return ManifestVersionOutputBody.model_validate(data)

    def put_tenant_manifest(
        self,
        id: str,
    ) -> ManifestVersionOutputBody:
        """Create or update a tenant's manifest"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/manifest"
        params = None
        data = self._http.put(path, params=params)
        return ManifestVersionOutputBody.model_validate(data)

    def mint_workspace_session(
        self,
        id: str,
    ) -> WorkspaceSessionOutputBody:
        """Mint a short-lived workspace handoff session"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/workspace-session"
        params = None
        data = self._http.post(path, params=params)
        return WorkspaceSessionOutputBody.model_validate(data)


class AsyncTenantHost(_TenantHostBase):
    async def list_tenant_domains(
        self,
        id: str,
    ) -> ListTenantDomainsResponse:
        """List a tenant's hostnames"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/domains"
        params = None
        data = await self._http.get(path, params=params)
        return ListTenantDomainsResponse.model_validate(data)

    async def create_tenant_domain(
        self,
        id: str,
        *,
        domain: str | None = None,
        domain_type: str,
        is_primary: bool | None = None,
        subdomain: str | None = None,
    ) -> DomainBody:
        """Claim a hostname for a tenant"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/domains"
        params = None
        _raw: dict[str, Any] = {}
        if domain is not None:
            _raw["domain"] = domain
        if domain_type is not None:
            _raw["domain_type"] = domain_type
        if is_primary is not None:
            _raw["is_primary"] = is_primary
        if subdomain is not None:
            _raw["subdomain"] = subdomain
        body = encode_body(CreateTenantDomainRequest, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return DomainBody.model_validate(data)

    async def delete_tenant_domain(
        self,
        id: str,
        domain: str,
    ) -> Any:
        """Remove a tenant hostname"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/domains/{quote(domain, safe='')}"
        params = None
        data = await self._http.delete(path, params=params)
        return data

    async def verify_tenant_domain(
        self,
        id: str,
        domain: str,
    ) -> DomainBody:
        """Verify custom-domain ownership via TXT record"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/domains/{quote(domain, safe='')}/verify"
        params = None
        data = await self._http.post(path, params=params)
        return DomainBody.model_validate(data)

    async def get_tenant_manifest(
        self,
        id: str,
    ) -> ManifestVersionOutputBody:
        """Get a tenant's manifest"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/manifest"
        params = None
        data = await self._http.get(path, params=params)
        return ManifestVersionOutputBody.model_validate(data)

    async def put_tenant_manifest(
        self,
        id: str,
    ) -> ManifestVersionOutputBody:
        """Create or update a tenant's manifest"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/manifest"
        params = None
        data = await self._http.put(path, params=params)
        return ManifestVersionOutputBody.model_validate(data)

    async def mint_workspace_session(
        self,
        id: str,
    ) -> WorkspaceSessionOutputBody:
        """Mint a short-lived workspace handoff session"""
        path = f"/api/v1/tenants/{quote(id, safe='')}/workspace-session"
        params = None
        data = await self._http.post(path, params=params)
        return WorkspaceSessionOutputBody.model_validate(data)
