# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Tools tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    AgentKBSearchInputBody,
    GetToolSchemasOutputBody,
    KbSearchResponse,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _ToolsBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Tools(_ToolsBase):
    def agent_kb_search_get(
        self,
        agent_id: str,
        *,
        q: str,
        limit: int | None = None,
    ) -> KbSearchResponse:
        """Search agent knowledge base (GET)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/tools/kb-search"
        params: dict[str, Any] = {}
        if q is not None:
            params["q"] = q
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return KbSearchResponse.model_validate(data)

    def agent_kb_search(
        self,
        agent_id: str,
        *,
        limit: int | None = None,
        query: str,
    ) -> KbSearchResponse:
        """Search agent knowledge base"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/tools/kb-search"
        params = None
        _raw: dict[str, Any] = {}
        if limit is not None:
            _raw["limit"] = limit
        if query is not None:
            _raw["query"] = query
        body = encode_body(AgentKBSearchInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return KbSearchResponse.model_validate(data)

    def get_tool_schemas(
        self,
        agent_id: str,
    ) -> GetToolSchemasOutputBody:
        """Get available tool schemas"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/tools/schemas"
        params = None
        data = self._http.get(path, params=params)
        return GetToolSchemasOutputBody.model_validate(data)


class AsyncTools(_ToolsBase):
    async def agent_kb_search_get(
        self,
        agent_id: str,
        *,
        q: str,
        limit: int | None = None,
    ) -> KbSearchResponse:
        """Search agent knowledge base (GET)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/tools/kb-search"
        params: dict[str, Any] = {}
        if q is not None:
            params["q"] = q
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return KbSearchResponse.model_validate(data)

    async def agent_kb_search(
        self,
        agent_id: str,
        *,
        limit: int | None = None,
        query: str,
    ) -> KbSearchResponse:
        """Search agent knowledge base"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/tools/kb-search"
        params = None
        _raw: dict[str, Any] = {}
        if limit is not None:
            _raw["limit"] = limit
        if query is not None:
            _raw["query"] = query
        body = encode_body(AgentKBSearchInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return KbSearchResponse.model_validate(data)

    async def get_tool_schemas(
        self,
        agent_id: str,
    ) -> GetToolSchemasOutputBody:
        """Get available tool schemas"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/tools/schemas"
        params = None
        data = await self._http.get(path, params=params)
        return GetToolSchemasOutputBody.model_validate(data)
