# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Users tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    MeResponse,
    UserEntry,
    UsersResponse,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _UsersBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Users(_UsersBase):
    def list_users(
        self,
        agent_id: str,
        *,
        sort_by: str | None = None,
        sort_order: str | None = None,
        limit: int = 100,
    ) -> Page[UserEntry]:
        """List users for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order
        return Page(
            fetcher=lambda p: self._http.get(path, params=p),
            params=params,
            item_key="users",
            item_parser=UserEntry.model_validate,
            mode="offset",
            total_key="total",
        )
    def get_my_org(
        self,
    ) -> MeResponse:
        """Get current user with organizations"""
        path = f"/api/v1/me"
        params = None
        data = self._http.get(path, params=params)
        return MeResponse.model_validate(data)


class AsyncUsers(_UsersBase):
    async def list_users(
        self,
        agent_id: str,
        *,
        sort_by: str | None = None,
        sort_order: str | None = None,
        limit: int = 100,
    ) -> AsyncPage[UserEntry]:
        """List users for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order

        async def fetcher(p: dict[str, Any]) -> dict[str, Any]:
            return await self._http.get(path, params=p)

        return AsyncPage(
            fetcher=fetcher,
            params=params,
            item_key="users",
            item_parser=UserEntry.model_validate,
            mode="offset",
            total_key="total",
        )
    async def get_my_org(
        self,
    ) -> MeResponse:
        """Get current user with organizations"""
        path = f"/api/v1/me"
        params = None
        data = await self._http.get(path, params=params)
        return MeResponse.model_validate(data)
