# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Users tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    MeResponse,
    UsersResponse,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _UsersBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Users(_UsersBase):
    def list_users(
        self,
        agent_id: str,
        *,
        page_size: int | None = None,
        cursor: str | None = None,
    ) -> UsersResponse:
        """List users for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users"
        params: dict[str, Any] = {}
        if page_size is not None:
            params["page_size"] = page_size
        if cursor is not None:
            params["cursor"] = cursor
        data = self._http.get(path, params=params)
        return UsersResponse.model_validate(data)

    def get_my_org(
        self,
    ) -> MeResponse:
        """Get current user with organizations"""
        path = f"/api/v1/me"
        params = None
        data = self._http.get(path, params=params)
        return MeResponse.model_validate(data)


class AsyncUsers(_UsersBase):
    async def list_users(
        self,
        agent_id: str,
        *,
        page_size: int | None = None,
        cursor: str | None = None,
    ) -> UsersResponse:
        """List users for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/users"
        params: dict[str, Any] = {}
        if page_size is not None:
            params["page_size"] = page_size
        if cursor is not None:
            params["cursor"] = cursor
        data = await self._http.get(path, params=params)
        return UsersResponse.model_validate(data)

    async def get_my_org(
        self,
    ) -> MeResponse:
        """Get current user with organizations"""
        path = f"/api/v1/me"
        params = None
        data = await self._http.get(path, params=params)
        return MeResponse.model_validate(data)
