# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the UserPersonas tag."""

from __future__ import annotations

from typing import Any

from sonzai._generated.models import (
    CreateUserPersonaInputBody,
    DeleteUserPersonaOutputBody,
    ListUserPersonasOutputBody,
    UpdateUserPersonaInputBody,
    UserPersonaRecord,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _UserPersonasBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class UserPersonas(_UserPersonasBase):
    def list_user_personas(
        self,
    ) -> ListUserPersonasOutputBody:
        """List user personas"""
        path = f"/user-personas"
        params = None
        data = self._http.get(path, params=params)
        return ListUserPersonasOutputBody.model_validate(data)
    def create_user_persona(
        self,
        **body_fields: Any,
    ) -> UserPersonaRecord:
        """Create a user persona"""
        path = f"/user-personas"
        params = None
        body = encode_body(CreateUserPersonaInputBody, body_fields)
        data = self._http.post(path, params=params, body=body)
        return UserPersonaRecord.model_validate(data)
    def delete_user_persona(
        self,
        persona_id: str,
    ) -> DeleteUserPersonaOutputBody:
        """Delete a user persona"""
        path = f"/user-personas/{personaId}"
        params = None
        data = self._http.delete(path, params=params)
        return DeleteUserPersonaOutputBody.model_validate(data)
    def get_user_persona(
        self,
        persona_id: str,
    ) -> UserPersonaRecord:
        """Get a user persona"""
        path = f"/user-personas/{personaId}"
        params = None
        data = self._http.get(path, params=params)
        return UserPersonaRecord.model_validate(data)
    def update_user_persona(
        self,
        persona_id: str,
        **body_fields: Any,
    ) -> UserPersonaRecord:
        """Update a user persona"""
        path = f"/user-personas/{personaId}"
        params = None
        body = encode_body(UpdateUserPersonaInputBody, body_fields)
        data = self._http.put(path, params=params, body=body)
        return UserPersonaRecord.model_validate(data)


class AsyncUserPersonas(_UserPersonasBase):
    async def list_user_personas(
        self,
    ) -> ListUserPersonasOutputBody:
        """List user personas"""
        path = f"/user-personas"
        params = None
        data = await self._http.get(path, params=params)
        return ListUserPersonasOutputBody.model_validate(data)
    async def create_user_persona(
        self,
        **body_fields: Any,
    ) -> UserPersonaRecord:
        """Create a user persona"""
        path = f"/user-personas"
        params = None
        body = encode_body(CreateUserPersonaInputBody, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return UserPersonaRecord.model_validate(data)
    async def delete_user_persona(
        self,
        persona_id: str,
    ) -> DeleteUserPersonaOutputBody:
        """Delete a user persona"""
        path = f"/user-personas/{personaId}"
        params = None
        data = await self._http.delete(path, params=params)
        return DeleteUserPersonaOutputBody.model_validate(data)
    async def get_user_persona(
        self,
        persona_id: str,
    ) -> UserPersonaRecord:
        """Get a user persona"""
        path = f"/user-personas/{personaId}"
        params = None
        data = await self._http.get(path, params=params)
        return UserPersonaRecord.model_validate(data)
    async def update_user_persona(
        self,
        persona_id: str,
        **body_fields: Any,
    ) -> UserPersonaRecord:
        """Update a user persona"""
        path = f"/user-personas/{personaId}"
        params = None
        body = encode_body(UpdateUserPersonaInputBody, body_fields)
        data = await self._http.put(path, params=params, body=body)
        return UserPersonaRecord.model_validate(data)
