# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Voice tag."""

from __future__ import annotations

from typing import Any

from sonzai._generated.models import (
    ListVoicesResponse,
    SpeechToTextInputBody,
    TextToSpeechInputBody,
    VoiceLiveWSTokenInputBody,
    VoiceLiveWSTokenOutputBody,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _VoiceBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Voice(_VoiceBase):
    def get_voice_live_ws_token(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> VoiceLiveWSTokenOutputBody:
        """Get a voice live WebSocket token"""
        path = f"/agents/{agentId}/voice/live-ws-token"
        params = None
        body = encode_body(VoiceLiveWSTokenInputBody, body_fields)
        data = self._http.post(path, params=params, body=body)
        return VoiceLiveWSTokenOutputBody.model_validate(data)
    def speech_to_text(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> Any:
        """Convert speech to text"""
        path = f"/agents/{agentId}/voice/stt"
        params = None
        body = encode_body(SpeechToTextInputBody, body_fields)
        data = self._http.post(path, params=params, body=body)
        return data
    def text_to_speech(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> Any:
        """Convert text to speech"""
        path = f"/agents/{agentId}/voice/tts"
        params = None
        body = encode_body(TextToSpeechInputBody, body_fields)
        data = self._http.post(path, params=params, body=body)
        return data
    def list_voices(
        self,
        *,
        gender: str | None = None,
    ) -> ListVoicesResponse:
        """List available voices"""
        path = f"/voices"
        params: dict[str, Any] = {}
        if gender is not None:
            params["gender"] = gender
        data = self._http.get(path, params=params)
        return ListVoicesResponse.model_validate(data)


class AsyncVoice(_VoiceBase):
    async def get_voice_live_ws_token(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> VoiceLiveWSTokenOutputBody:
        """Get a voice live WebSocket token"""
        path = f"/agents/{agentId}/voice/live-ws-token"
        params = None
        body = encode_body(VoiceLiveWSTokenInputBody, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return VoiceLiveWSTokenOutputBody.model_validate(data)
    async def speech_to_text(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> Any:
        """Convert speech to text"""
        path = f"/agents/{agentId}/voice/stt"
        params = None
        body = encode_body(SpeechToTextInputBody, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return data
    async def text_to_speech(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> Any:
        """Convert text to speech"""
        path = f"/agents/{agentId}/voice/tts"
        params = None
        body = encode_body(TextToSpeechInputBody, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return data
    async def list_voices(
        self,
        *,
        gender: str | None = None,
    ) -> ListVoicesResponse:
        """List available voices"""
        path = f"/voices"
        params: dict[str, Any] = {}
        if gender is not None:
            params["gender"] = gender
        data = await self._http.get(path, params=params)
        return ListVoicesResponse.model_validate(data)
