# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Wakeups tag."""

from __future__ import annotations

from typing import Any
from sonzai._generated.models import (
    ScheduleWakeupInputBody,
    ScheduleWakeupOutputBody,
    WakeupsResponse,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _WakeupsBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Wakeups(_WakeupsBase):
    def list_wakeups(
        self,
        agent_id: str,
        *,
        status: str | None = None,
        limit: int | None = 50,
    ) -> WakeupsResponse:
        """List scheduled wakeups for an agent"""
        path = f"/agents/{agentId}/wakeups"
        params: dict[str, Any] = {}
        if status is not None:
            params["status"] = status
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return WakeupsResponse.model_validate(data)

    def schedule_wakeup(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> ScheduleWakeupOutputBody:
        """Schedule a wakeup for an agent"""
        path = f"/agents/{agentId}/wakeups"
        params = None
        body = encode_body(ScheduleWakeupInputBody, body_fields)
        data = self._http.post(path, params=params, body=body)
        return ScheduleWakeupOutputBody.model_validate(data)


class AsyncWakeups(_WakeupsBase):
    async def list_wakeups(
        self,
        agent_id: str,
        *,
        status: str | None = None,
        limit: int | None = 50,
    ) -> WakeupsResponse:
        """List scheduled wakeups for an agent"""
        path = f"/agents/{agentId}/wakeups"
        params: dict[str, Any] = {}
        if status is not None:
            params["status"] = status
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return WakeupsResponse.model_validate(data)

    async def schedule_wakeup(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> ScheduleWakeupOutputBody:
        """Schedule a wakeup for an agent"""
        path = f"/agents/{agentId}/wakeups"
        params = None
        body = encode_body(ScheduleWakeupInputBody, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return ScheduleWakeupOutputBody.model_validate(data)
