# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Webhooks tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    ListDeliveryAttemptsOutputBody,
    ListWebhooksOutputBody,
    RotateSigningSecretOutputBody,
    UpsertWebhookForTenantInputBody,
    UpsertWebhookInputBody,
    UpsertWebhookOutputBody,
    WebhookDeliveryAttempt,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _WebhooksBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Webhooks(_WebhooksBase):
    def list_webhooks(
        self,
        project_id: str,
    ) -> ListWebhooksOutputBody:
        """List webhooks for a project"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/webhooks"
        params = None
        data = self._http.get(path, params=params)
        return ListWebhooksOutputBody.model_validate(data)
    def delete_webhook(
        self,
        project_id: str,
        event_type: str,
    ) -> Any:
        """Delete a webhook"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/webhooks/{quote(event_type, safe='')}"
        params = None
        data = self._http.delete(path, params=params)
        return data
    def upsert_webhook(
        self,
        project_id: str,
        event_type: str,
        *,
        auth_header: str | None = None,
        webhook_url: str,
    ) -> UpsertWebhookOutputBody:
        """Register or update a webhook"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/webhooks/{quote(event_type, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if auth_header is not None:
            _raw["auth_header"] = auth_header
        if webhook_url is not None:
            _raw["webhook_url"] = webhook_url
        body = encode_body(UpsertWebhookInputBody, _raw)
        data = self._http.put(path, params=params, json_data=body)
        return UpsertWebhookOutputBody.model_validate(data)
    def list_delivery_attempts(
        self,
        project_id: str,
        event_type: str,
        *,
        limit: int = 100,
    ) -> Page[WebhookDeliveryAttempt]:
        """List webhook delivery attempts"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/webhooks/{quote(event_type, safe='')}/attempts"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        return Page(
            fetcher=lambda p: self._http.get(path, params=p),
            params=params,
            item_key="attempts",
            item_parser=WebhookDeliveryAttempt.model_validate,
            mode="offset",
        )
    def rotate_webhook_signing_secret(
        self,
        project_id: str,
        event_type: str,
    ) -> RotateSigningSecretOutputBody:
        """Rotate webhook signing secret"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/webhooks/{quote(event_type, safe='')}/rotate-secret"
        params = None
        data = self._http.post(path, params=params)
        return RotateSigningSecretOutputBody.model_validate(data)
    def list_webhooks_for_tenant(
        self,
    ) -> ListWebhooksOutputBody:
        """List webhooks for current tenant"""
        path = f"/api/v1/webhooks"
        params = None
        data = self._http.get(path, params=params)
        return ListWebhooksOutputBody.model_validate(data)
    def delete_webhook_for_tenant(
        self,
        event_type: str,
    ) -> Any:
        """Delete a webhook (tenant-scoped)"""
        path = f"/api/v1/webhooks/{quote(event_type, safe='')}"
        params = None
        data = self._http.delete(path, params=params)
        return data
    def upsert_webhook_for_tenant(
        self,
        event_type: str,
        *,
        auth_header: str | None = None,
        webhook_url: str,
    ) -> UpsertWebhookOutputBody:
        """Register or update a webhook (tenant-scoped)"""
        path = f"/api/v1/webhooks/{quote(event_type, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if auth_header is not None:
            _raw["auth_header"] = auth_header
        if webhook_url is not None:
            _raw["webhook_url"] = webhook_url
        body = encode_body(UpsertWebhookForTenantInputBody, _raw)
        data = self._http.put(path, params=params, json_data=body)
        return UpsertWebhookOutputBody.model_validate(data)
    def list_delivery_attempts_for_tenant(
        self,
        event_type: str,
        *,
        limit: int = 100,
    ) -> Page[WebhookDeliveryAttempt]:
        """List webhook delivery attempts (tenant-scoped)"""
        path = f"/api/v1/webhooks/{quote(event_type, safe='')}/attempts"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        return Page(
            fetcher=lambda p: self._http.get(path, params=p),
            params=params,
            item_key="attempts",
            item_parser=WebhookDeliveryAttempt.model_validate,
            mode="offset",
        )
    def rotate_webhook_signing_secret_for_tenant(
        self,
        event_type: str,
    ) -> RotateSigningSecretOutputBody:
        """Rotate webhook signing secret (tenant-scoped)"""
        path = f"/api/v1/webhooks/{quote(event_type, safe='')}/rotate-secret"
        params = None
        data = self._http.post(path, params=params)
        return RotateSigningSecretOutputBody.model_validate(data)


class AsyncWebhooks(_WebhooksBase):
    async def list_webhooks(
        self,
        project_id: str,
    ) -> ListWebhooksOutputBody:
        """List webhooks for a project"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/webhooks"
        params = None
        data = await self._http.get(path, params=params)
        return ListWebhooksOutputBody.model_validate(data)
    async def delete_webhook(
        self,
        project_id: str,
        event_type: str,
    ) -> Any:
        """Delete a webhook"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/webhooks/{quote(event_type, safe='')}"
        params = None
        data = await self._http.delete(path, params=params)
        return data
    async def upsert_webhook(
        self,
        project_id: str,
        event_type: str,
        *,
        auth_header: str | None = None,
        webhook_url: str,
    ) -> UpsertWebhookOutputBody:
        """Register or update a webhook"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/webhooks/{quote(event_type, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if auth_header is not None:
            _raw["auth_header"] = auth_header
        if webhook_url is not None:
            _raw["webhook_url"] = webhook_url
        body = encode_body(UpsertWebhookInputBody, _raw)
        data = await self._http.put(path, params=params, json_data=body)
        return UpsertWebhookOutputBody.model_validate(data)
    async def list_delivery_attempts(
        self,
        project_id: str,
        event_type: str,
        *,
        limit: int = 100,
    ) -> AsyncPage[WebhookDeliveryAttempt]:
        """List webhook delivery attempts"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/webhooks/{quote(event_type, safe='')}/attempts"
        params: dict[str, Any] = {"limit": limit, "offset": 0}

        async def fetcher(p: dict[str, Any]) -> dict[str, Any]:
            return await self._http.get(path, params=p)

        return AsyncPage(
            fetcher=fetcher,
            params=params,
            item_key="attempts",
            item_parser=WebhookDeliveryAttempt.model_validate,
            mode="offset",
        )
    async def rotate_webhook_signing_secret(
        self,
        project_id: str,
        event_type: str,
    ) -> RotateSigningSecretOutputBody:
        """Rotate webhook signing secret"""
        path = f"/api/v1/projects/{quote(project_id, safe='')}/webhooks/{quote(event_type, safe='')}/rotate-secret"
        params = None
        data = await self._http.post(path, params=params)
        return RotateSigningSecretOutputBody.model_validate(data)
    async def list_webhooks_for_tenant(
        self,
    ) -> ListWebhooksOutputBody:
        """List webhooks for current tenant"""
        path = f"/api/v1/webhooks"
        params = None
        data = await self._http.get(path, params=params)
        return ListWebhooksOutputBody.model_validate(data)
    async def delete_webhook_for_tenant(
        self,
        event_type: str,
    ) -> Any:
        """Delete a webhook (tenant-scoped)"""
        path = f"/api/v1/webhooks/{quote(event_type, safe='')}"
        params = None
        data = await self._http.delete(path, params=params)
        return data
    async def upsert_webhook_for_tenant(
        self,
        event_type: str,
        *,
        auth_header: str | None = None,
        webhook_url: str,
    ) -> UpsertWebhookOutputBody:
        """Register or update a webhook (tenant-scoped)"""
        path = f"/api/v1/webhooks/{quote(event_type, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if auth_header is not None:
            _raw["auth_header"] = auth_header
        if webhook_url is not None:
            _raw["webhook_url"] = webhook_url
        body = encode_body(UpsertWebhookForTenantInputBody, _raw)
        data = await self._http.put(path, params=params, json_data=body)
        return UpsertWebhookOutputBody.model_validate(data)
    async def list_delivery_attempts_for_tenant(
        self,
        event_type: str,
        *,
        limit: int = 100,
    ) -> AsyncPage[WebhookDeliveryAttempt]:
        """List webhook delivery attempts (tenant-scoped)"""
        path = f"/api/v1/webhooks/{quote(event_type, safe='')}/attempts"
        params: dict[str, Any] = {"limit": limit, "offset": 0}

        async def fetcher(p: dict[str, Any]) -> dict[str, Any]:
            return await self._http.get(path, params=p)

        return AsyncPage(
            fetcher=fetcher,
            params=params,
            item_key="attempts",
            item_parser=WebhookDeliveryAttempt.model_validate,
            mode="offset",
        )
    async def rotate_webhook_signing_secret_for_tenant(
        self,
        event_type: str,
    ) -> RotateSigningSecretOutputBody:
        """Rotate webhook signing secret (tenant-scoped)"""
        path = f"/api/v1/webhooks/{quote(event_type, safe='')}/rotate-secret"
        params = None
        data = await self._http.post(path, params=params)
        return RotateSigningSecretOutputBody.model_validate(data)
