# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Wisdom tag."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote
from sonzai._generated.models import (
    CreateWisdomAttributedBody,
    CreateWisdomAttributedOutputBody,
    CreateWisdomRelationBody,
    CreateWisdomRelationOutputBody,
    ListWisdomAttributedOutputBody,
    ListWisdomAuditOutputBody,
    ListWisdomRelationsOutputBody,
    ReplaceWisdomAttributedInputBody,
    ReplaceWisdomAttributedOutputBody,
    WisdomImportInputBody,
    WisdomImportResponse,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _WisdomBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Wisdom(_WisdomBase):
    def list_attributed_wisdom(
        self,
        agent_id: str,
    ) -> ListWisdomAttributedOutputBody:
        """List attributed wisdom for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/attributed"
        params = None
        data = self._http.get(path, params=params)
        return ListWisdomAttributedOutputBody.model_validate(data)

    def create_attributed_wisdom(
        self,
        agent_id: str,
        *,
        category: str,
        confidence: float | None = None,
        entity_display_name: str | None = None,
        entity_id: str,
        entity_type: str,
        expires_at: str | None = None,
        observed_at: str | None = None,
        source_ref: str | None = None,
        value: str,
    ) -> CreateWisdomAttributedOutputBody:
        """Create or upsert an attributed wisdom fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/attributed"
        params = None
        _raw: dict[str, Any] = {}
        if category is not None:
            _raw["category"] = category
        if confidence is not None:
            _raw["confidence"] = confidence
        if entity_display_name is not None:
            _raw["entity_display_name"] = entity_display_name
        if entity_id is not None:
            _raw["entity_id"] = entity_id
        if entity_type is not None:
            _raw["entity_type"] = entity_type
        if expires_at is not None:
            _raw["expires_at"] = expires_at
        if observed_at is not None:
            _raw["observed_at"] = observed_at
        if source_ref is not None:
            _raw["source_ref"] = source_ref
        if value is not None:
            _raw["value"] = value
        body = encode_body(CreateWisdomAttributedBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return CreateWisdomAttributedOutputBody.model_validate(data)

    def import_attributed_wisdom(
        self,
        agent_id: str,
        *,
        data: str,
        dry_run: bool | None = None,
        format: str,
    ) -> WisdomImportResponse:
        """Bulk import attributed wisdom facts (JSON or CSV)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/attributed/import"
        params = None
        _raw: dict[str, Any] = {}
        if data is not None:
            _raw["data"] = data
        if dry_run is not None:
            _raw["dry_run"] = dry_run
        if format is not None:
            _raw["format"] = format
        body = encode_body(WisdomImportInputBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return WisdomImportResponse.model_validate(data)

    def list_attributed_wisdom_by_entity(
        self,
        agent_id: str,
        entity_type: str,
        entity_id: str,
    ) -> ListWisdomAttributedOutputBody:
        """List attributed wisdom for one entity"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/attributed/{quote(entity_type, safe='')}/{quote(entity_id, safe='')}"
        params = None
        data = self._http.get(path, params=params)
        return ListWisdomAttributedOutputBody.model_validate(data)

    def delete_attributed_wisdom(
        self,
        agent_id: str,
        entity_type: str,
        entity_id: str,
        category: str,
    ) -> Any:
        """Delete an attributed wisdom fact (idempotent)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/attributed/{quote(entity_type, safe='')}/{quote(entity_id, safe='')}/{quote(category, safe='')}"
        params = None
        data = self._http.delete(path, params=params)
        return data

    def replace_attributed_wisdom(
        self,
        agent_id: str,
        entity_type: str,
        entity_id: str,
        category: str,
        *,
        confidence: float | None = None,
        entity_display_name: str | None = None,
        expires_at: str | None = None,
        observed_at: str | None = None,
        source_ref: str | None = None,
        value: str,
    ) -> ReplaceWisdomAttributedOutputBody:
        """Replace the value of an attributed wisdom fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/attributed/{quote(entity_type, safe='')}/{quote(entity_id, safe='')}/{quote(category, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if confidence is not None:
            _raw["confidence"] = confidence
        if entity_display_name is not None:
            _raw["entity_display_name"] = entity_display_name
        if expires_at is not None:
            _raw["expires_at"] = expires_at
        if observed_at is not None:
            _raw["observed_at"] = observed_at
        if source_ref is not None:
            _raw["source_ref"] = source_ref
        if value is not None:
            _raw["value"] = value
        body = encode_body(ReplaceWisdomAttributedInputBody, _raw)
        data = self._http.put(path, params=params, json_data=body)
        return ReplaceWisdomAttributedOutputBody.model_validate(data)

    def list_attributed_wisdom_audit(
        self,
        agent_id: str,
        *,
        from_: str | None = None,
        to: str | None = None,
        limit: int | None = None,
    ) -> ListWisdomAuditOutputBody:
        """List attributed wisdom disclosure audit entries"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/audit"
        params: dict[str, Any] = {}
        if from_ is not None:
            params["from"] = from_
        if to is not None:
            params["to"] = to
        if limit is not None:
            params["limit"] = limit
        data = self._http.get(path, params=params)
        return ListWisdomAuditOutputBody.model_validate(data)

    def list_attributed_wisdom_relations(
        self,
        agent_id: str,
    ) -> ListWisdomRelationsOutputBody:
        """List attributed wisdom relations for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/relations"
        params = None
        data = self._http.get(path, params=params)
        return ListWisdomRelationsOutputBody.model_validate(data)

    def create_attributed_wisdom_relation(
        self,
        agent_id: str,
        *,
        edge_type: str,
        from_id: str,
        from_type: str,
        metadata: dict[str, Any] | None = None,
        observed_at: str | None = None,
        source_ref: str | None = None,
        to_id: str,
        to_type: str,
    ) -> CreateWisdomRelationOutputBody:
        """Create an attributed wisdom relation"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/relations"
        params = None
        _raw: dict[str, Any] = {}
        if edge_type is not None:
            _raw["edge_type"] = edge_type
        if from_id is not None:
            _raw["from_id"] = from_id
        if from_type is not None:
            _raw["from_type"] = from_type
        if metadata is not None:
            _raw["metadata"] = metadata
        if observed_at is not None:
            _raw["observed_at"] = observed_at
        if source_ref is not None:
            _raw["source_ref"] = source_ref
        if to_id is not None:
            _raw["to_id"] = to_id
        if to_type is not None:
            _raw["to_type"] = to_type
        body = encode_body(CreateWisdomRelationBody, _raw)
        data = self._http.post(path, params=params, json_data=body)
        return CreateWisdomRelationOutputBody.model_validate(data)

    def delete_attributed_wisdom_relation(
        self,
        agent_id: str,
        relation_id: str,
    ) -> Any:
        """Delete an attributed wisdom relation (idempotent)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/relations/{quote(relation_id, safe='')}"
        params = None
        data = self._http.delete(path, params=params)
        return data


class AsyncWisdom(_WisdomBase):
    async def list_attributed_wisdom(
        self,
        agent_id: str,
    ) -> ListWisdomAttributedOutputBody:
        """List attributed wisdom for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/attributed"
        params = None
        data = await self._http.get(path, params=params)
        return ListWisdomAttributedOutputBody.model_validate(data)

    async def create_attributed_wisdom(
        self,
        agent_id: str,
        *,
        category: str,
        confidence: float | None = None,
        entity_display_name: str | None = None,
        entity_id: str,
        entity_type: str,
        expires_at: str | None = None,
        observed_at: str | None = None,
        source_ref: str | None = None,
        value: str,
    ) -> CreateWisdomAttributedOutputBody:
        """Create or upsert an attributed wisdom fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/attributed"
        params = None
        _raw: dict[str, Any] = {}
        if category is not None:
            _raw["category"] = category
        if confidence is not None:
            _raw["confidence"] = confidence
        if entity_display_name is not None:
            _raw["entity_display_name"] = entity_display_name
        if entity_id is not None:
            _raw["entity_id"] = entity_id
        if entity_type is not None:
            _raw["entity_type"] = entity_type
        if expires_at is not None:
            _raw["expires_at"] = expires_at
        if observed_at is not None:
            _raw["observed_at"] = observed_at
        if source_ref is not None:
            _raw["source_ref"] = source_ref
        if value is not None:
            _raw["value"] = value
        body = encode_body(CreateWisdomAttributedBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return CreateWisdomAttributedOutputBody.model_validate(data)

    async def import_attributed_wisdom(
        self,
        agent_id: str,
        *,
        data: str,
        dry_run: bool | None = None,
        format: str,
    ) -> WisdomImportResponse:
        """Bulk import attributed wisdom facts (JSON or CSV)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/attributed/import"
        params = None
        _raw: dict[str, Any] = {}
        if data is not None:
            _raw["data"] = data
        if dry_run is not None:
            _raw["dry_run"] = dry_run
        if format is not None:
            _raw["format"] = format
        body = encode_body(WisdomImportInputBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return WisdomImportResponse.model_validate(data)

    async def list_attributed_wisdom_by_entity(
        self,
        agent_id: str,
        entity_type: str,
        entity_id: str,
    ) -> ListWisdomAttributedOutputBody:
        """List attributed wisdom for one entity"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/attributed/{quote(entity_type, safe='')}/{quote(entity_id, safe='')}"
        params = None
        data = await self._http.get(path, params=params)
        return ListWisdomAttributedOutputBody.model_validate(data)

    async def delete_attributed_wisdom(
        self,
        agent_id: str,
        entity_type: str,
        entity_id: str,
        category: str,
    ) -> Any:
        """Delete an attributed wisdom fact (idempotent)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/attributed/{quote(entity_type, safe='')}/{quote(entity_id, safe='')}/{quote(category, safe='')}"
        params = None
        data = await self._http.delete(path, params=params)
        return data

    async def replace_attributed_wisdom(
        self,
        agent_id: str,
        entity_type: str,
        entity_id: str,
        category: str,
        *,
        confidence: float | None = None,
        entity_display_name: str | None = None,
        expires_at: str | None = None,
        observed_at: str | None = None,
        source_ref: str | None = None,
        value: str,
    ) -> ReplaceWisdomAttributedOutputBody:
        """Replace the value of an attributed wisdom fact"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/attributed/{quote(entity_type, safe='')}/{quote(entity_id, safe='')}/{quote(category, safe='')}"
        params = None
        _raw: dict[str, Any] = {}
        if confidence is not None:
            _raw["confidence"] = confidence
        if entity_display_name is not None:
            _raw["entity_display_name"] = entity_display_name
        if expires_at is not None:
            _raw["expires_at"] = expires_at
        if observed_at is not None:
            _raw["observed_at"] = observed_at
        if source_ref is not None:
            _raw["source_ref"] = source_ref
        if value is not None:
            _raw["value"] = value
        body = encode_body(ReplaceWisdomAttributedInputBody, _raw)
        data = await self._http.put(path, params=params, json_data=body)
        return ReplaceWisdomAttributedOutputBody.model_validate(data)

    async def list_attributed_wisdom_audit(
        self,
        agent_id: str,
        *,
        from_: str | None = None,
        to: str | None = None,
        limit: int | None = None,
    ) -> ListWisdomAuditOutputBody:
        """List attributed wisdom disclosure audit entries"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/audit"
        params: dict[str, Any] = {}
        if from_ is not None:
            params["from"] = from_
        if to is not None:
            params["to"] = to
        if limit is not None:
            params["limit"] = limit
        data = await self._http.get(path, params=params)
        return ListWisdomAuditOutputBody.model_validate(data)

    async def list_attributed_wisdom_relations(
        self,
        agent_id: str,
    ) -> ListWisdomRelationsOutputBody:
        """List attributed wisdom relations for an agent"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/relations"
        params = None
        data = await self._http.get(path, params=params)
        return ListWisdomRelationsOutputBody.model_validate(data)

    async def create_attributed_wisdom_relation(
        self,
        agent_id: str,
        *,
        edge_type: str,
        from_id: str,
        from_type: str,
        metadata: dict[str, Any] | None = None,
        observed_at: str | None = None,
        source_ref: str | None = None,
        to_id: str,
        to_type: str,
    ) -> CreateWisdomRelationOutputBody:
        """Create an attributed wisdom relation"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/relations"
        params = None
        _raw: dict[str, Any] = {}
        if edge_type is not None:
            _raw["edge_type"] = edge_type
        if from_id is not None:
            _raw["from_id"] = from_id
        if from_type is not None:
            _raw["from_type"] = from_type
        if metadata is not None:
            _raw["metadata"] = metadata
        if observed_at is not None:
            _raw["observed_at"] = observed_at
        if source_ref is not None:
            _raw["source_ref"] = source_ref
        if to_id is not None:
            _raw["to_id"] = to_id
        if to_type is not None:
            _raw["to_type"] = to_type
        body = encode_body(CreateWisdomRelationBody, _raw)
        data = await self._http.post(path, params=params, json_data=body)
        return CreateWisdomRelationOutputBody.model_validate(data)

    async def delete_attributed_wisdom_relation(
        self,
        agent_id: str,
        relation_id: str,
    ) -> Any:
        """Delete an attributed wisdom relation (idempotent)"""
        path = f"/api/v1/agents/{quote(agent_id, safe='')}/wisdom/relations/{quote(relation_id, safe='')}"
        params = None
        data = await self._http.delete(path, params=params)
        return data
