# Generated by scripts/codegen/generate_resources.py. Do not edit.
# Regenerate via `just regenerate-sdk`.
"""Auto-generated resource classes for the Memory tag."""

from __future__ import annotations

from typing import Any

from sonzai._generated.models import (
    AddFactInputBody,
    ListAllFactsResponse,
    StoredFact,
)
from sonzai._pagination import AsyncPage, Page
from sonzai._request_helpers import encode_body


class _MemoryBase:
    def __init__(self, http: Any) -> None:
        self._http = http


class Memory(_MemoryBase):
    def list_all_facts(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
        limit: int = 100,
    ) -> Page[StoredFact]:
        """Auto-generated paginated list."""
        path = f"/api/v1/agents/{agent_id}/facts/all"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        if user_id is not None:
            params["user_id"] = user_id
        return Page(
            fetcher=lambda p: self._http.get(path, params=p),
            params=params,
            item_key="facts",
            item_parser=StoredFact.model_validate,
            mode="offset",
            total_key="total",
        )
    def add_fact(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> StoredFact:
        """Auto-generated."""
        path = f"/api/v1/agents/{agent_id}/facts"
        params = None
        body = encode_body(AddFactInputBody, body_fields)
        data = self._http.post(path, params=params, body=body)
        return StoredFact.model_validate(data)


class AsyncMemory(_MemoryBase):
    async def list_all_facts(
        self,
        agent_id: str,
        *,
        user_id: str | None = None,
        limit: int = 100,
    ) -> AsyncPage[StoredFact]:
        """Auto-generated paginated list."""
        path = f"/api/v1/agents/{agent_id}/facts/all"
        params: dict[str, Any] = {"limit": limit, "offset": 0}
        if user_id is not None:
            params["user_id"] = user_id

        async def fetcher(p: dict[str, Any]) -> dict[str, Any]:
            return await self._http.get(path, params=p)

        return AsyncPage(
            fetcher=fetcher,
            params=params,
            item_key="facts",
            item_parser=StoredFact.model_validate,
            mode="offset",
            total_key="total",
        )
    async def add_fact(
        self,
        agent_id: str,
        **body_fields: Any,
    ) -> StoredFact:
        """Auto-generated."""
        path = f"/api/v1/agents/{agent_id}/facts"
        params = None
        body = encode_body(AddFactInputBody, body_fields)
        data = await self._http.post(path, params=params, body=body)
        return StoredFact.model_validate(data)
